In [157]:
from persianNumberNormalizer import PersianNumberNormalizer 
import re,pandas as pd,numpy as np,datetime

In [158]:
df = pd.read_excel("output/price_of_fertilizers - Copy (7).xlsx"
                   ,sheet_name=None)
df

{'agriplus.ir':                                                    url  \
 0    https://agriplus.ir/Product/BKP-35038/%da%a9%d...
 1    https://agriplus.ir/Product/BKP-27426/%da%a9%d...
 2    https://agriplus.ir/Product/BKP-22917/%da%a9%d...
 3    https://agriplus.ir/Product/BKP-22916/%da%a9%d...
 4    https://agriplus.ir/Product/BKP-21436/%da%a9%d...
 ..                                                 ...
 233  https://agriplus.ir/Product/BKP-14233/%d9%be%d...
 234  https://agriplus.ir/Product/BKP-37836/rooty-sg15/
 235  https://agriplus.ir/Product/BKP-24561/rooting-...
 236  https://agriplus.ir/Product/BKP-36035/rooty-ho...
 237  https://agriplus.ir/Product/BKP-37832/rooty-sy...

                                              name          category    price  \
 0                          کود NPK ۳۰ ۱۰ ۱۰ زیگلر           کود NPK      NaN
 1                 کود سه بیست لبین (NPK ۲۰ ۲۰ ۲۰)           کود NPK      NaN
 2    کود NPK تحریک گلدهی ۳۶ ۱۲ ۱۲ بسته بندی خانگی         کود خانگی  1233400
 3        کود محرک رشد ۲۰ ۲۰ ۲۰ با بسته بندی خانگی         کود خانگی   198000
 4                       کود NPK ۱۵ ۵ ۳۰ کوالی مکس           کود NPK      NaN
 ..                                            ...               ...      ...
 233                    پودر جیبرلین BERELEX ۴۰ SG  هورمون رشد گیاهی      NaN
 234    هورمون ریشه زایی هلندی روتی SG15 اگری پلاس  هورمون رشد گیاهی      NaN
 235           هورمون ریشه زایی هندی L30 اگری پلاس  هورمون رشد گیاهی      NaN
 236    هورمون ریشه‌ زایی هلندی روتی L30 اگری پلاس  هورمون رشد گیاهی      NaN
 237    هورمون ریشه زایی غلیظ روتی Syrup اگری پلاس  هورمون رشد گیاهی      NaN

      price_per_kg  amount_kg  last_price_update is_available  \
 0             NaN        NaN                NaN        False
 1             NaN        NaN                NaN        False
 2             NaN        NaN                NaN         True
 3             NaN        NaN                NaN         True
 4             NaN        NaN                NaN        False
 ..            ...        ...                ...          ...
 233           NaN        NaN                NaN        False
 234           NaN        NaN                NaN        False
 235           NaN        NaN                NaN        False
 236           NaN        NaN                NaN        False
 237           NaN        NaN                NaN        False

               created_at         last_updated  product_menu_url
 0    2025-07-22 15:50:46  2025-08-12 08:36:14               NaN
 1    2025-07-22 15:50:50  2025-08-12 08:36:20               NaN
 2    2025-07-22 15:50:52  2025-08-12 08:52:40               NaN
 3    2025-07-22 15:50:55  2025-08-12 08:53:18               NaN
 4    2025-07-22 15:50:58  2025-08-12 08:36:39               NaN
 ..                   ...                  ...               ...
 233  2025-07-22 16:34:21  2025-08-12 09:33:25               NaN
 234  2025-08-12 09:32:35  2025-08-12 09:32:35               NaN
 235  2025-08-12 09:32:48  2025-08-12 09:32:48               NaN
 236  2025-08-12 09:32:54  2025-08-12 09:32:54               NaN
 237  2025-08-12 09:33:06  2025-08-12 09:33:06               NaN

 [238 rows x 11 columns],
 'torob.com':                                                     url  \
 0     https://torob.com/p/2b84fb38-5f28-47ed-904d-1a...
 1     https://torob.com/p/ae8d4083-b06f-4d62-b5f1-38...
 2     https://torob.com/p/86e88419-cd7b-4fb1-9fb5-72...
 3     https://torob.com/p/570734d8-40be-4f91-87d7-b5...
 4     https://torob.com/p/bade8776-56ef-4605-82a5-f5...
 ...                                                 ...
 1556  https://torob.com/p/8293600b-2a42-4364-9983-cd...
 1557  https://torob.com/p/f3151753-ea93-454e-a6e2-ac...
 1558  https://torob.com/p/1d9f604d-5a93-49af-a6db-a7...
 1559  https://torob.com/p/ea2cb9c3-71b7-44ab-9a28-78...
 1560  https://torob.com/p/eeb69058-7863-423e-8bbc-4e...

                                                    name  category   price  \
 0                  کود جلبک دریایی مایع شوک اصل 5 لیتری       NaN  888000
 1                              قرص کود ارگانیک 120 عددی       NaN   66000
 2                       کود شیمیایی اوره گرانول 46 درصد       NaN   70000
 3                            پودر هیومیک اسید پلنت چویس       NaN  630000
 4     کود سه بیست 20 20 برند هایپر ایکس گرین - کود ک...       NaN  240000
 ...                                                 ...       ...     ...
 1556                      صابون حشره کش جنوبگان 5 لیتری       NaN  365000
 1557                       کود آلی مایع زرگرین ۲۰ لیتری       NaN  820000
 1558            کود نیترات کلسیم جنوبگان وزن ۲۵ کیلوگرم       NaN  110000
 1559        کود گوگرد مایع شوک ۲۰ لیتری ۸۰ درصد ارگانیک       NaN  260000
 1560           کود پلیت مرغی زرین مهر کیمیا 25 کیلوگرمی       NaN  227500

       price_per_kg  amount_kg  last_price_update  is_available  \
 0         177600.0        5.0                NaN          True
 1              NaN        NaN                NaN          True
 2              NaN        NaN                NaN          True
 3              NaN        NaN                NaN          True
 4              NaN        NaN                NaN          True
 ...            ...        ...                ...           ...
 1556       73000.0        5.0                NaN          True
 1557       41000.0       20.0                NaN          True
 1558        4400.0       25.0                NaN          True
 1559       13000.0       20.0                NaN          True
 1560        9100.0       25.0                NaN          True

                created_at         last_updated  product_menu_url
 0     2025-07-22 16:45:39  2025-07-27 16:48:28               NaN
 1     2025-07-22 16:45:40  2025-07-29 15:01:00               NaN
 2     2025-07-22 16:45:40  2025-07-22 16:45:40               NaN
 3     2025-07-22 16:45:40  2025-07-22 16:45:40               NaN
 4     2025-07-22 16:45:40  2025-07-29 15:01:04               NaN
 ...                   ...                  ...               ...
 1556  2025-07-29 15:00:59  2025-07-29 15:00:59               NaN
 1557  2025-07-29 15:02:06  2025-07-29 15:02:06               NaN
 1558  2025-07-29 15:02:12  2025-07-29 15:02:12               NaN
 1559  2025-07-29 15:02:19  2025-07-29 15:02:19               NaN
 1560  2025-07-29 15:03:02  2025-07-29 15:03:02               NaN

 [1561 rows x 11 columns],
 'digikood.com':                                                   url  \
 0   https://www.digikood.com/product/%da%a9%d9%84%...
 1   https://www.digikood.com/product/%d9%81%d8%b3%...
 2         https://www.digikood.com/product/__trashed/
 3   https://www.digikood.com/product/%da%a9%d9%88%...
 4   https://www.digikood.com/product/%d8%a7%d9%88%...
 ..                                                ...
 83  https://www.digikood.com/product/%d8%b6%d8%af-...
 84  https://www.digikood.com/product/%da%a9%d9%88%...
 85  https://www.digikood.com/product/%d8%a8%d8%a7%...
 86  https://www.digikood.com/product/%da%a9%d9%85%...
 87  https://www.digikood.com/product/%da%af%d9%88%...

                            name       category      price  price_per_kg  \
 0   کلات آهن لایفر ۶٪ اسپانیایی   شیمیایی جامد  1200000.0           NaN
 1                  فسفات گوگردی   شیمیایی جامد   850000.0       17000.0
 2                ماکرو 20 20 20   کود های ازته  3500000.0     3500000.0
 3                کود کامل خانگی   کود های ازته        NaN           NaN
 4                   اوره گوگردی   کود های ازته   850000.0       34000.0
 ..                          ...            ...        ...           ...
 83                  ضد یخ گیاهی  کودهای گوگردی        NaN           NaN
 84          کود بیولوژیک بیوراس  کود های زیستی  2125000.0       85000.0
 85   بایوکامپوزیت گوگردی (تیاس)  کودهای گوگردی  3800000.0     1900000.0
 86            کمپوست آلی سلولزی       ریز مغزی   180000.0       18000.0
 87                   گوگرد مایع  کودهای گوگردی  1750000.0      350000.0

     amount_kg  last_price_update  is_available           created_at  \
 0         0.0                NaN          True  2025-07-22 17:05:51
 1        50.0                NaN          True  2025-07-22 17:05:56
 2         1.0                NaN          True  2025-07-22 17:06:01
 3        10.0                NaN          True  2025-07-22 17:06:06
 4        25.0                NaN          True  2025-07-22 17:06:11
 ..        ...                ...           ...                  ...
 83        1.0                NaN          True  2025-07-22 17:19:39
 84       25.0                NaN          True  2025-07-22 17:20:21
 85        2.0                NaN          True  2025-07-22 17:20:26
 86       10.0                NaN          True  2025-07-22 17:20:31
 87        5.0                NaN          True  2025-07-22 17:24:31

            last_updated  product_menu_url
 0   2025-08-12 10:19:09               NaN
 1   2025-08-12 10:19:16               NaN
 2   2025-08-12 10:28:31               NaN
 3   2025-08-12 10:28:37               NaN
 4   2025-08-12 10:28:42               NaN
 ..                  ...               ...
 83  2025-07-27 17:46:51               NaN
 84  2025-07-27 17:44:48               NaN
 85  2025-07-27 17:45:47               NaN
 86  2025-07-27 17:40:18               NaN
 87  2025-07-27 17:45:52               NaN

 [88 rows x 11 columns],
 'koodforosh.com':                                      url  \
 0       https://koodforosh.com/showads/6
 1    https://koodforosh.com/showads/2194
 2    https://koodforosh.com/showads/2253
 3    https://koodforosh.com/showads/2945
 4    https://koodforosh.com/showads/2930
 ..                                   ...
 180  https://koodforosh.com/showads/3444
 181  https://koodforosh.com/showads/3445
 182  https://koodforosh.com/showads/3446
 183  https://koodforosh.com/showads/3447
 184  https://koodforosh.com/showads/3448

                                                   name    category    price  \
 0    روش استفاده از کود سولفات امونیوم گرانوله در ش...  کود سولفات  ۱۱۵,۰۰۰
 1                                  فروش کود سولفات اهن  کود سولفات      NaN
 2                                  فروش سولفات امونیوم  کود سولفات      NaN
 3                                  فروش سولفات آمونیوم  کود سولفات      NaN
 4                                       کود NK 5‐5 آفر    کود پتاس      NaN
 ..                                                 ...         ...      ...
 180           آیا کود هوموس برای همه گیاهان مناسب است؟   کود هوموس    ۲,۵۰۰
 181                   چگونه از کود هوموس استفاده کنیم؟   کود هوموس    ۲,۵۰۰
 182           کود هوموس چگونه به بهبود خاک کمک می‌کند؟   کود هوموس    ۲,۵۰۰
 183       آیا کود هوموس باعث افزایش رشد گیاهان می‌شود؟   کود هوموس    ۲,۵۰۰
 184           کود هوموس چگونه به محیط زیست کمک می‌کند؟   کود هوموس    ۲,۵۰۰

      price_per_kg  amount_kg  last_price_update  is_available  \
 0             NaN        NaN                NaN           NaN
 1             NaN        NaN                NaN           NaN
 2             NaN        NaN                NaN           NaN
 3             NaN        NaN                NaN           NaN
 4             NaN        NaN                NaN           NaN
 ..            ...        ...                ...           ...
 180           NaN        NaN                NaN           NaN
 181           NaN        NaN                NaN           NaN
 182           NaN        NaN                NaN           NaN
 183           NaN        NaN                NaN           NaN
 184           NaN        NaN                NaN           NaN

               created_at         last_updated  product_menu_url
 0    2025-07-22 17:28:23  2025-08-12 08:00:25               NaN
 1    2025-07-22 17:28:25  2025-08-12 08:00:29               NaN
 2    2025-07-22 17:28:34  2025-08-12 08:00:38               NaN
 3    2025-07-22 17:28:38  2025-08-12 08:00:43               NaN
 4    2025-07-22 17:29:20  2025-08-12 08:01:27               NaN
 ..                   ...                  ...               ...
 180  2025-07-22 17:39:06  2025-08-12 08:18:41               NaN
 181  2025-07-22 17:39:07  2025-08-12 08:18:44               NaN
 182  2025-07-22 17:39:08  2025-08-12 08:18:48               NaN
 183  2025-07-22 17:39:10  2025-08-12 08:18:51               NaN
 184  2025-07-22 17:39:11  2025-08-12 08:18:54               NaN

 [185 rows x 11 columns],
 'digikoud.com':                                                   url  \
 0   https://digikoud.com/کود-های-پتاسه/9-نیترات-پت...
 1   https://digikoud.com/کود-های-پتاسه/8-سولفات-پت...
 2   https://digikoud.com/کود-های-مرکب/37-مونو-پتاس...
 3   https://digikoud.com/کود-های-مایع/72-کود-زیستی...
 4   https://digikoud.com/کود-کامل-ماکرو-/182-ماکرو...
 ..                                                ...
 77  https://digikoud.com/کود-مخصوص-گل-و-سبزیجات/16...
 78  https://digikoud.com/کود-مخصوص-گل-و-سبزیجات/16...
 79  https://digikoud.com/کود-مخصوص-گل-و-سبزیجات/16...
 80  https://digikoud.com/کود-مخصوص-گل-و-سبزیجات/17...
 81  https://digikoud.com/کود-مخصوص-گل-و-سبزیجات/17...

                          name                    category  price  \
 0               نیترات پتاسیم            کود های مرکب\n37    NaN
 1   سولفات پتاسیم منیزیم 10/4        کود های ریز مغزی\n17    NaN
 2           مونو پتاسیم فسفات            کود های مرکب\n37    NaN
 3        کود زیستی پتابارور-2            کود های مایع\n12    NaN
 4          ماکرو کامل20/20/20      کود کامل ( ماکرو )\n23    NaN
 ..                        ...                         ...    ...
 77       کود گیاهان آپارتمانی  کود مخصوص گل و سبزیجات\n15    NaN
 78        کود گیاهان باغچه ای  کود مخصوص گل و سبزیجات\n15    NaN
 79                  کود گلدهی  کود مخصوص گل و سبزیجات\n15    NaN
 80                     کود رز  کود مخصوص گل و سبزیجات\n15    NaN
 81       کود رشد مخصوص گیاهان  کود مخصوص گل و سبزیجات\n15    NaN

     price_per_kg  amount_kg  last_price_update  is_available  \
 0            NaN        NaN                NaN           NaN
 1            NaN        NaN                NaN           NaN
 2            NaN        NaN                NaN           NaN
 3            NaN        NaN                NaN           NaN
 4            NaN        NaN                NaN           NaN
 ..           ...        ...                ...           ...
 77           NaN        NaN                NaN           NaN
 78           NaN        NaN                NaN           NaN
 79           NaN        NaN                NaN           NaN
 80           NaN        NaN                NaN           NaN
 81           NaN        NaN                NaN           NaN

              created_at         last_updated  product_menu_url
 0   2025-07-22 17:39:20  2025-08-12 08:27:27               NaN
 1   2025-07-22 17:39:23  2025-08-12 08:31:08               NaN
 2   2025-07-22 17:39:27  2025-08-12 08:27:17               NaN
 3   2025-07-22 17:39:30  2025-08-12 08:23:08               NaN
 4   2025-07-22 17:39:33  2025-08-12 08:33:11               NaN
 ..                  ...                  ...               ...
 77  2025-07-22 17:48:49  2025-08-12 08:34:57               NaN
 78  2025-07-22 17:48:52  2025-08-12 08:35:02               NaN
 79  2025-07-22 17:48:55  2025-08-12 08:35:07               NaN
 80  2025-07-22 17:49:01  2025-08-12 08:35:17               NaN
 81  2025-07-22 17:49:05  2025-08-12 08:35:21               NaN

 [82 rows x 11 columns],
 'sepahankesht.com':                                                   url  \
 0   https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 1   https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 2   https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 3   https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 4   https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 5   https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 6   https://sepahankesht.com/shop/%da%86%d8%a7%d9%...
 7   https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 8   https://sepahankesht.com/shop/%d9%87%db%8c%d9%...
 9   https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 10  https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 11  https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 12  https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 13  https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 14  https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 15  https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 16  https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 17  https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 18  https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 19  https://sepahankesht.com/shop/%da%86%d8%a7%d9%...
 20  https://sepahankesht.com/shop/%da%86%d8%a7%d9%...
 21  https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 22  https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 23  https://sepahankesht.com/shop/%d9%be%d8%aa%d8%...
 24  https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 25  https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 26  https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 27  https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 28  https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 29  https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 30  https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 31  https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 32  https://sepahankesht.com/shop/%da%a9%d9%88%d8%...

                                                  name  \
 0     کود هومی پاور پودری فیوچرکو بایوساینس ۱ کیلوگرم
 1               کود هیومیک اسید مایع هیومولایف ۵ لیتر
 2         کود هیومیک اسید گرانول هیومولایف ۲۵ کیلوگرم
 3                کود اکوسالت (کاهنده شوری خاک) ۵ لیتر
 4                کود نیچرمیک فیوچرکو بایوساینس ۵ لیتر
 5         کود هومی پاور پلاس فیوچرکو بایوساینس ۵ لیتر
 6   چالکود فرموکمپلکس همراه با گوگرد و عناصر ریزمغ...
 7                      کود یارامیلا کمپلکس ۲۵ کیلوگرم
 8                          هیومیک اسید فرتی وان AH 75
 9                کود مایع هیومیک‌اسید نوتری تک ۵ لیتر
 10     کود هیومیک دار NPK 20-5-10 هیومولایف 5 کیلوگرم
 11     کود هیومیک دار NPK 12-5-20 هیومولایف 5 کیلوگرم
 12               کود اصلاح کننده PH لوورسون (7 LOWER)
 13          کود هیومیک و فولویک اسید هیومیستار ۵ لیتر
 14         کود هیومیک اسید و فولویک اسید پابرا ۵ لیتر
 15                 کود فولویک اسید نوتریویم ۱ کیلوگرم
 16           کود ضدشوری گیاهان آپارتمانی ۶۰ میلی لیتر
 17          کود ضد شوری فورنوترینت (Anti Salt) 5 لیتر
 18               کود ضدشوری فرمولایف مدل دسالت ۵ لیتر
 19                       چال کود پارس بلدر ۲۵ کیلوگرم
 20                    چالکود پارسی لئون اس ۲۵ کیلوگرم
 21      کود اسید هیومیک گیاهان آپارتمانی ۶۰ میلی لیتر
 22                            کود ریزمغذی هوگر ۱ لیتر
 23                              کود جلبک دریایی سیفول
 24    کود فول‌فورس اس نوتریویم (FULLFORCE-S) 1کیلوگرم
 25  کود مرغی مایع نیو داتیس آل (NEW DATIS ALL) حجم...
 26          کود پودری اسیدهیومیک ASORIK وزن 1 کیلوگرم
 27     کود داتیس فورنوترینت ارگانیک (کود مرغی) ۵ لیتر
 28                 کود هیومیک اسید پابرا ۲.۵ کیلوگرمی
 29          کود هیومیک اسید پودری هیومولایف ۱ کیلوگرم
 30      کود هیومیک اسید مایع فورنوترینت OM حجم 5 لیتر
 31   کود هیومیک اسید پودری هوموکسال ۹۵% وزن ۱ کیلوگرم
 32                       کود مرغی مایع چیکوتی ۲۰ لیتر

                           category    price  price_per_kg  amount_kg  \
 0                   soil-modifying  1145760     1145760.0        1.0
 1                      هیومیک-اسید  1155000      231000.0        5.0
 2                      هیومیک-اسید  2204400       88176.0       25.0
 3         anti-salinity-fertilizer  2481600      496320.0        5.0
 4                   soil-modifying  2587200      517440.0        5.0
 5                      هیومیک-اسید  2877600      575520.0        5.0
 6                  fertilizer-hole  2970000      118800.0       25.0
 7                  fertilizer-hole  6025800      241032.0       25.0
 8                      هیومیک-اسید   194000           NaN        NaN
 9                      هیومیک-اسید   377520       75504.0        5.0
 10                     هیومیک-اسید   675840      135168.0        5.0

In [159]:
# Concatenate all the data in the 
dataFrame = pd.DataFrame()
for data in df.values():
    dataFrame = pd.concat([data,dataFrame],ignore_index=True)

dataFrame

,url,name,category,price,price_per_kg,amount_kg,last_price_update,is_available,created_at,last_updated,product_menu_url,_pk
0,https://basalam.com/greenrose/product/11745865,خاک و کود آماده کاشت تای سیز 4 لیتری,NaN,45000,28125,1.6,NaN,True,2025-08-04 10:38:26,2025-08-12 10:36:27,https://basalam.com/cat/tools/%D8%AE%D8%A7%DA%...,https://basalam.com/greenrose/product/11745865...
1,https://basalam.com/arzankadeh7berke/product/1...,خاک و کود بستر مخصوص گیاهان آبزی و میگوها اوشن...,NaN,1223800,407933.333333,3.0,NaN,True,2025-08-04 10:38:28,2025-08-12 12:01:19,https://basalam.com/cat/tools/%D8%AE%D8%A7%DA%...,https://basalam.com/arzankadeh7berke/product/1...
2,https://basalam.com/goldan.felezi/product/1507...,خاک و کود آماده کاشت 4 لیتری,NaN,40200,10050,4.0,NaN,True,2025-08-04 10:38:31,2025-08-12 10:36:24,https://basalam.com/cat/tools/%D8%AE%D8%A7%DA%...,https://basalam.com/goldan.felezi/product/1507...
3,https://basalam.com/almase_sorkh/product/11141428,خاک و کود آماده کاشت گیلدا بسته 4 لیتری,NaN,110000,47826.086957,2.3,NaN,True,2025-08-04 10:38:34,2025-08-12 10:36:16,https://basalam.com/cat/tools/%D8%AE%D8%A7%DA%...,https://basalam.com/almase_sorkh/product/11141...
4,https://basalam.com/igool/product/16423331,خاک کود آفت کش و گلدان پلیمری پک تعویض گلدان ک...,NaN,499000,nan,NaN,NaN,True,2025-08-04 10:38:37,2025-08-12 12:01:23,https://basalam.com/cat/tools/%D8%AE%D8%A7%DA%...,https://basalam.com/igool/product/16423331::خا...
...,...,...,...,...,...,...,...,...,...,...,...,...
5176,https://agriplus.ir/Product/BKP-14233/%d9%be%d...,پودر جیبرلین BERELEX ۴۰ SG,هورمون رشد گیاهی,NaN,NaN,NaN,NaN,False,2025-07-22 16:34:21,2025-08-12 09:33:25,NaN,NaN
5177,https://agriplus.ir/Product/BKP-37836/rooty-sg15/,هورمون ریشه زایی هلندی روتی SG15 اگری پلاس,هورمون رشد گیاهی,NaN,NaN,NaN,NaN,False,2025-08-12 09:32:35,2025-08-12 09:32:35,NaN,NaN
5178,https://agriplus.ir/Product/BKP-24561/rooting-...,هورمون ریشه زایی هندی L30 اگری پلاس,هورمون رشد گیاهی,NaN,NaN,NaN,NaN,False,2025-08-12 09:32:48,2025-08-12 09:32:48,NaN,NaN
5179,https://agriplus.ir/Product/BKP-36035/rooty-ho...,هورمون ریشه‌ زایی هلندی روتی L30 اگری پلاس,هورمون رشد گیاهی,NaN,NaN,NaN,NaN,False,2025-08-12 09:32:54,2025-08-12 09:32:54,NaN,NaN
5180,https://agriplus.ir/Product/BKP-37832/rooty-sy...,هورمون ریشه زایی غلیظ روتی Syrup اگری پلاس,هورمون رشد گیاهی,NaN,NaN,NaN,NaN,False,2025-08-12 09:33:06,2025-08-12 09:33:06,NaN,NaN

In [160]:
df = dataFrame

df.dropna(subset=['price_per_kg'],inplace=True)
df = df.drop(labels="created_at",axis=1)
df = df.drop(labels="last_updated",axis=1)
df.to_csv("concatenated_excel/fullRawExcel.csv")

df.drop("url",axis=1,inplace=True)

In [161]:
df = df.drop(labels="last_price_update",axis=1)
df

,name,category,price,price_per_kg,amount_kg,is_available,product_menu_url,_pk
0,خاک و کود آماده کاشت تای سیز 4 لیتری,NaN,45000,28125,1.6,True,https://basalam.com/cat/tools/%D8%AE%D8%A7%DA%...,https://basalam.com/greenrose/product/11745865...
1,خاک و کود بستر مخصوص گیاهان آبزی و میگوها اوشن...,NaN,1223800,407933.333333,3.0,True,https://basalam.com/cat/tools/%D8%AE%D8%A7%DA%...,https://basalam.com/arzankadeh7berke/product/1...
2,خاک و کود آماده کاشت 4 لیتری,NaN,40200,10050,4.0,True,https://basalam.com/cat/tools/%D8%AE%D8%A7%DA%...,https://basalam.com/goldan.felezi/product/1507...
3,خاک و کود آماده کاشت گیلدا بسته 4 لیتری,NaN,110000,47826.086957,2.3,True,https://basalam.com/cat/tools/%D8%AE%D8%A7%DA%...,https://basalam.com/almase_sorkh/product/11141...
4,خاک کود آفت کش و گلدان پلیمری پک تعویض گلدان ک...,NaN,499000,nan,NaN,True,https://basalam.com/cat/tools/%D8%AE%D8%A7%DA%...,https://basalam.com/igool/product/16423331::خا...
...,...,...,...,...,...,...,...,...
5154,کود مایع بمباردیر شوگر کیمیتک,کود کامل,13068000,13068000.0,1.0,True,NaN,NaN
5159,کود مایع محرک رشد بمباردیر,کود کامل,10920000,10920000.0,1.0,True,NaN,NaN
5170,هورمون شاخه‌ زایی شوتی (®Shooty) اگری پلاس,هورمون رشد گیاهی,5170000,51700.0,100.0,True,NaN,NaN
5172,هورمون پاکوتاهی - گلدهی کتولی (®Cotooly) اگری ...,هورمون رشد گیاهی,3100000,31000.0,100.0,True,NaN,NaN
5174,هورمون گلدهی فلوری (®Flory) اگری پلاس,هورمون رشد گیاهی,12400000,49600.0,250.0,True,NaN,NaN

In [162]:
df.drop("_pk",axis=1,inplace=True)
df

,name,category,price,price_per_kg,amount_kg,is_available,product_menu_url
0,خاک و کود آماده کاشت تای سیز 4 لیتری,NaN,45000,28125,1.6,True,https://basalam.com/cat/tools/%D8%AE%D8%A7%DA%...
1,خاک و کود بستر مخصوص گیاهان آبزی و میگوها اوشن...,NaN,1223800,407933.333333,3.0,True,https://basalam.com/cat/tools/%D8%AE%D8%A7%DA%...
2,خاک و کود آماده کاشت 4 لیتری,NaN,40200,10050,4.0,True,https://basalam.com/cat/tools/%D8%AE%D8%A7%DA%...
3,خاک و کود آماده کاشت گیلدا بسته 4 لیتری,NaN,110000,47826.086957,2.3,True,https://basalam.com/cat/tools/%D8%AE%D8%A7%DA%...
4,خاک کود آفت کش و گلدان پلیمری پک تعویض گلدان ک...,NaN,499000,nan,NaN,True,https://basalam.com/cat/tools/%D8%AE%D8%A7%DA%...
...,...,...,...,...,...,...,...
5154,کود مایع بمباردیر شوگر کیمیتک,کود کامل,13068000,13068000.0,1.0,True,NaN
5159,کود مایع محرک رشد بمباردیر,کود کامل,10920000,10920000.0,1.0,True,NaN
5170,هورمون شاخه‌ زایی شوتی (®Shooty) اگری پلاس,هورمون رشد گیاهی,5170000,51700.0,100.0,True,NaN
5172,هورمون پاکوتاهی - گلدهی کتولی (®Cotooly) اگری ...,هورمون رشد گیاهی,3100000,31000.0,100.0,True,NaN
5174,هورمون گلدهی فلوری (®Flory) اگری پلاس,هورمون رشد گیاهی,12400000,49600.0,250.0,True,NaN

In [163]:
normalizer = PersianNumberNormalizer()
df['name'] = normalizer.convert(df['name'])

In [164]:
# convert all of the prices to float
df["price_per_kg"] = pd.to_numeric(df["price_per_kg"], errors="coerce").astype(float)

In [165]:
df

,name,category,price,price_per_kg,amount_kg,is_available,product_menu_url
0,خاک و کود آماده کاشت تای سیز 4 لیتری,NaN,45000,2.812500e+04,1.6,True,https://basalam.com/cat/tools/%D8%AE%D8%A7%DA%...
1,خاک و کود بستر مخصوص گیاهان آبزی و میگوها اوشن...,NaN,1223800,4.079333e+05,3.0,True,https://basalam.com/cat/tools/%D8%AE%D8%A7%DA%...
2,خاک و کود آماده کاشت 4 لیتری,NaN,40200,1.005000e+04,4.0,True,https://basalam.com/cat/tools/%D8%AE%D8%A7%DA%...
3,خاک و کود آماده کاشت گیلدا بسته 4 لیتری,NaN,110000,4.782609e+04,2.3,True,https://basalam.com/cat/tools/%D8%AE%D8%A7%DA%...
4,خاک کود آفت کش و گلدان پلیمری پک تعویض گلدان ک...,NaN,499000,NaN,NaN,True,https://basalam.com/cat/tools/%D8%AE%D8%A7%DA%...
...,...,...,...,...,...,...,...
5154,کود مایع بمباردیر شوگر کیمیتک,کود کامل,13068000,1.306800e+07,1.0,True,NaN
5159,کود مایع محرک رشد بمباردیر,کود کامل,10920000,1.092000e+07,1.0,True,NaN
5170,هورمون شاخه‌ زایی شوتی (®Shooty) اگری پلاس,هورمون رشد گیاهی,5170000,5.170000e+04,100.0,True,NaN
5172,هورمون پاکوتاهی - گلدهی کتولی (®Cotooly) اگری ...,هورمون رشد گیاهی,3100000,3.100000e+04,100.0,True,NaN
5174,هورمون گلدهی فلوری (®Flory) اگری پلاس,هورمون رشد گیاهی,12400000,4.960000e+04,250.0,True,NaN

In [166]:
raw_source_df = pd.read_excel(io="source/raw_source_of_fertilizer.xlsx")

**Filter specific fertilizer**

npk

In [167]:
# Compile all positive patterns into one regex
include_pattern = r"(npk|n\s*p\s*k|کامل)"
exclude_pattern = r"(خاک)"

filtered_df_npk = df[
    df['name'].str.lower().str.contains(include_pattern, regex=True, na=False)
    & ~df['name'].str.contains(exclude_pattern, regex=True, na=False)
]

C:\Users\pc\AppData\Local\Temp\ipykernel_12608\3938185361.py:6: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df['name'].str.lower().str.contains(include_pattern, regex=True, na=False)
C:\Users\pc\AppData\Local\Temp\ipykernel_12608\3938185361.py:7: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  & ~df['name'].str.contains(exclude_pattern, regex=True, na=False)

In [168]:
raw_source_df.columns

Index(['sub_input_code', 'input_code', 'Name_of_fertilizer',
       'Group_of_fertilizer', 'Real_Name_of_fertilizer', 'Minimum_Price(Kg)',
       'Maximum_Price(Kg)', 'Exact_Price(Kg)', 'Sources', 'sources_unique',
       'Group_of_fertilizer_unique'],
      dtype='object')

In [169]:
raw_source_df_npk_filtered = raw_source_df[raw_source_df["input_code"] == 17]
raw_source_df_npk_filtered

,sub_input_code,input_code,Name_of_fertilizer,Group_of_fertilizer,Real_Name_of_fertilizer,Minimum_Price(Kg),Maximum_Price(Kg),Exact_Price(Kg),Sources,sources_unique,Group_of_fertilizer_unique
58,111,17,17-111,کود های کامل (N-P-K),20-20-20,900000,2300000,NaN,https://torob.com/,NaN,NaN
59,112,17,17-112,کود های کامل (N-P-K),12-12-36,1690000,2480000,NaN,https://torob.com/,NaN,NaN
60,113,17,17-113,کود های کامل (N-P-K),10-52-10,1700000,2956000,NaN,https://torob.com/,NaN,NaN
61,114,17,17-114,کود های کامل (N-P-K),15-5-40,1690000,2480000,NaN,https://torob.com/,NaN,NaN
62,115,17,17-115,کود های کامل (N-P-K),5-5-15,1690000,2480000,NaN,https://torob.com/,NaN,NaN
63,116,17,17-116,کود های کامل (N-P-K),15-5-30,1690000,2480000,NaN,https://torob.com/,NaN,NaN
64,117,17,17-117,کود های کامل (N-P-K),14-8-30,1690000,2480000,NaN,https://torob.com/,NaN,NaN
65,118,17,17-118,کود های کامل (N-P-K),18-8-30,1690000,2480000,NaN,https://torob.com/,NaN,NaN
66,119,17,17-119,کود های کامل (N-P-K),15-8-15,1090000,1090000,1090000.0,https://torob.com/,NaN,NaN
67,120,17,17-120,کود های کامل (N-P-K),10-4-44,1690000,2480000,NaN,https://torob.com/,NaN,NaN
68,121,17,17-121,کود های کامل (N-P-K),13-40-13,1090000,1090000,1090000.0,https://torob.com/,NaN,NaN
69,122,17,17-122,کود های کامل (N-P-K),12-8-40,1690000,2480000,NaN,https://torob.com/,NaN,NaN
70,123,17,17-123,کود های کامل (N-P-K),15-10-30,1690000,2480000,NaN,https://torob.com/,NaN,NaN
71,124,17,17-124,کود های کامل (N-P-K),12-3-43,1690000,2480000,NaN,https://torob.com/,NaN,NaN
72,125,17,17-125,کود های کامل (N-P-K),30-10-10,3120000,3120000,3120000.0,https://agriplus.ir/,NaN,NaN
73,126,17,17-126,کود های کامل (N-P-K),12-12-17,970000,970000,970000.0,https://torob.com/,NaN,NaN
74,127,17,17-127,کود های کامل (N-P-K),10-10-43,1690000,2480000,NaN,https://torob.com/,NaN,NaN
75,128,17,17-128,کود های کامل (N-P-K),15-5-15,900000,2300000,NaN,https://torob.com/,NaN,NaN
76,129,17,17-129,کود های کامل (N-P-K),18-18-18,4200000,4200000,4200000.0,https://torob.com/,NaN,NaN
77,130,17,17-130,کود های کامل (N-P-K),3-11-38,1690000,2480000,NaN,https://torob.com/,NaN,NaN
78,131,17,17-131,کود های کامل (N-P-K),20-5-10,3120000,3120000,3120000.0,https://agriplus.ir/,NaN,NaN
79,132,17,17-132,کود های کامل (N-P-K),30-6-6,3120000,3120000,3120000.0,https://agriplus.ir/,NaN,NaN
80,133,17,17-133,کود های کامل (N-P-K),40-5-5,3120000,3120000,3120000.0,https://agriplus.ir/,NaN,NaN
81,134,17,17-134,کود های کامل (N-P-K),10-45-10,3200000,3200000,3200000.0,https://torob.com/,NaN,NaN
82,135,17,17-135,کود های کامل (N-P-K),10-5-40,1690000,2480000,NaN,https://torob.com/,NaN,NaN
83,136,17,17-136,کود های کامل (N-P-K),18-10-18,1690000,2480000,NaN,https://torob.com/,NaN,NaN
84,137,17,17-137,کود های کامل (N-P-K),10-30-10,1690000,2480000,NaN,https://torob.com/,NaN,NaN
85,138,17,17-138,کود های کامل (N-P-K),5-5-45,1690000,2480000,NaN,https://torob.com/,NaN,NaN
86,139,17,17-139,کود های کامل (N-P-K),19-6-20,5000000,5000000,5000000.0,https://torob.com/,NaN,NaN
87,140,17,17-140,کود های کامل (N-P-K),4-5-40,1690000,2480000,NaN,https://torob.com/,NaN,NaN
88,141,17,17-141,کود های کامل (N-P-K),15-50-5,3200000,3200000,3200000.0,https://torob.com/,NaN,NaN
89,142,17,17-142,کود های کامل (N-P-K),12-3-43,1690000,2480000,NaN,https://torob.com/,NaN,NaN
90,143,17,17-143,کود های کامل (N-P-K),10-40-10,3200000,3200000,3200000.0,https://torob.com/,NaN,NaN
91,144,17,17-144,کود های کامل (N-P-K),5-10-40,1690000,2480000,NaN,https://torob.com/,NaN,NaN
92,145,17,17-145,کود های کامل (N-P-K),19-19-19,3700000,3700000,3700000.0,https://torob.com/,NaN,NaN
93,146,17,17-146,کود های کامل (N-P-K),15-5-26,1690000,2480000,NaN,https://torob.com/,NaN,NaN
94,147,17,17-147,کود های کامل (N-P-K),17-4-30,1690000,2480000,NaN,https://torob.com/,NaN,NaN
95,148,17,17-148,کود های کامل (N-P-K),40-10-10,1440000,1440000,1440000.0,https://torob.com/,NaN,NaN
96,149,17,17-149,کود های کامل (N-P-K),16-7-28,1690000,2480000,NaN,https://torob.com/,NaN,NaN
97,150,17,17-150,کود های کامل (N-P-K),15-30-15,1700000,1700000,1700000.0,https://torob.com/,NaN,NaN
98,151,17,17-151,کود های کامل (N-P-K),18-16-24,1690000,2480000,NaN,https://torob.com/,NaN,NaN

In [170]:
allRawNpkRealNamesList = (
    raw_source_df_npk_filtered.iloc[:, 4]
    .astype(str)
    # Replace "-" with space
    .str.replace("-", " ", regex=False)
    # Replace +TE (case-insensitive) with " TE"
    .str.replace(r"\+TE", " TE", case=False, regex=True)
    # Replace +Ca (case-insensitive) with " Ca"
    .str.replace(r"\+Ca", " Ca", case=False, regex=True)
    # Collapse multiple spaces to one
    .str.replace(r"\s+", " ", regex=True)
    # Strip extra spaces at start/end
    .str.strip()
    .tolist()
)
allRawNpkRealNamesList

['20 20 20',
 '12 12 36',
 '10 52 10',
 '15 5 40',
 '5 5 15',
 '15 5 30',
 '14 8 30',
 '18 8 30',
 '15 8 15',
 '10 4 44',
 '13 40 13',
 '12 8 40',
 '15 10 30',
 '12 3 43',
 '30 10 10',
 '12 12 17',
 '10 10 43',
 '15 5 15',
 '18 18 18',
 '3 11 38',
 '20 5 10',
 '30 6 6',
 '40 5 5',
 '10 45 10',
 '10 5 40',
 '18 10 18',
 '10 30 10',
 '5 5 45',
 '19 6 20',
 '4 5 40',
 '15 50 5',
 '12 3 43',
 '10 40 10',
 '5 10 40',
 '19 19 19',
 '15 5 26',
 '17 4 30',
 '40 10 10',
 '16 7 28',
 '15 30 15',
 '18 16 24']

In [171]:
filtered_df_npk

,name,category,price,price_per_kg,amount_kg,is_available,product_menu_url
909,کود سه بیست شوک npk آمریکایی اصل مایع 1 لیتری ...,NaN,410٬000,NaN,NaN,NaN,NaN
910,کود کامل پودری 30 گرمی 20-20-20 شرکت زیست فناو...,NaN,42٬500,NaN,NaN,NaN,NaN
930,کود کامل سه بیست شوک اصل آمریکایی 5 لیتری مایع...,NaN,904٬400,NaN,NaN,NaN,NaN
942,کود کامل سه بیست مایع (NPK 20-20-20+TE+HA) برن...,NaN,599٬000,NaN,NaN,NaN,NaN
949,سم سوسک ریپلزال تحت لیسانس درجه یک با ضمانت ری...,NaN,490000,NaN,NaN,True,https://basalam.com/cat/tools/%D8%AE%D8%A7%DA%...
...,...,...,...,...,...,...,...
4970,کود سه بیست (NPK 20 20 20) کوالی مکس,کود NPK,29000000,29000000.0,1.0,True,NaN
4982,کود 10 52 10 NPK زیگلر آلمان,کود NPK,3960000,3960000.0,1.0,True,NaN
4984,کود NPK 11 53 05 اینترمگ,کود NPK,NaN,52600000.0,1.0,False,NaN
4988,کود 36 12 12 NPK فرمولایف,کود NPK,28175000,28175000.0,1.0,True,NaN
4992,کود NPK 15 5 30 زیگلر,کود NPK,50030000,50030000.0,1.0,True,NaN

In [172]:
# rows = []

# # NPK to Dataframe
# for name in allRawNpkRealNamesList:
#     filtered = filtered_df_npk[filtered_df_npk['name'].str.contains(name, na=False)]
#     if filtered.empty:
#         continue  # skip if no matches
    
#     row = {
#         "code": raw_source_df_npk_filtered.iloc[allRawNpkRealNamesList.index(name),2], 
#         "name": name,
#         "med": filtered['price_per_kg'].mean(), 
#         "min": filtered['price_per_kg'].min(),
#         "max": filtered['price_per_kg'].max(),
#         "std": filtered['price_per_kg'].std(),
#         "listOfNames": filtered['name'].tolist(),
#         "listOfPrices": filtered['price_per_kg'].tolist(),
#     }
#     rows.append(row)

# # Convert list of dicts directly to a DataFrame
# result_df = pd.DataFrame(rows)

# print(result_df)

In [173]:
import re
import pandas as pd

rows = []

# Loop with index to avoid .index() inefficiency
for idx, name in enumerate(allRawNpkRealNamesList):
    # Normalize pattern for flexible matching:
    # - Escape regex special chars
    # - Allow spaces, slashes, or dashes between numbers
    # - Remove "+TE" from matching requirements
    pattern = re.escape(name)
    pattern = pattern.replace(r"\ ", r"[\s\-\/]*")  # flexible spaces/dashes/slashes
    pattern = re.sub(r"\+te$", r"(?:\+te)?", pattern, flags=re.IGNORECASE)  # optional +TE

    filtered = filtered_df_npk[
        filtered_df_npk['name']
        .str.lower()
        .str.contains(pattern, regex=True, na=False)
    ]

    if filtered.empty:
        continue

    row = {
        "code": raw_source_df_npk_filtered.iloc[idx, 2],
        "name": name,
        "med": filtered['price_per_kg'].mean(),
        "min": filtered['price_per_kg'].min(),
        "max": filtered['price_per_kg'].max(),
        "std": filtered['price_per_kg'].std(),
        "listOfNames": filtered['name'].tolist(),
        "listOfPrices": filtered['price_per_kg'].tolist(),
    }
    rows.append(row)

# Final DataFrame
result_df = pd.DataFrame(rows)
print(result_df)

      code      name           med           min         max           std  \
0   17-111  20 20 20  1.672539e+06  1.200000e+05  29000000.0  5.534420e+06
1   17-112  12 12 36  3.014300e+05  2.167200e+05    519000.0  1.458177e+05
2   17-113  10 52 10  2.759341e+06  2.500000e+03  32000000.0  8.144183e+06
3   17-116   15 5 30  5.003000e+07  5.003000e+07  50030000.0           NaN
4   17-119   15 8 15  1.892000e+05  1.892000e+05    189200.0           NaN
5   17-124   12 3 43           NaN           NaN         NaN           NaN
6   17-125  30 10 10  7.153333e+05  4.760000e+05    980000.0  2.529532e+05
7   17-129  18 18 18  2.758043e+06  6.260870e+05   4890000.0  3.015042e+06
8   17-131   20 5 10  1.351680e+05  1.351680e+05    135168.0           NaN
9   17-133    40 5 5  3.425000e+05  3.425000e+05    342500.0           NaN
10  17-139   19 6 20  4.890000e+06  4.890000e+06   4890000.0           NaN
11  17-142   12 3 43           NaN           NaN         NaN           NaN

                                          listOfNames  \
0   [کود کامل پودری 30 گرمی 20-20-20 شرکت زیست فنا...
1   [کود کامل 12-12-36 باواریا آلمان ( 50گرم کود خ...
2   [فسفر بالا .کود ریشه زایی گل طبیعی گل آپارتمان...
3   [کود کامل 15530 25 کیلویی فرمولایف پس کرایه, ک...
4                                [ماکرو کامل 15/8/15]
5   [کود دوازده سه چهل و سه NPK 12 3 43 متد اسپانی...
6   [کود افزایش رشد نیتروژن بالا ( ازت بالا ) NPK ...
7   [کود کامل 18-18-18 جهت افزایش سرعت رشد و سبزین...
8    [کود هیومیک دار NPK 20-5-10 هیومولایف 5 کیلوگرم]
9                [كود کامل 40-5-5 هورتی گرو 2 کیلویی]
10                          [کود NPK 19 6 20 باواریا]
11  [کود دوازده سه چهل و سه NPK 12 3 43 متد اسپانی...

                                         listOfPrices
0   [nan, nan, nan, nan, nan, nan, 295000.0, 58333...
1   [nan, nan, nan, nan, nan, nan, nan, nan, nan, ...
2   [nan, nan, 750000.0, 300000.0, 960000.0, 27500...
3                                   [nan, 50030000.0]
4                                          [189200.0]
5                                               [nan]
6                      [980000.0, 476000.0, 690000.0]
7                  [nan, 626086.956521739, 4890000.0]
8                                          [135168.0]
9                                          [342500.0]
10                                        [4890000.0]
11                                              [nan]

In [174]:
import re
import pandas as pd

rows = []

for idx, name in enumerate(allRawNpkRealNamesList):
    name_norm = name.lower().strip()

    # Flexible matching between numbers (any non-digit chars allowed)
    m = re.match(r'(\d+)\D+(\d+)\D+(\d+)', name_norm)
    if m:
        pattern = f"{m.group(1)}\\D*{m.group(2)}\\D*{m.group(3)}"
    else:
        pattern = re.escape(name_norm)

    # Make +TE / +Ca / +ME optional at the end (case-insensitive)
    pattern = re.sub(
        r'(\\\+\s*(?:te|ca|me))$',
        r'(?:\1)?',
        pattern,
        flags=re.IGNORECASE
    )

    filtered = filtered_df_npk[
        filtered_df_npk['name']
        .str.lower()
        .str.contains(pattern, regex=True, na=False)
    ]

    if filtered.empty:
        continue

    row = {
        "code": raw_source_df_npk_filtered.iloc[idx, 2],
        "name": name,
        "med": filtered['price_per_kg'].mean(),
        "min": filtered['price_per_kg'].min(),
        "max": filtered['price_per_kg'].max(),
        "std": filtered['price_per_kg'].std(),
        "listOfNames": filtered['name'].tolist(),
        "listOfPrices": filtered['price_per_kg'].tolist(),
    }
    rows.append(row)

result_df = pd.DataFrame(rows)
print(result_df)

      code      name           med           min         max           std  \
0   17-111  20 20 20  1.621734e+06  1.200000e+05  29000000.0  5.437614e+06
1   17-112  12 12 36  3.014300e+05  2.167200e+05    519000.0  1.458177e+05
2   17-113  10 52 10  2.499615e+06  2.500000e+03  32000000.0  7.654907e+06
3   17-116   15 5 30  5.003000e+07  5.003000e+07  50030000.0           NaN
4   17-119   15 8 15  1.892000e+05  1.892000e+05    189200.0           NaN
5   17-124   12 3 43           NaN           NaN         NaN           NaN
6   17-125  30 10 10  7.153333e+05  4.760000e+05    980000.0  2.529532e+05
7   17-129  18 18 18  2.758043e+06  6.260870e+05   4890000.0  3.015042e+06
8   17-131   20 5 10  1.351680e+05  1.351680e+05    135168.0           NaN
9   17-133    40 5 5  3.425000e+05  3.425000e+05    342500.0           NaN
10  17-139   19 6 20  4.890000e+06  4.890000e+06   4890000.0           NaN
11  17-142   12 3 43           NaN           NaN         NaN           NaN

                                          listOfNames  \
0   [کود کامل پودری 30 گرمی 20-20-20 شرکت زیست فنا...
1   [کود کامل 12-12-36 باواریا آلمان ( 50گرم کود خ...
2   [فسفر بالا .کود ریشه زایی گل طبیعی گل آپارتمان...
3   [کود کامل 15530 25 کیلویی فرمولایف پس کرایه, ک...
4                                [ماکرو کامل 15/8/15]
5   [کود دوازده سه چهل و سه NPK 12 3 43 متد اسپانی...
6   [کود افزایش رشد نیتروژن بالا ( ازت بالا ) NPK ...
7   [کود کامل 18-18-18 جهت افزایش سرعت رشد و سبزین...
8    [کود هیومیک دار NPK 20-5-10 هیومولایف 5 کیلوگرم]
9                [كود کامل 40-5-5 هورتی گرو 2 کیلویی]
10                          [کود NPK 19 6 20 باواریا]
11  [کود دوازده سه چهل و سه NPK 12 3 43 متد اسپانی...

                                         listOfPrices
0   [nan, nan, nan, nan, nan, nan, 295000.0, 58333...
1   [nan, nan, nan, nan, nan, nan, nan, nan, nan, ...
2   [nan, nan, 750000.0, 983333.333333333, 300000....
3                                   [nan, 50030000.0]
4                                          [189200.0]
5                                               [nan]
6                      [980000.0, 476000.0, 690000.0]
7                  [nan, 626086.956521739, 4890000.0]
8                                          [135168.0]
9                                          [342500.0]
10                                        [4890000.0]
11                                              [nan]

In [175]:
npk_excluded_raw_source = raw_source_df[raw_source_df["input_code"] != 17]
npk_excluded_raw_source

,sub_input_code,input_code,Name_of_fertilizer,Group_of_fertilizer,Real_Name_of_fertilizer,Minimum_Price(Kg),Maximum_Price(Kg),Exact_Price(Kg),Sources,sources_unique,Group_of_fertilizer_unique
0,111,11,11-111,کود نیتروژن (ازته),اوره,25000,600000,42500.0,https://www.bbk-iran.com/,https://www.bbk-iran.com/,کود نیتروژن (ازته)
1,112,11,11-112,کود نیتروژن (ازته),آمونیاک,440000,440000,440000.0,https://shimistore.com/product/ammonia/,https://shimistore.com/product/ammonia/,کود فسفاته
2,113,11,11-113,کود نیتروژن (ازته),نیترات آمونیوم,640000,640000,640000.0,torob.com,torob.com,کود پتاسه
3,114,11,11-114,کود نیتروژن (ازته),اسید نیتریک,640000,640000,640000.0,torob.com,https://www.bbk-iran.com,کود کلسیم
4,115,11,11-115,کود نیتروژن (ازته),سولفات آمونیوم,210000,100000,155000.0,https://www.bbk-iran.com,https://digikoud.com/,کود منیزیم
...,...,...,...,...,...,...,...,...,...,...,...
190,113,99,99-113,سایر کود ها,ضد شوری,3120000,4100000,NaN,https://torob.com/,NaN,NaN
191,114,99,99-114,سایر کود ها,ضد تنش,3990000,3990000,NaN,https://sepahankesht.com/,NaN,NaN
192,115,99,99-115,سایر کود ها,اصلاح کننده خاک,420000,3200000,NaN,https://torob.com/,NaN,NaN
193,116,99,99-116,سایر کود ها,اصلاح کننده ph,1220000,1650000,NaN,https://torob.com/,NaN,NaN
194,117,99,99-117,سایر کود ها,ریشه زا ( تریکوران، پارس باسیل و ...),6890000,8450000,NaN,https://torob.com/,NaN,NaN

In [176]:
npk_excluded_raw_source.iloc[:,4].tolist()
cleaned_col = npk_excluded_raw_source.iloc[:, 4].str.replace("+", " ", regex=False).str.replace("\xad\u200c", " ", regex=False)
npk_excluded_raw_source.iloc[:,4] = cleaned_col
npk_excluded_raw_source

,sub_input_code,input_code,Name_of_fertilizer,Group_of_fertilizer,Real_Name_of_fertilizer,Minimum_Price(Kg),Maximum_Price(Kg),Exact_Price(Kg),Sources,sources_unique,Group_of_fertilizer_unique
0,111,11,11-111,کود نیتروژن (ازته),اوره,25000,600000,42500.0,https://www.bbk-iran.com/,https://www.bbk-iran.com/,کود نیتروژن (ازته)
1,112,11,11-112,کود نیتروژن (ازته),آمونیاک,440000,440000,440000.0,https://shimistore.com/product/ammonia/,https://shimistore.com/product/ammonia/,کود فسفاته
2,113,11,11-113,کود نیتروژن (ازته),نیترات آمونیوم,640000,640000,640000.0,torob.com,torob.com,کود پتاسه
3,114,11,11-114,کود نیتروژن (ازته),اسید نیتریک,640000,640000,640000.0,torob.com,https://www.bbk-iran.com,کود کلسیم
4,115,11,11-115,کود نیتروژن (ازته),سولفات آمونیوم,210000,100000,155000.0,https://www.bbk-iran.com,https://digikoud.com/,کود منیزیم
...,...,...,...,...,...,...,...,...,...,...,...
190,113,99,99-113,سایر کود ها,ضد شوری,3120000,4100000,NaN,https://torob.com/,NaN,NaN
191,114,99,99-114,سایر کود ها,ضد تنش,3990000,3990000,NaN,https://sepahankesht.com/,NaN,NaN
192,115,99,99-115,سایر کود ها,اصلاح کننده خاک,420000,3200000,NaN,https://torob.com/,NaN,NaN
193,116,99,99-116,سایر کود ها,اصلاح کننده ph,1220000,1650000,NaN,https://torob.com/,NaN,NaN
194,117,99,99-117,سایر کود ها,ریشه زا ( تریکوران، پارس باسیل و ...),6890000,8450000,NaN,https://torob.com/,NaN,NaN

Other fertilizers

In [177]:


# # Others to Dataframe
# for counter in range(len(npk_excluded_raw_source.iloc[:,4].tolist())):
#     name = npk_excluded_raw_source.iloc[:,4].tolist()[counter]
#     filtered = df[df['name'].str.contains(re.escape(name), na=False, case=False)]
#     if filtered.empty:
#         continue  # skip if no matches
    
#     row = {
#         "code": npk_excluded_raw_source.iloc[counter,2], 
#         "name": name,
#         "med": filtered['price_per_kg'].mean(), 
#         "min": filtered['price_per_kg'].min(),
#         "max": filtered['price_per_kg'].max(),
#         "std": filtered['price_per_kg'].std(),
#         "listOfNames": filtered['name'].tolist(),
#         "listOfPrices": filtered['price_per_kg'].tolist(),
#     }
#     rows.append(row)

# # Convert list of dicts directly to a DataFrame
# result_df = pd.DataFrame(rows)

# print(result_df)

In [178]:
import pandas as pd

def contains_all_words(text, words):
    """Check if all words are present in text (any order). Case insensitive."""
    text_lower = str(text).lower()
    return all(word in text_lower for word in words)

for counter, full_name in enumerate(npk_excluded_raw_source.iloc[:, 4].tolist()):
    words = full_name.split()
    
    # Filter rows where 'name' column contains all words (in any order)
    filtered = df[df['name'].apply(lambda x: contains_all_words(x, words))]
    
    if filtered.empty:
        continue  # skip if no matches
    
    row = {
        "code": npk_excluded_raw_source.iloc[counter, 2],
        "name": full_name,
        "med": filtered['price_per_kg'].mean(),
        "min": filtered['price_per_kg'].min(),
        "max": filtered['price_per_kg'].max(),
        "std": filtered['price_per_kg'].std(),
        "listOfNames": filtered['name'].tolist(),
        "listOfPrices": filtered['price_per_kg'].tolist(),
    }
    rows.append(row)

result_df = pd.DataFrame(rows)
print(result_df)

      code             name           med         min           max  \
0   17-111         20 20 20  1.621734e+06    120000.0  2.900000e+07
1   17-112         12 12 36  3.014300e+05    216720.0  5.190000e+05
2   17-113         10 52 10  2.499615e+06      2500.0  3.200000e+07
3   17-116          15 5 30  5.003000e+07  50030000.0  5.003000e+07
4   17-119          15 8 15  1.892000e+05    189200.0  1.892000e+05
..     ...              ...           ...         ...           ...
80  22-125   قارچ تریکودرما  1.980000e+06   1980000.0  1.980000e+06
81  99-111      کود بذر مال  9.660000e+05    966000.0  9.660000e+05
82  99-113          ضد شوری  4.238398e+05     62400.0  9.166667e+05
83  99-114           ضد تنش  1.193237e+06    550000.0  3.000000e+06
84  99-115  اصلاح کننده خاک  4.616871e+05    182500.0  1.200000e+06

             std                                        listOfNames  \
0   5.437614e+06  [کود کامل پودری 30 گرمی 20-20-20 شرکت زیست فنا...
1   1.458177e+05  [کود کامل 12-12-36 باواریا آلمان ( 50گرم کود خ...
2   7.654907e+06  [فسفر بالا .کود ریشه زایی گل طبیعی گل آپارتمان...
3            NaN  [کود کامل 15530 25 کیلویی فرمولایف پس کرایه, ک...
4            NaN                               [ماکرو کامل 15/8/15]
..           ...                                                ...
80           NaN           [قارچ کش بیولوژیک خاک تریکودرما 50 گرمی]
81           NaN  [کود بذرمال روی یاراویتا-پس کرایه, کود بذرمال ...
82  3.257902e+05  [کود ضد شوری و اصلاح کننده خاک دسالت (100 سی س...
83  9.124681e+05  [اسید هیومیک ضد تنش ضد شوری اصلاح بافت خاک, کو...
84  3.094920e+05  [کود ضد شوری و اصلاح کننده خاک دسالت (100 سی س...

                                         listOfPrices
0   [nan, nan, nan, nan, nan, nan, 295000.0, 58333...
1   [nan, nan, nan, nan, nan, nan, nan, nan, nan, ...
2   [nan, nan, 750000.0, 983333.333333333, 300000....
3                                   [nan, 50030000.0]
4                                          [189200.0]
..                                                ...
80                                        [1980000.0]
81                                    [966000.0, nan]
82  [560000.0, 916666.666666666, nan, nan, 62400.0...
83  [916666.666666666, 900000.0, nan, nan, 1166666...
84  [560000.0, 279166.666666666, nan, nan, 520000....

[85 rows x 8 columns]

In [179]:
result_df

,code,name,med,min,max,std,listOfNames,listOfPrices
0,17-111,20 20 20,1.621734e+06,120000.0,2.900000e+07,5.437614e+06,[کود کامل پودری 30 گرمی 20-20-20 شرکت زیست فنا...,"[nan, nan, nan, nan, nan, nan, 295000.0, 58333..."
1,17-112,12 12 36,3.014300e+05,216720.0,5.190000e+05,1.458177e+05,[کود کامل 12-12-36 باواریا آلمان ( 50گرم کود خ...,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ..."
2,17-113,10 52 10,2.499615e+06,2500.0,3.200000e+07,7.654907e+06,[فسفر بالا .کود ریشه زایی گل طبیعی گل آپارتمان...,"[nan, nan, 750000.0, 983333.333333333, 300000...."
3,17-116,15 5 30,5.003000e+07,50030000.0,5.003000e+07,NaN,"[کود کامل 15530 25 کیلویی فرمولایف پس کرایه, ک...","[nan, 50030000.0]"
4,17-119,15 8 15,1.892000e+05,189200.0,1.892000e+05,NaN,[ماکرو کامل 15/8/15],[189200.0]
...,...,...,...,...,...,...,...,...
80,22-125,قارچ تریکودرما,1.980000e+06,1980000.0,1.980000e+06,NaN,[قارچ کش بیولوژیک خاک تریکودرما 50 گرمی],[1980000.0]
81,99-111,کود بذر مال,9.660000e+05,966000.0,9.660000e+05,NaN,"[کود بذرمال روی یاراویتا-پس کرایه, کود بذرمال ...","[966000.0, nan]"
82,99-113,ضد شوری,4.238398e+05,62400.0,9.166667e+05,3.257902e+05,[کود ضد شوری و اصلاح کننده خاک دسالت (100 سی س...,"[560000.0, 916666.666666666, nan, nan, 62400.0..."
83,99-114,ضد تنش,1.193237e+06,550000.0,3.000000e+06,9.124681e+05,"[اسید هیومیک ضد تنش ضد شوری اصلاح بافت خاک, کو...","[916666.666666666, 900000.0, nan, nan, 1166666..."
84,99-115,اصلاح کننده خاک,4.616871e+05,182500.0,1.200000e+06,3.094920e+05,[کود ضد شوری و اصلاح کننده خاک دسالت (100 سی س...,"[560000.0, 279166.666666666, nan, nan, 520000...."

In [180]:

# # Others to Dataframe
# for counter in range(len(npk_excluded_raw_source.iloc[:,4].tolist())):
#     name = npk_excluded_raw_source.iloc[:,4].tolist()[counter]
#     filtered = df[df['name'].str.contains(re.escape(name), na=False, case=False)]
#     if filtered.empty:
#         continue  # skip if no matches
    
#     row = {
#         "code": npk_excluded_raw_source.iloc[counter,2], 
#         "name": name,
#         "med": filtered['price_per_kg'].median(), 
#         "min": filtered['price_per_kg'].min(),
#         "max": filtered['price_per_kg'].max(),
#         "std": filtered['price_per_kg'].std(),
#         "listOfNames": filtered['name'].tolist(),
#         "listOfPrices": filtered['price_per_kg'].tolist(),
#     }
#     rows.append(row)

# # Convert list of dicts directly to a DataFrame
# #npkExcludedResultRows = pd.DataFrame(rows)
# result_df = pd.DataFrame(rows)

# print(result_df)

In [181]:
result_df

,code,name,med,min,max,std,listOfNames,listOfPrices
0,17-111,20 20 20,1.621734e+06,120000.0,2.900000e+07,5.437614e+06,[کود کامل پودری 30 گرمی 20-20-20 شرکت زیست فنا...,"[nan, nan, nan, nan, nan, nan, 295000.0, 58333..."
1,17-112,12 12 36,3.014300e+05,216720.0,5.190000e+05,1.458177e+05,[کود کامل 12-12-36 باواریا آلمان ( 50گرم کود خ...,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ..."
2,17-113,10 52 10,2.499615e+06,2500.0,3.200000e+07,7.654907e+06,[فسفر بالا .کود ریشه زایی گل طبیعی گل آپارتمان...,"[nan, nan, 750000.0, 983333.333333333, 300000...."
3,17-116,15 5 30,5.003000e+07,50030000.0,5.003000e+07,NaN,"[کود کامل 15530 25 کیلویی فرمولایف پس کرایه, ک...","[nan, 50030000.0]"
4,17-119,15 8 15,1.892000e+05,189200.0,1.892000e+05,NaN,[ماکرو کامل 15/8/15],[189200.0]
...,...,...,...,...,...,...,...,...
80,22-125,قارچ تریکودرما,1.980000e+06,1980000.0,1.980000e+06,NaN,[قارچ کش بیولوژیک خاک تریکودرما 50 گرمی],[1980000.0]
81,99-111,کود بذر مال,9.660000e+05,966000.0,9.660000e+05,NaN,"[کود بذرمال روی یاراویتا-پس کرایه, کود بذرمال ...","[966000.0, nan]"
82,99-113,ضد شوری,4.238398e+05,62400.0,9.166667e+05,3.257902e+05,[کود ضد شوری و اصلاح کننده خاک دسالت (100 سی س...,"[560000.0, 916666.666666666, nan, nan, 62400.0..."
83,99-114,ضد تنش,1.193237e+06,550000.0,3.000000e+06,9.124681e+05,"[اسید هیومیک ضد تنش ضد شوری اصلاح بافت خاک, کو...","[916666.666666666, 900000.0, nan, nan, 1166666..."
84,99-115,اصلاح کننده خاک,4.616871e+05,182500.0,1.200000e+06,3.094920e+05,[کود ضد شوری و اصلاح کننده خاک دسالت (100 سی س...,"[560000.0, 279166.666666666, nan, nan, 520000...."

**Correct EXCEPTIONS**

In [182]:
result_df

,code,name,med,min,max,std,listOfNames,listOfPrices
0,17-111,20 20 20,1.621734e+06,120000.0,2.900000e+07,5.437614e+06,[کود کامل پودری 30 گرمی 20-20-20 شرکت زیست فنا...,"[nan, nan, nan, nan, nan, nan, 295000.0, 58333..."
1,17-112,12 12 36,3.014300e+05,216720.0,5.190000e+05,1.458177e+05,[کود کامل 12-12-36 باواریا آلمان ( 50گرم کود خ...,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ..."
2,17-113,10 52 10,2.499615e+06,2500.0,3.200000e+07,7.654907e+06,[فسفر بالا .کود ریشه زایی گل طبیعی گل آپارتمان...,"[nan, nan, 750000.0, 983333.333333333, 300000...."
3,17-116,15 5 30,5.003000e+07,50030000.0,5.003000e+07,NaN,"[کود کامل 15530 25 کیلویی فرمولایف پس کرایه, ک...","[nan, 50030000.0]"
4,17-119,15 8 15,1.892000e+05,189200.0,1.892000e+05,NaN,[ماکرو کامل 15/8/15],[189200.0]
...,...,...,...,...,...,...,...,...
80,22-125,قارچ تریکودرما,1.980000e+06,1980000.0,1.980000e+06,NaN,[قارچ کش بیولوژیک خاک تریکودرما 50 گرمی],[1980000.0]
81,99-111,کود بذر مال,9.660000e+05,966000.0,9.660000e+05,NaN,"[کود بذرمال روی یاراویتا-پس کرایه, کود بذرمال ...","[966000.0, nan]"
82,99-113,ضد شوری,4.238398e+05,62400.0,9.166667e+05,3.257902e+05,[کود ضد شوری و اصلاح کننده خاک دسالت (100 سی س...,"[560000.0, 916666.666666666, nan, nan, 62400.0..."
83,99-114,ضد تنش,1.193237e+06,550000.0,3.000000e+06,9.124681e+05,"[اسید هیومیک ضد تنش ضد شوری اصلاح بافت خاک, کو...","[916666.666666666, 900000.0, nan, nan, 1166666..."
84,99-115,اصلاح کننده خاک,4.616871e+05,182500.0,1.200000e+06,3.094920e+05,[کود ضد شوری و اصلاح کننده خاک دسالت (100 سی س...,"[560000.0, 279166.666666666, nan, nan, 520000...."

In [183]:
# Get the lists from the first row
names = result_df.iloc[4, 6]  # assuming this is already a list
prices = result_df.iloc[4, 7]  # assuming this is already a list

# Make new filtered lists
correctedNamesList = []
correctedPriceList = []
irrevelent_keywords = ["سولفات", "گوگردی", "فسفات"]


for name, price in zip(names, prices):
    if not any(keyword in name for keyword in irrevelent_keywords):
        correctedNamesList.append(name)
        correctedPriceList.append(price)

# Save them back
result_df.at[4, "listOfNames"] = correctedNamesList
result_df.at[4, "listOfPrices"] = correctedPriceList

In [184]:
result_df

,code,name,med,min,max,std,listOfNames,listOfPrices
0,17-111,20 20 20,1.621734e+06,120000.0,2.900000e+07,5.437614e+06,[کود کامل پودری 30 گرمی 20-20-20 شرکت زیست فنا...,"[nan, nan, nan, nan, nan, nan, 295000.0, 58333..."
1,17-112,12 12 36,3.014300e+05,216720.0,5.190000e+05,1.458177e+05,[کود کامل 12-12-36 باواریا آلمان ( 50گرم کود خ...,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ..."
2,17-113,10 52 10,2.499615e+06,2500.0,3.200000e+07,7.654907e+06,[فسفر بالا .کود ریشه زایی گل طبیعی گل آپارتمان...,"[nan, nan, 750000.0, 983333.333333333, 300000...."
3,17-116,15 5 30,5.003000e+07,50030000.0,5.003000e+07,NaN,"[کود کامل 15530 25 کیلویی فرمولایف پس کرایه, ک...","[nan, 50030000.0]"
4,17-119,15 8 15,1.892000e+05,189200.0,1.892000e+05,NaN,[ماکرو کامل 15/8/15],[189200.0]
...,...,...,...,...,...,...,...,...
80,22-125,قارچ تریکودرما,1.980000e+06,1980000.0,1.980000e+06,NaN,[قارچ کش بیولوژیک خاک تریکودرما 50 گرمی],[1980000.0]
81,99-111,کود بذر مال,9.660000e+05,966000.0,9.660000e+05,NaN,"[کود بذرمال روی یاراویتا-پس کرایه, کود بذرمال ...","[966000.0, nan]"
82,99-113,ضد شوری,4.238398e+05,62400.0,9.166667e+05,3.257902e+05,[کود ضد شوری و اصلاح کننده خاک دسالت (100 سی س...,"[560000.0, 916666.666666666, nan, nan, 62400.0..."
83,99-114,ضد تنش,1.193237e+06,550000.0,3.000000e+06,9.124681e+05,"[اسید هیومیک ضد تنش ضد شوری اصلاح بافت خاک, کو...","[916666.666666666, 900000.0, nan, nan, 1166666..."
84,99-115,اصلاح کننده خاک,4.616871e+05,182500.0,1.200000e+06,3.094920e+05,[کود ضد شوری و اصلاح کننده خاک دسالت (100 سی س...,"[560000.0, 279166.666666666, nan, nan, 520000...."

***Remove Irrelevent Price Values***

In [185]:
def remove_outliers_iqr(prices, names, k=1.5):
    """
    Remove outlier prices and corresponding names using the IQR method.
    prices: list of floats
    names: list of strings (same length as prices)
    Returns filtered prices and names.
    """
    if not prices or len(prices) < 4:
        # Not enough data to filter, return original
        return prices, names

    arr = np.array(prices)
    q1 = np.percentile(arr, 25)
    q3 = np.percentile(arr, 75)
    iqr = q3 - q1
    lower_bound = q1 - k * iqr
    upper_bound = q3 + k * iqr

    filtered_prices = []
    filtered_names = []
    for price, name in zip(prices, names):
        if lower_bound <= price <= upper_bound:
            filtered_prices.append(price)
            filtered_names.append(name)

    return filtered_prices, filtered_names

cleaned_data = []

for idx, row in result_df.iterrows():
    prices = row['listOfPrices']
    names = row['listOfNames']

    filtered_prices, filtered_names = remove_outliers_iqr(prices, names)

    if filtered_prices:
        avg = np.mean(filtered_prices)
        minimum = np.min(filtered_prices)
        maximum = np.max(filtered_prices)
        std = np.std(filtered_prices, ddof=1) if len(filtered_prices) > 1 else 0.0
    else:
        avg = minimum = maximum = std = np.nan
        filtered_names = []

    cleaned_data.append({
        "code": row['code'],
        "name": row['name'],
        "med": avg,
        "min": minimum,
        "max": maximum,
        "std": std,
        "listOfNames": filtered_names,
        "listOfPrices": filtered_prices,
    })

cleaned_df = pd.DataFrame(cleaned_data)
cleaned_df

,code,name,med,min,max,std,listOfNames,listOfPrices
0,17-111,20 20 20,NaN,NaN,NaN,NaN,[],[]
1,17-112,12 12 36,NaN,NaN,NaN,NaN,[],[]
2,17-113,10 52 10,NaN,NaN,NaN,NaN,[],[]
3,17-116,15 5 30,NaN,NaN,NaN,NaN,"[کود کامل 15530 25 کیلویی فرمولایف پس کرایه, ک...","[nan, 50030000.0]"
4,17-119,15 8 15,189200.0,189200.0,189200.0,0.0,[ماکرو کامل 15/8/15],[189200.0]
...,...,...,...,...,...,...,...,...
80,22-125,قارچ تریکودرما,1980000.0,1980000.0,1980000.0,0.0,[قارچ کش بیولوژیک خاک تریکودرما 50 گرمی],[1980000.0]
81,99-111,کود بذر مال,NaN,NaN,NaN,NaN,"[کود بذرمال روی یاراویتا-پس کرایه, کود بذرمال ...","[966000.0, nan]"
82,99-113,ضد شوری,NaN,NaN,NaN,NaN,[],[]
83,99-114,ضد تنش,NaN,NaN,NaN,NaN,[],[]
84,99-115,اصلاح کننده خاک,NaN,NaN,NaN,NaN,[],[]

In [186]:
def mad_based_filter(prices, names, thresh=3.5):
    """
    Remove outliers using Median Absolute Deviation (MAD).
    prices: list of floats
    names: list of strings (same length)
    thresh: threshold for modified z-score to consider outlier (usually 3-3.5)
    Returns filtered prices and names.
    """
    if not prices or len(prices) < 3:
        # Not enough data to filter robustly, return as is
        return prices, names

    arr = np.array(prices)
    median = np.median(arr)
    mad = np.median(np.abs(arr - median))

    if mad == 0:
        # MAD is zero means no variation, return original
        return prices, names

    modified_z_scores = 0.6745 * (arr - median) / mad

    filtered_prices = []
    filtered_names = []
    for price, name, z in zip(prices, names, modified_z_scores):
        if np.abs(z) <= thresh:
            filtered_prices.append(price)
            filtered_names.append(name)

    return filtered_prices, filtered_names

cleaned_data = []

for idx, row in result_df.iterrows():
    prices = row['listOfPrices']
    names = row['listOfNames']

    filtered_prices, filtered_names = mad_based_filter(prices, names)

    if filtered_prices:
        avg = np.mean(filtered_prices)
        minimum = np.min(filtered_prices)
        maximum = np.max(filtered_prices)
        std = np.std(filtered_prices, ddof=1) if len(filtered_prices) > 1 else 0.0
    else:
        avg = minimum = maximum = std = np.nan
        filtered_names = []

    cleaned_data.append({
        "code": row['code'],
        "name": row['name'],
        "med": avg,
        "min": minimum,
        "max": maximum,
        "std": std,
        "listOfNames": filtered_names,
        "listOfPrices": filtered_prices,
    })

cleaned_df = pd.DataFrame(cleaned_data)
cleaned_df

,code,name,med,min,max,std,listOfNames,listOfPrices
0,17-111,20 20 20,NaN,NaN,NaN,NaN,[],[]
1,17-112,12 12 36,NaN,NaN,NaN,NaN,[],[]
2,17-113,10 52 10,NaN,NaN,NaN,NaN,[],[]
3,17-116,15 5 30,NaN,NaN,NaN,NaN,"[کود کامل 15530 25 کیلویی فرمولایف پس کرایه, ک...","[nan, 50030000.0]"
4,17-119,15 8 15,189200.0,189200.0,189200.0,0.0,[ماکرو کامل 15/8/15],[189200.0]
...,...,...,...,...,...,...,...,...
80,22-125,قارچ تریکودرما,1980000.0,1980000.0,1980000.0,0.0,[قارچ کش بیولوژیک خاک تریکودرما 50 گرمی],[1980000.0]
81,99-111,کود بذر مال,NaN,NaN,NaN,NaN,"[کود بذرمال روی یاراویتا-پس کرایه, کود بذرمال ...","[966000.0, nan]"
82,99-113,ضد شوری,NaN,NaN,NaN,NaN,[],[]
83,99-114,ضد تنش,NaN,NaN,NaN,NaN,[],[]
84,99-115,اصلاح کننده خاک,NaN,NaN,NaN,NaN,[],[]

**Remove any Price outlier via IQR**

write the function for removing outliers by median of the prices

In [187]:
import statistics
import re
import unicodedata

def normalize_number_string(s: str) -> str:
    """Convert Persian/Arabic digits to English and remove thousands separators."""
    if not isinstance(s, str):
        return s
    # Normalize Unicode
    s = unicodedata.normalize("NFKC", s)
    # Convert Persian digits
    persian_digits = "۰۱۲۳۴۵۶۷۸۹"
    arabic_digits = "٠١٢٣٤٥٦٧٨٩"
    english_digits = "0123456789"
    s = s.translate(str.maketrans(persian_digits, english_digits))
    s = s.translate(str.maketrans(arabic_digits, english_digits))
    # Remove Persian/Arabic/English commas
    s = s.replace("٬", "").replace("،", "").replace(",", "")
    return s

def remove_outliers_iqr(names, prices):
    """
    Removes outliers using the IQR method,
    ensures at least 2 items remain.
    Automatically handles Persian/Arabic digits and sorts by price.
    """
    if not prices:
        return names, prices
    
    # How much robust if smaller become more aggresive
    RATE = 1.5

    # Extract numeric values and sort them by price
    clean_data = []
    for name, price in zip(names, prices):
        if isinstance(price, (int, float)):
            clean_data.append((float(price), name))
        elif isinstance(price, str):
            normalized = normalize_number_string(price)
            match = re.search(r"[-+]?\d*\.?\d+", normalized)
            if match:
                clean_data.append((float(match.group()), name))

    # If fewer than 2 numeric prices, skip filtering
    if len(clean_data) < 2:
        return names, prices

    # Sort by price
    clean_data.sort(key=lambda x: x[0])
    clean_prices = [p for p, _ in clean_data]
    clean_names = [n for _, n in clean_data]

    # Calculate Q1, Q3, and IQR
    q1 = statistics.quantiles(clean_prices, n=4)[0]
    q3 = statistics.quantiles(clean_prices, n=4)[2]
    iqr = q3 - q1
    lower_limit = q1 - RATE * iqr
    upper_limit = q3 + RATE * iqr

    # Filter values within bounds
    filtered_data = [(p, n) for p, n in clean_data if lower_limit <= p <= upper_limit]

    # Ensure at least 2 prices remain
    if len(filtered_data) < 2:
        return names, prices

    # Return sorted filtered results
    filtered_prices = [p for p, _ in filtered_data]
    filtered_names = [n for _, n in filtered_data]
    return filtered_names, filtered_prices

In [188]:
import math
import statistics

listOfRemovedOutliersByMedian = []

for index, row in result_df.iterrows():
    filtered_outliers_names, filtered_outliers_prices = remove_outliers_iqr(row["listOfNames"], row["listOfPrices"])
    
    # Remove NaN or non-numeric values from prices list
    filtered_outliers_prices = [p for p in filtered_outliers_prices if p is not None and not (isinstance(p, float) and math.isnan(p))]

    if filtered_outliers_prices:
        median = statistics.median(filtered_outliers_prices)
        minimum = min(filtered_outliers_prices)
        maximum = max(filtered_outliers_prices)
        if len(filtered_outliers_prices) >= 2:
            std = statistics.stdev(filtered_outliers_prices)
        else:
            std = None
    else:
        median, minimum, maximum, std = None, None, None, None
    
    listOfRemovedOutliersByMedian.append({
        "code": row['code'],
        "name": row['name'],
        "med": median,
        "min": minimum,
        "max": maximum,
        "std": std,
        "listOfPrices": filtered_outliers_prices,
        "listOfNames": filtered_outliers_names,
    })

dfOfRemovedOutliersByMedian = pd.DataFrame(listOfRemovedOutliersByMedian)
result_df = dfOfRemovedOutliersByMedian
dfOfRemovedOutliersByMedian

,code,name,med,min,max,std,listOfPrices,listOfNames
0,17-111,20 20 20,3.568182e+05,120000.0,1.225000e+06,279419.052644,"[120000.0, 149000.0, 180000.0, 189000.0, 20468...","[کود NPK 20-20-20 (10کیلو), کود NPK 20 20 20 د..."
1,17-112,12 12 36,2.350000e+05,216720.0,5.190000e+05,145817.670168,"[519000.0, 250000.0, 216720.0, 220000.0]",[کود کامل 12-12-36 باواریا آلمان ( 50گرم کود خ...
2,17-113,10 52 10,3.150000e+05,2500.0,9.833333e+05,298975.085705,"[2500.0, 120000.0, 154800.0, 249480.0, 275000....","[کود NPK 10-52-10 وزن 10 کیلوگرم, 10.52.10 NPK..."
3,17-116,15 5 30,5.003000e+07,50030000.0,5.003000e+07,NaN,[50030000.0],"[کود کامل 15530 25 کیلویی فرمولایف پس کرایه, ک..."
4,17-119,15 8 15,1.892000e+05,189200.0,1.892000e+05,NaN,[189200.0],[ماکرو کامل 15/8/15]
...,...,...,...,...,...,...,...,...
80,22-125,قارچ تریکودرما,1.980000e+06,1980000.0,1.980000e+06,NaN,[1980000.0],[قارچ کش بیولوژیک خاک تریکودرما 50 گرمی]
81,99-111,کود بذر مال,9.660000e+05,966000.0,9.660000e+05,NaN,[966000.0],"[کود بذرمال روی یاراویتا-پس کرایه, کود بذرمال ..."
82,99-113,ضد شوری,3.853360e+05,62400.0,9.166667e+05,325790.170509,"[560000.0, 916666.666666666, 62400.0, 210672.0...",[کود ضد شوری و اصلاح کننده خاک دسالت (100 سی س...
83,99-114,ضد تنش,9.083333e+05,550000.0,3.000000e+06,912468.149386,"[916666.666666666, 900000.0, 1166666.66666666,...","[اسید هیومیک ضد تنش ضد شوری اصلاح بافت خاک, کو..."
84,99-115,اصلاح کننده خاک,4.025000e+05,182500.0,1.200000e+06,309491.970908,"[560000.0, 279166.666666666, 520000.0, 199200....",[کود ضد شوری و اصلاح کننده خاک دسالت (100 سی س...

***Checking Fertilizers Which Aren't In The List***

In [189]:
resultList = result_df.iloc[:,1].str.replace("-", " ", regex=False).tolist()
completeList = raw_source_df.iloc[:,4].str.replace("-", " ", regex=False).tolist()
absentFertilizers = [x for x in completeList if x not in resultList]
absentdf = pd.DataFrame({
    "absents": absentFertilizers
})
import datetime
import os

os.makedirs("absents", exist_ok=True)

now_str = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
filename = f"absents/fertilizer_absent_{now_str}.xlsx"

absentdf.to_excel(filename, sheet_name="Fertilizer_Absent_Estimations", index=False)

save the result

In [190]:
import datetime
import os

os.makedirs("estimation_output", exist_ok=True)

now_str = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
filename = f"estimation_output/fertilizer_price_estimations_{now_str}.xlsx"

result_df.to_excel(filename, sheet_name="Fertilizer_Price_Estimations", index=False)