In [224]:
from persianNumberNormalizer import PersianNumberNormalizer 
import re
import datetime

In [225]:
import pandas as pd

df = pd.read_excel("output/price_of_fertilizers - Copy (3).xlsx"
                   ,sheet_name=None)
df

{'agriplus.ir':                                                    url  \
 0    https://agriplus.ir/Product/BKP-35038/%da%a9%d...
 1    https://agriplus.ir/Product/BKP-27426/%da%a9%d...
 2    https://agriplus.ir/Product/BKP-22917/%da%a9%d...
 3    https://agriplus.ir/Product/BKP-22916/%da%a9%d...
 4    https://agriplus.ir/Product/BKP-21436/%da%a9%d...
 ..                                                 ...
 229  https://agriplus.ir/Product/BKP-36074/cotooly-...
 230  https://agriplus.ir/Product/BKP-37832/rooty-sy...
 231  https://agriplus.ir/Product/BKP-36042/flory-ho...
 232  https://agriplus.ir/Product/BKP-22850/%d9%82%d...
 233  https://agriplus.ir/Product/BKP-14233/%d9%be%d...

                                                   name          category  \
 0                               کود NPK ۳۰ ۱۰ ۱۰ زیگلر           کود NPK
 1                      کود سه بیست لبین (NPK ۲۰ ۲۰ ۲۰)           کود NPK
 2         کود NPK تحریک گلدهی ۳۶ ۱۲ ۱۲ بسته بندی خانگی         کود خانگی
 3             کود محرک رشد ۲۰ ۲۰ ۲۰ با بسته بندی خانگی         کود خانگی
 4                            کود NPK ۱۵ ۵ ۳۰ کوالی مکس           کود NPK
 ..                                                 ...               ...
 229  هورمون پاکوتاهی - گلدهی کتولی (®Cotooly) اگری ...  هورمون رشد گیاهی
 230      هورمون ریشه زایی غلیظ (Rooty Syrup) اگری پلاس  هورمون رشد گیاهی
 231              هورمون گلدهی فلوری (®Flory) اگری پلاس  هورمون رشد گیاهی
 232                            قرص جیبرلیک اسید اگریمن  هورمون رشد گیاهی
 233                         پودر جیبرلین BERELEX ۴۰ SG  هورمون رشد گیاهی

             price  price_per_kg  amount_kg  last_price_update is_available  \
 0             NaN           NaN        NaN                NaN        False
 1             NaN           NaN        NaN                NaN        False
 2             NaN           NaN        NaN                NaN        False
 3    ۱۹۸,۰۰۰ ریال           NaN        NaN                NaN          NaN
 4             NaN           NaN        NaN                NaN        False
 ..            ...           ...        ...                ...          ...
 229       3100000       31000.0      100.0                NaN         True
 230           NaN           NaN        NaN                NaN        False
 231      12400000       49600.0      250.0                NaN         True
 232           NaN           NaN        NaN                NaN        False
 233           NaN           NaN        NaN                NaN        False

               created_at         last_updated
 0    2025-07-22 15:50:46  2025-07-22 15:50:46
 1    2025-07-22 15:50:50  2025-07-22 15:50:50
 2    2025-07-22 15:50:52  2025-07-22 16:02:02
 3    2025-07-22 15:50:55  2025-07-22 16:02:19
 4    2025-07-22 15:50:58  2025-07-22 15:50:58
 ..                   ...                  ...
 229  2025-07-22 16:34:09  2025-07-22 16:34:09
 230  2025-07-22 16:34:12  2025-07-22 16:34:12
 231  2025-07-22 16:34:15  2025-07-22 16:34:15
 232  2025-07-22 16:34:18  2025-07-22 16:34:18
 233  2025-07-22 16:34:21  2025-07-22 16:34:21

 [234 rows x 10 columns],
 'torob.com':                                                     url  \
 0     https://torob.com/p/2b84fb38-5f28-47ed-904d-1a...
 1     https://torob.com/p/ae8d4083-b06f-4d62-b5f1-38...
 2     https://torob.com/p/86e88419-cd7b-4fb1-9fb5-72...
 3     https://torob.com/p/570734d8-40be-4f91-87d7-b5...
 4     https://torob.com/p/bade8776-56ef-4605-82a5-f5...
 ...                                                 ...
 1556  https://torob.com/p/8293600b-2a42-4364-9983-cd...
 1557  https://torob.com/p/f3151753-ea93-454e-a6e2-ac...
 1558  https://torob.com/p/1d9f604d-5a93-49af-a6db-a7...
 1559  https://torob.com/p/ea2cb9c3-71b7-44ab-9a28-78...
 1560  https://torob.com/p/eeb69058-7863-423e-8bbc-4e...

                                                    name  category   price  \
 0                  کود جلبک دریایی مایع شوک اصل 5 لیتری       NaN  888000
 1                              قرص کود ارگانیک 120 عددی       NaN   66000
 2                       کود شیمیایی اوره گرانول 46 درصد       NaN   70000
 3                            پودر هیومیک اسید پلنت چویس       NaN  630000
 4     کود سه بیست 20 20 برند هایپر ایکس گرین - کود ک...       NaN  240000
 ...                                                 ...       ...     ...
 1556                      صابون حشره کش جنوبگان 5 لیتری       NaN  365000
 1557                       کود آلی مایع زرگرین ۲۰ لیتری       NaN  820000
 1558            کود نیترات کلسیم جنوبگان وزن ۲۵ کیلوگرم       NaN  110000
 1559        کود گوگرد مایع شوک ۲۰ لیتری ۸۰ درصد ارگانیک       NaN  260000
 1560           کود پلیت مرغی زرین مهر کیمیا 25 کیلوگرمی       NaN  227500

       price_per_kg  amount_kg  last_price_update  is_available  \
 0         177600.0        5.0                NaN          True
 1              NaN        NaN                NaN          True
 2              NaN        NaN                NaN          True
 3              NaN        NaN                NaN          True
 4              NaN        NaN                NaN          True
 ...            ...        ...                ...           ...
 1556       73000.0        5.0                NaN          True
 1557       41000.0       20.0                NaN          True
 1558        4400.0       25.0                NaN          True
 1559       13000.0       20.0                NaN          True
 1560        9100.0       25.0                NaN          True

                created_at         last_updated
 0     2025-07-22 16:45:39  2025-07-27 16:48:28
 1     2025-07-22 16:45:40  2025-07-29 15:01:00
 2     2025-07-22 16:45:40  2025-07-22 16:45:40
 3     2025-07-22 16:45:40  2025-07-22 16:45:40
 4     2025-07-22 16:45:40  2025-07-29 15:01:04
 ...                   ...                  ...
 1556  2025-07-29 15:00:59  2025-07-29 15:00:59
 1557  2025-07-29 15:02:06  2025-07-29 15:02:06
 1558  2025-07-29 15:02:12  2025-07-29 15:02:12
 1559  2025-07-29 15:02:19  2025-07-29 15:02:19
 1560  2025-07-29 15:03:02  2025-07-29 15:03:02

 [1561 rows x 10 columns],
 'digikood.com':                                                   url  \
 0   https://www.digikood.com/product/%da%a9%d9%84%...
 1   https://www.digikood.com/product/%d9%81%d8%b3%...
 2         https://www.digikood.com/product/__trashed/
 3   https://www.digikood.com/product/%da%a9%d9%88%...
 4   https://www.digikood.com/product/%d8%a7%d9%88%...
 ..                                                ...
 83  https://www.digikood.com/product/%d8%b6%d8%af-...
 84  https://www.digikood.com/product/%da%a9%d9%88%...
 85  https://www.digikood.com/product/%d8%a8%d8%a7%...
 86  https://www.digikood.com/product/%da%a9%d9%85%...
 87  https://www.digikood.com/product/%da%af%d9%88%...

                            name       category      price  price_per_kg  \
 0   کلات آهن لایفر ۶٪ اسپانیایی  کودهای گوگردی  1200000.0      200000.0
 1                  فسفات گوگردی  کودهای گوگردی   850000.0       17000.0
 2                ماکرو 20 20 20   کود های مایع  3500000.0     3500000.0
 3                کود کامل خانگی  کودهای گوگردی        NaN           NaN
 4                   اوره گوگردی  کودهای گوگردی   850000.0       34000.0
 ..                          ...            ...        ...           ...
 83                  ضد یخ گیاهی  کودهای گوگردی        NaN           NaN
 84          کود بیولوژیک بیوراس  کود های زیستی  2125000.0       85000.0
 85   بایوکامپوزیت گوگردی (تیاس)  کودهای گوگردی  3800000.0     1900000.0
 86            کمپوست آلی سلولزی       ریز مغزی   180000.0       18000.0
 87                   گوگرد مایع  کودهای گوگردی  1750000.0      350000.0

     amount_kg  last_price_update  is_available           created_at  \
 0           6                NaN          True  2025-07-22 17:05:51
 1          50                NaN          True  2025-07-22 17:05:56
 2           1                NaN          True  2025-07-22 17:06:01
 3          10                NaN          True  2025-07-22 17:06:06
 4          25                NaN          True  2025-07-22 17:06:11
 ..        ...                ...           ...                  ...
 83          1                NaN          True  2025-07-22 17:19:39
 84         25                NaN          True  2025-07-22 17:20:21
 85          2                NaN          True  2025-07-22 17:20:26
 86         10                NaN          True  2025-07-22 17:20:31
 87          5                NaN          True  2025-07-22 17:24:31

            last_updated
 0   2025-07-27 17:46:32
 1   2025-07-27 17:45:34
 2   2025-07-27 17:43:16
 3   2025-07-27 17:45:38
 4   2025-07-27 17:45:43
 ..                  ...
 83  2025-07-27 17:46:51
 84  2025-07-27 17:44:48
 85  2025-07-27 17:45:47
 86  2025-07-27 17:40:18
 87  2025-07-27 17:45:52

 [88 rows x 10 columns],
 'koodforosh.com':                                      url  \
 0       https://koodforosh.com/showads/6
 1    https://koodforosh.com/showads/2194
 2    https://koodforosh.com/showads/2253
 3    https://koodforosh.com/showads/2945
 4    https://koodforosh.com/showads/2930
 ..                                   ...
 180  https://koodforosh.com/showads/3444
 181  https://koodforosh.com/showads/3445
 182  https://koodforosh.com/showads/3446
 183  https://koodforosh.com/showads/3447
 184  https://koodforosh.com/showads/3448

                                                   name    category    price  \
 0    روش استفاده از کود سولفات امونیوم گرانوله در ش...  کود سولفات  ۱۱۵,۰۰۰
 1                                  فروش کود سولفات اهن  کود سولفات      NaN
 2                                  فروش سولفات امونیوم  کود سولفات      NaN
 3                                  فروش سولفات آمونیوم  کود سولفات      NaN
 4                                       کود NK 5‐5 آفر    کود پتاس      NaN
 ..                                                 ...         ...      ...
 180           آیا کود هوموس برای همه گیاهان مناسب است؟   کود هوموس    ۲,۵۰۰
 181                   چگونه از کود هوموس استفاده کنیم؟   کود هوموس    ۲,۵۰۰
 182           کود هوموس چگونه به بهبود خاک کمک می‌کند؟   کود هوموس    ۲,۵۰۰
 183       آیا کود هوموس باعث افزایش رشد گیاهان می‌شود؟   کود هوموس    ۲,۵۰۰
 184           کود هوموس چگونه به محیط زیست کمک می‌کند؟   کود هوموس    ۲,۵۰۰

      price_per_kg  amount_kg  last_price_update  is_available  \
 0             NaN        NaN                NaN           NaN
 1             NaN        NaN                NaN           NaN
 2             NaN        NaN                NaN           NaN
 3             NaN        NaN                NaN           NaN
 4             NaN        NaN                NaN           NaN
 ..            ...        ...                ...           ...
 180           NaN        NaN                NaN           NaN
 181           NaN        NaN                NaN           NaN
 182           NaN        NaN                NaN           NaN
 183           NaN        NaN                NaN           NaN
 184           NaN        NaN                NaN           NaN

               created_at         last_updated
 0    2025-07-22 17:28:23  2025-07-22 17:28:23
 1    2025-07-22 17:28:25  2025-07-22 17:28:25
 2    2025-07-22 17:28:34  2025-07-22 17:28:34
 3    2025-07-22 17:28:38  2025-07-22 17:28:38
 4    2025-07-22 17:29:20  2025-07-22 17:29:20
 ..                   ...                  ...
 180  2025-07-22 17:39:06  2025-07-22 17:39:06
 181  2025-07-22 17:39:07  2025-07-22 17:39:07
 182  2025-07-22 17:39:08  2025-07-22 17:39:08
 183  2025-07-22 17:39:10  2025-07-22 17:39:10
 184  2025-07-22 17:39:11  2025-07-22 17:39:11

 [185 rows x 10 columns],
 'digikoud.com':                                                   url  \
 0   https://digikoud.com/کود-های-پتاسه/9-نیترات-پت...
 1   https://digikoud.com/کود-های-پتاسه/8-سولفات-پت...
 2   https://digikoud.com/کود-های-مرکب/37-مونو-پتاس...
 3   https://digikoud.com/کود-های-مایع/72-کود-زیستی...
 4   https://digikoud.com/کود-کامل-ماکرو-/182-ماکرو...
 ..                                                ...
 77  https://digikoud.com/کود-مخصوص-گل-و-سبزیجات/16...
 78  https://digikoud.com/کود-مخصوص-گل-و-سبزیجات/16...
 79  https://digikoud.com/کود-مخصوص-گل-و-سبزیجات/16...
 80  https://digikoud.com/کود-مخصوص-گل-و-سبزیجات/17...
 81  https://digikoud.com/کود-مخصوص-گل-و-سبزیجات/17...

                          name                    category       price  \
 0               نیترات پتاسیم            کود های مرکب\n37  27500004.0
 1   سولفات پتاسیم منیزیم 10/4        کود های ریز مغزی\n17   3399000.0
 2           مونو پتاسیم فسفات            کود های مرکب\n37   2500000.0
 3        کود زیستی پتابارور-2            کود های مایع\n12    980000.0
 4          ماکرو کامل20/20/20      کود کامل ( ماکرو )\n23   5550000.0
 ..                        ...                         ...         ...
 77       کود گیاهان آپارتمانی  کود مخصوص گل و سبزیجات\n15         NaN
 78        کود گیاهان باغچه ای  کود مخصوص گل و سبزیجات\n15         NaN
 79                  کود گلدهی  کود مخصوص گل و سبزیجات\n15         NaN
 80                     کود رز  کود مخصوص گل و سبزیجات\n15         NaN
 81       کود رشد مخصوص گیاهان  کود مخصوص گل و سبزیجات\n15         NaN

     price_per_kg  amount_kg  last_price_update  is_available  \
 0     1100000.16        NaN                NaN           NaN
 1      135960.00        NaN                NaN           NaN
 2      100000.00        NaN                NaN           NaN
 3      196000.00        NaN                NaN           NaN
 4      555000.00        NaN                NaN           NaN
 ..           ...        ...                ...           ...
 77           NaN        NaN                NaN           NaN
 78           NaN        NaN                NaN           NaN
 79           NaN        NaN                NaN           NaN
 80           NaN        NaN                NaN           NaN
 81           NaN        NaN                NaN           NaN

              created_at         last_updated
 0   2025-07-22 17:39:20  2025-07-22 17:44:18
 1   2025-07-22 17:39:23  2025-07-22 17:46:35
 2   2025-07-22 17:39:27  2025-07-22 17:44:12
 3   2025-07-22 17:39:30  2025-07-22 17:41:39
 4   2025-07-22 17:39:33  2025-07-22 17:47:48
 ..                  ...                  ...
 77  2025-07-22 17:48:49  2025-07-22 17:48:49
 78  2025-07-22 17:48:52  2025-07-22 17:48:52
 79  2025-07-22 17:48:55  2025-07-22 17:48:55
 80  2025-07-22 17:49:01  2025-07-22 17:49:01
 81  2025-07-22 17:49:05  2025-07-22 17:49:05

 [82 rows x 10 columns],
 'sepahankesht.com':                                                   url  \
 0   https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 1   https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 2   https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 3   https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 4   https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 5   https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 6   https://sepahankesht.com/shop/%da%86%d8%a7%d9%...
 7   https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 8   https://sepahankesht.com/shop/%d9%87%db%8c%d9%...
 9   https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 10  https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 11  https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 12  https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 13  https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 14  https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 15  https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 16  https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 17  https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 18  https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 19  https://sepahankesht.com/shop/%da%86%d8%a7%d9%...
 20  https://sepahankesht.com/shop/%da%86%d8%a7%d9%...
 21  https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 22  https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 23  https://sepahankesht.com/shop/%d9%be%d8%aa%d8%...
 24  https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 25  https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 26  https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 27  https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 28  https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 29  https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 30  https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 31  https://sepahankesht.com/shop/%da%a9%d9%88%d8%...
 32  https://sepahankesht.com/shop/%da%a9%d9%88%d8%...

                                                  name  \
 0     کود هومی پاور پودری فیوچرکو بایوساینس ۱ کیلوگرم
 1               کود هیومیک اسید مایع هیومولایف ۵ لیتر
 2         کود هیومیک اسید گرانول هیومولایف ۲۵ کیلوگرم
 3                کود اکوسالت (کاهنده شوری خاک) ۵ لیتر
 4                کود نیچرمیک فیوچرکو بایوساینس ۵ لیتر
 5         کود هومی پاور پلاس فیوچرکو بایوساینس ۵ لیتر
 6   چالکود فرموکمپلکس همراه با گوگرد و عناصر ریزمغ...
 7                      کود یارامیلا کمپلکس ۲۵ کیلوگرم
 8                          هیومیک اسید فرتی وان AH 75
 9                کود مایع هیومیک‌اسید نوتری تک ۵ لیتر
 10     کود هیومیک دار NPK 20-5-10 هیومولایف 5 کیلوگرم
 11     کود هیومیک دار NPK 12-5-20 هیومولایف 5 کیلوگرم
 12               کود اصلاح کننده PH لوورسون (7 LOWER)
 13          کود هیومیک و فولویک اسید هیومیستار ۵ لیتر
 14         کود هیومیک اسید و فولویک اسید پابرا ۵ لیتر
 15                 کود فولویک اسید نوتریویم ۱ کیلوگرم
 16           کود ضدشوری گیاهان آپارتمانی ۶۰ میلی لیتر
 17          کود ضد شوری فورنوترینت (Anti Salt) 5 لیتر
 18               کود ضدشوری فرمولایف مدل دسالت ۵ لیتر
 19                       چال کود پارس بلدر ۲۵ کیلوگرم
 20                    چالکود پارسی لئون اس ۲۵ کیلوگرم
 21      کود اسید هیومیک گیاهان آپارتمانی ۶۰ میلی لیتر
 22                            کود ریزمغذی هوگر ۱ لیتر
 23                              کود جلبک دریایی سیفول
 24    کود فول‌فورس اس نوتریویم (FULLFORCE-S) 1کیلوگرم
 25  کود مرغی مایع نیو داتیس آل (NEW DATIS ALL) حجم...
 26          کود پودری اسیدهیومیک ASORIK وزن 1 کیلوگرم
 27     کود داتیس فورنوترینت ارگانیک (کود مرغی) ۵ لیتر
 28                 کود هیومیک اسید پابرا ۲.۵ کیلوگرمی
 29          کود هیومیک اسید پودری هیومولایف ۱ کیلوگرم
 30      کود هیومیک اسید مایع فورنوترینت OM حجم 5 لیتر
 31   کود هیومیک اسید پودری هوموکسال ۹۵% وزن ۱ کیلوگرم
 32                       کود مرغی مایع چیکوتی ۲۰ لیتر

                           category    price  price_per_kg  amount_kg  \
 0                   soil-modifying  1145760     1145760.0        1.0
 1                      هیومیک-اسید  1155000      231000.0        5.0
 2                      هیومیک-اسید  2204400       88176.0       25.0
 3         anti-salinity-fertilizer  2481600      496320.0        5.0
 4                   soil-modifying  2587200      517440.0        5.0
 5                      هیومیک-اسید  2877600      575520.0        5.0
 6                  fertilizer-hole  2970000      118800.0       25.0
 7                  fertilizer-hole  6025800      241032.0       25.0
 8                      هیومیک-اسید   194000           NaN        NaN
 9                      هیومیک-اسید   377520       75504.0        5.0
 10                     هیومیک-اسید   675840      135168.0        5.0
 11                     هیومیک-اسید   675840      135168.0        5.0
 12                  soil-modifying   774840           NaN        NaN
 13                     هیومیک-اسید  1141800      228360.0        5.0
 14                     هیومیک-اسید   411400       82280.0        5.0
 15  powdered-folic-acid-fertilizer   776160      776160.0        1.0
 16        anti-salinity-fertilizer    30000           NaN        NaN
 17        anti-salinity-fertilizer   312000       62400.0        5.0
 18        anti-salinity-fertilizer  1053360      210672.0        5.0
 19                 fertilizer-hole   467500       18700.0       25.0
 20                     هیومیک-اسید   561000       22440.0       25.0
 21                     هیومیک-اسید    30000           NaN        NaN
 22                     هیومیک-اسید   177600      177600.0        1.0
 23                     هیومیک-اسید   187000      187000.0        1.0

In [226]:
# Concatenate all the data in the 
dataFrame = pd.DataFrame()
for data in df.values():
    dataFrame = pd.concat([data,dataFrame],ignore_index=True)

dataFrame

,url,name,category,price,price_per_kg,amount_kg,last_price_update,is_available,created_at,last_updated,_pk
0,https://basalam.com/greenrose/product/11745865,خاک و کود آماده کاشت تای سیز 4 لیتری,NaN,45٬000,28125.0,1.6,NaN,True,2025-08-04 10:38:26,2025-08-05 10:37:50,https://basalam.com/greenrose/product/11745865...
1,https://basalam.com/arzankadeh7berke/product/1...,خاک و کود بستر مخصوص گیاهان آبزی و میگوها اوشن...,NaN,1٬223٬800,407933.333333,3.0,NaN,True,2025-08-04 10:38:28,2025-08-05 10:37:51,https://basalam.com/arzankadeh7berke/product/1...
2,https://basalam.com/goldan.felezi/product/1507...,خاک و کود آماده کاشت 4 لیتری,NaN,40٬200,10050.0,4.0,NaN,True,2025-08-04 10:38:31,2025-08-05 10:37:53,https://basalam.com/goldan.felezi/product/1507...
3,https://basalam.com/almase_sorkh/product/11141428,خاک و کود آماده کاشت گیلدا بسته 4 لیتری,NaN,110٬000,47826.086957,2.3,NaN,True,2025-08-04 10:38:34,2025-08-05 10:37:55,https://basalam.com/almase_sorkh/product/11141...
4,https://basalam.com/igool/product/16423331,خاک کود آفت کش و گلدان پلیمری پک تعویض گلدان ک...,NaN,499٬000,NaN,NaN,NaN,True,2025-08-04 10:38:37,2025-08-05 10:37:56,https://basalam.com/igool/product/16423331::خا...
...,...,...,...,...,...,...,...,...,...,...,...
4883,https://agriplus.ir/Product/BKP-36074/cotooly-...,هورمون پاکوتاهی - گلدهی کتولی (®Cotooly) اگری ...,هورمون رشد گیاهی,3100000,31000.0,100.0,NaN,True,2025-07-22 16:34:09,2025-07-22 16:34:09,NaN
4884,https://agriplus.ir/Product/BKP-37832/rooty-sy...,هورمون ریشه زایی غلیظ (Rooty Syrup) اگری پلاس,هورمون رشد گیاهی,NaN,NaN,NaN,NaN,False,2025-07-22 16:34:12,2025-07-22 16:34:12,NaN
4885,https://agriplus.ir/Product/BKP-36042/flory-ho...,هورمون گلدهی فلوری (®Flory) اگری پلاس,هورمون رشد گیاهی,12400000,49600.0,250.0,NaN,True,2025-07-22 16:34:15,2025-07-22 16:34:15,NaN
4886,https://agriplus.ir/Product/BKP-22850/%d9%82%d...,قرص جیبرلیک اسید اگریمن,هورمون رشد گیاهی,NaN,NaN,NaN,NaN,False,2025-07-22 16:34:18,2025-07-22 16:34:18,NaN
4887,https://agriplus.ir/Product/BKP-14233/%d9%be%d...,پودر جیبرلین BERELEX ۴۰ SG,هورمون رشد گیاهی,NaN,NaN,NaN,NaN,False,2025-07-22 16:34:21,2025-07-22 16:34:21,NaN

In [227]:
df = dataFrame

df.drop("url",axis=1,inplace=True)
df.dropna(subset=['price_per_kg'],inplace=True)
df = df.drop(labels="created_at",axis=1)
df = df.drop(labels="last_updated",axis=1)
df

,name,category,price,price_per_kg,amount_kg,last_price_update,is_available,_pk
0,خاک و کود آماده کاشت تای سیز 4 لیتری,NaN,45٬000,28125.0,1.6,NaN,True,https://basalam.com/greenrose/product/11745865...
1,خاک و کود بستر مخصوص گیاهان آبزی و میگوها اوشن...,NaN,1٬223٬800,407933.333333,3.0,NaN,True,https://basalam.com/arzankadeh7berke/product/1...
2,خاک و کود آماده کاشت 4 لیتری,NaN,40٬200,10050.0,4.0,NaN,True,https://basalam.com/goldan.felezi/product/1507...
3,خاک و کود آماده کاشت گیلدا بسته 4 لیتری,NaN,110٬000,47826.086957,2.3,NaN,True,https://basalam.com/almase_sorkh/product/11141...
5,خاک و کود آماده کاشت 20 لیتری,NaN,181٬700,9085.0,20.0,NaN,True,https://basalam.com/goldan.felezi/product/1507...
...,...,...,...,...,...,...,...,...
4865,کود مایع بمباردیر شوگر کیمیتک,کود کامل,13068000,13068000.0,1.0,NaN,True,NaN
4870,کود مایع محرک رشد بمباردیر,کود کامل,10920000,10920000.0,1.0,NaN,True,NaN
4881,هورمون شاخه‌ زایی شوتی (®Shooty) اگری پلاس,هورمون رشد گیاهی,5170000,51700.0,100.0,NaN,True,NaN
4883,هورمون پاکوتاهی - گلدهی کتولی (®Cotooly) اگری ...,هورمون رشد گیاهی,3100000,31000.0,100.0,NaN,True,NaN
4885,هورمون گلدهی فلوری (®Flory) اگری پلاس,هورمون رشد گیاهی,12400000,49600.0,250.0,NaN,True,NaN

In [228]:
#df = df.drop(labels="last_price_update",axis=1)
df

,name,category,price,price_per_kg,amount_kg,last_price_update,is_available,_pk
0,خاک و کود آماده کاشت تای سیز 4 لیتری,NaN,45٬000,28125.0,1.6,NaN,True,https://basalam.com/greenrose/product/11745865...
1,خاک و کود بستر مخصوص گیاهان آبزی و میگوها اوشن...,NaN,1٬223٬800,407933.333333,3.0,NaN,True,https://basalam.com/arzankadeh7berke/product/1...
2,خاک و کود آماده کاشت 4 لیتری,NaN,40٬200,10050.0,4.0,NaN,True,https://basalam.com/goldan.felezi/product/1507...
3,خاک و کود آماده کاشت گیلدا بسته 4 لیتری,NaN,110٬000,47826.086957,2.3,NaN,True,https://basalam.com/almase_sorkh/product/11141...
5,خاک و کود آماده کاشت 20 لیتری,NaN,181٬700,9085.0,20.0,NaN,True,https://basalam.com/goldan.felezi/product/1507...
...,...,...,...,...,...,...,...,...
4865,کود مایع بمباردیر شوگر کیمیتک,کود کامل,13068000,13068000.0,1.0,NaN,True,NaN
4870,کود مایع محرک رشد بمباردیر,کود کامل,10920000,10920000.0,1.0,NaN,True,NaN
4881,هورمون شاخه‌ زایی شوتی (®Shooty) اگری پلاس,هورمون رشد گیاهی,5170000,51700.0,100.0,NaN,True,NaN
4883,هورمون پاکوتاهی - گلدهی کتولی (®Cotooly) اگری ...,هورمون رشد گیاهی,3100000,31000.0,100.0,NaN,True,NaN
4885,هورمون گلدهی فلوری (®Flory) اگری پلاس,هورمون رشد گیاهی,12400000,49600.0,250.0,NaN,True,NaN

In [229]:
df.drop("_pk",axis=1,inplace=True)
df

,name,category,price,price_per_kg,amount_kg,last_price_update,is_available
0,خاک و کود آماده کاشت تای سیز 4 لیتری,NaN,45٬000,28125.0,1.6,NaN,True
1,خاک و کود بستر مخصوص گیاهان آبزی و میگوها اوشن...,NaN,1٬223٬800,407933.333333,3.0,NaN,True
2,خاک و کود آماده کاشت 4 لیتری,NaN,40٬200,10050.0,4.0,NaN,True
3,خاک و کود آماده کاشت گیلدا بسته 4 لیتری,NaN,110٬000,47826.086957,2.3,NaN,True
5,خاک و کود آماده کاشت 20 لیتری,NaN,181٬700,9085.0,20.0,NaN,True
...,...,...,...,...,...,...,...
4865,کود مایع بمباردیر شوگر کیمیتک,کود کامل,13068000,13068000.0,1.0,NaN,True
4870,کود مایع محرک رشد بمباردیر,کود کامل,10920000,10920000.0,1.0,NaN,True
4881,هورمون شاخه‌ زایی شوتی (®Shooty) اگری پلاس,هورمون رشد گیاهی,5170000,51700.0,100.0,NaN,True
4883,هورمون پاکوتاهی - گلدهی کتولی (®Cotooly) اگری ...,هورمون رشد گیاهی,3100000,31000.0,100.0,NaN,True
4885,هورمون گلدهی فلوری (®Flory) اگری پلاس,هورمون رشد گیاهی,12400000,49600.0,250.0,NaN,True

In [230]:
normalizer = PersianNumberNormalizer()
df['name'] = normalizer.convert(df['name'])

In [231]:
# convert all of the prices to float
df["price_per_kg"] = pd.to_numeric(df["price_per_kg"], errors="coerce").astype(float)

In [232]:
df

,name,category,price,price_per_kg,amount_kg,last_price_update,is_available
0,خاک و کود آماده کاشت تای سیز 4 لیتری,NaN,45٬000,2.812500e+04,1.6,NaN,True
1,خاک و کود بستر مخصوص گیاهان آبزی و میگوها اوشن...,NaN,1٬223٬800,4.079333e+05,3.0,NaN,True
2,خاک و کود آماده کاشت 4 لیتری,NaN,40٬200,1.005000e+04,4.0,NaN,True
3,خاک و کود آماده کاشت گیلدا بسته 4 لیتری,NaN,110٬000,4.782609e+04,2.3,NaN,True
5,خاک و کود آماده کاشت 20 لیتری,NaN,181٬700,9.085000e+03,20.0,NaN,True
...,...,...,...,...,...,...,...
4865,کود مایع بمباردیر شوگر کیمیتک,کود کامل,13068000,1.306800e+07,1.0,NaN,True
4870,کود مایع محرک رشد بمباردیر,کود کامل,10920000,1.092000e+07,1.0,NaN,True
4881,هورمون شاخه‌ زایی شوتی (®Shooty) اگری پلاس,هورمون رشد گیاهی,5170000,5.170000e+04,100.0,NaN,True
4883,هورمون پاکوتاهی - گلدهی کتولی (®Cotooly) اگری ...,هورمون رشد گیاهی,3100000,3.100000e+04,100.0,NaN,True
4885,هورمون گلدهی فلوری (®Flory) اگری پلاس,هورمون رشد گیاهی,12400000,4.960000e+04,250.0,NaN,True

In [233]:
raw_source_df = pd.read_excel(io="source/raw_source_of_fertilizer.xlsx")

**Filter specific fertilizer**

npk

In [234]:
# Find rows where 'name' contains 'NPK' (case-insensitive)
filtered_df_npk = df[(df['name'].str.contains('NPK', case=False, na=False)) | (df['name'].str.contains('N P K', case=False, na=False)) | (df['name'].str.contains('کامل', case=False, na=False))]

# Remove soils from it
filtered_df_npk = filtered_df_npk[~filtered_df_npk['name'].str.contains('خاک',na=False)]
filtered_df_npk

,name,category,price,price_per_kg,amount_kg,last_price_update,is_available
2715,کود هیومیک دار NPK 20-5-10 هیومولایف 5 کیلوگرم,هیومیک-اسید,675840,135168.0,5.0,NaN,False
2716,کود هیومیک دار NPK 12-5-20 هیومولایف 5 کیلوگرم,هیومیک-اسید,675840,135168.0,5.0,NaN,False
2742,ماکرو کامل20/20/20,کود کامل ( ماکرو )\n23,5550000.0,555000.0,NaN,NaN,NaN
2743,ماکرو کامل 15/8/15,کود کامل ( ماکرو )\n23,5530000.0,110600.0,NaN,NaN,NaN
2746,ماکرو کامل 10/52/10,کود کامل ( ماکرو )\n23,6240000.0,624000.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...
4673,کود NPK 10 52 10 کوالی مکس,کود NPK,32000000,32000000.0,1.0,NaN,True
4681,کود سه بیست (NPK 20 20 20) کوالی مکس,کود NPK,29000000,29000000.0,1.0,NaN,True
4693,کود 10 52 10 NPK زیگلر آلمان,کود NPK,3960000,3960000.0,1.0,NaN,True
4695,کود NPK 11 53 05 اینترمگ,کود NPK,52600000,52600000.0,1.0,NaN,True
4699,کود 36 12 12 NPK فرمولایف,کود NPK,28175000,28175000.0,1.0,NaN,True

In [235]:
raw_source_df.columns

Index(['sub_input_code', 'input_code', 'Name_of_fertilizer',
       'Group_of_fertilizer', 'Real_Name_of_fertilizer', 'Minimum_Price(Kg)',
       'Maximum_Price(Kg)', 'Exact_Price(Kg)', 'Sources', 'sources_unique',
       'Group_of_fertilizer_unique'],
      dtype='object')

In [236]:
raw_source_df_npk_filtered = raw_source_df[raw_source_df["input_code"] == 17]
raw_source_df_npk_filtered

,sub_input_code,input_code,Name_of_fertilizer,Group_of_fertilizer,Real_Name_of_fertilizer,Minimum_Price(Kg),Maximum_Price(Kg),Exact_Price(Kg),Sources,sources_unique,Group_of_fertilizer_unique
58,111,17,17-111,کود های کامل (N-P-K),20-20-20,900000,2300000,NaN,https://torob.com/,NaN,NaN
59,112,17,17-112,کود های کامل (N-P-K),12-12-36,1690000,2480000,NaN,https://torob.com/,NaN,NaN
60,113,17,17-113,کود های کامل (N-P-K),10-52-10,1700000,2956000,NaN,https://torob.com/,NaN,NaN
61,114,17,17-114,کود های کامل (N-P-K),15-5-40,1690000,2480000,NaN,https://torob.com/,NaN,NaN
62,115,17,17-115,کود های کامل (N-P-K),5-5-15,1690000,2480000,NaN,https://torob.com/,NaN,NaN
63,116,17,17-116,کود های کامل (N-P-K),15-5-30,1690000,2480000,NaN,https://torob.com/,NaN,NaN
64,117,17,17-117,کود های کامل (N-P-K),14-8-30,1690000,2480000,NaN,https://torob.com/,NaN,NaN
65,118,17,17-118,کود های کامل (N-P-K),18-8-30,1690000,2480000,NaN,https://torob.com/,NaN,NaN
66,119,17,17-119,کود های کامل (N-P-K),15-8-15,1090000,1090000,1090000.0,https://torob.com/,NaN,NaN
67,120,17,17-120,کود های کامل (N-P-K),10-4-44,1690000,2480000,NaN,https://torob.com/,NaN,NaN
68,121,17,17-121,کود های کامل (N-P-K),13-40-13,1090000,1090000,1090000.0,https://torob.com/,NaN,NaN
69,122,17,17-122,کود های کامل (N-P-K),12-8-40,1690000,2480000,NaN,https://torob.com/,NaN,NaN
70,123,17,17-123,کود های کامل (N-P-K),15-10-30,1690000,2480000,NaN,https://torob.com/,NaN,NaN
71,124,17,17-124,کود های کامل (N-P-K),12-3-43,1690000,2480000,NaN,https://torob.com/,NaN,NaN
72,125,17,17-125,کود های کامل (N-P-K),30-10-10,3120000,3120000,3120000.0,https://agriplus.ir/,NaN,NaN
73,126,17,17-126,کود های کامل (N-P-K),12-12-17,970000,970000,970000.0,https://torob.com/,NaN,NaN
74,127,17,17-127,کود های کامل (N-P-K),10-10-43,1690000,2480000,NaN,https://torob.com/,NaN,NaN
75,128,17,17-128,کود های کامل (N-P-K),15-5-15,900000,2300000,NaN,https://torob.com/,NaN,NaN
76,129,17,17-129,کود های کامل (N-P-K),18-18-18,4200000,4200000,4200000.0,https://torob.com/,NaN,NaN
77,130,17,17-130,کود های کامل (N-P-K),3-11-38,1690000,2480000,NaN,https://torob.com/,NaN,NaN
78,131,17,17-131,کود های کامل (N-P-K),20-5-10,3120000,3120000,3120000.0,https://agriplus.ir/,NaN,NaN
79,132,17,17-132,کود های کامل (N-P-K),30-6-6,3120000,3120000,3120000.0,https://agriplus.ir/,NaN,NaN
80,133,17,17-133,کود های کامل (N-P-K),40-5-5,3120000,3120000,3120000.0,https://agriplus.ir/,NaN,NaN
81,134,17,17-134,کود های کامل (N-P-K),10-45-10,3200000,3200000,3200000.0,https://torob.com/,NaN,NaN
82,135,17,17-135,کود های کامل (N-P-K),10-5-40,1690000,2480000,NaN,https://torob.com/,NaN,NaN
83,136,17,17-136,کود های کامل (N-P-K),18-10-18,1690000,2480000,NaN,https://torob.com/,NaN,NaN
84,137,17,17-137,کود های کامل (N-P-K),10-30-10,1690000,2480000,NaN,https://torob.com/,NaN,NaN
85,138,17,17-138,کود های کامل (N-P-K),5-5-45,1690000,2480000,NaN,https://torob.com/,NaN,NaN
86,139,17,17-139,کود های کامل (N-P-K),19-6-20,5000000,5000000,5000000.0,https://torob.com/,NaN,NaN
87,140,17,17-140,کود های کامل (N-P-K),4-5-40,1690000,2480000,NaN,https://torob.com/,NaN,NaN
88,141,17,17-141,کود های کامل (N-P-K),15-50-5,3200000,3200000,3200000.0,https://torob.com/,NaN,NaN
89,142,17,17-142,کود های کامل (N-P-K),12-3-43,1690000,2480000,NaN,https://torob.com/,NaN,NaN
90,143,17,17-143,کود های کامل (N-P-K),10-40-10,3200000,3200000,3200000.0,https://torob.com/,NaN,NaN
91,144,17,17-144,کود های کامل (N-P-K),5-10-40,1690000,2480000,NaN,https://torob.com/,NaN,NaN
92,145,17,17-145,کود های کامل (N-P-K),19-19-19,3700000,3700000,3700000.0,https://torob.com/,NaN,NaN
93,146,17,17-146,کود های کامل (N-P-K),15-5-26,1690000,2480000,NaN,https://torob.com/,NaN,NaN
94,147,17,17-147,کود های کامل (N-P-K),17-4-30,1690000,2480000,NaN,https://torob.com/,NaN,NaN
95,148,17,17-148,کود های کامل (N-P-K),40-10-10,1440000,1440000,1440000.0,https://torob.com/,NaN,NaN
96,149,17,17-149,کود های کامل (N-P-K),16-7-28,1690000,2480000,NaN,https://torob.com/,NaN,NaN
97,150,17,17-150,کود های کامل (N-P-K),15-30-15,1700000,1700000,1700000.0,https://torob.com/,NaN,NaN
98,151,17,17-151,کود های کامل (N-P-K),18-16-24,1690000,2480000,NaN,https://torob.com/,NaN,NaN

In [237]:
allRawNpkRealNamesList = raw_source_df_npk_filtered.iloc[:,4]
allRawNpkRealNamesList = allRawNpkRealNamesList.str.replace("-", " ", regex=False).tolist()
allRawNpkRealNamesList

['20 20 20',
 '12 12 36',
 '10 52 10',
 '15 5 40',
 '5 5 15',
 '15 5 30',
 '14 8 30',
 '18 8 30',
 '15 8 15',
 '10 4 44',
 '13 40 13',
 '12 8 40',
 '15 10 30',
 '12 3 43',
 '30 10 10',
 '12 12 17',
 '10 10 43',
 '15 5 15',
 '18 18 18',
 '3 11 38',
 '20 5 10',
 '30 6 6',
 '40 5 5',
 '10 45 10',
 '10 5 40',
 '18 10 18',
 '10 30 10',
 '5 5 45',
 '19 6 20',
 '4 5 40',
 '15 50 5',
 '12 3 43',
 '10 40 10',
 '5 10 40',
 '19 19 19',
 '15 5 26',
 '17 4 30',
 '40 10 10',
 '16 7 28',
 '15 30 15',
 '18 16 24']

In [238]:
filtered_df_npk

,name,category,price,price_per_kg,amount_kg,last_price_update,is_available
2715,کود هیومیک دار NPK 20-5-10 هیومولایف 5 کیلوگرم,هیومیک-اسید,675840,135168.0,5.0,NaN,False
2716,کود هیومیک دار NPK 12-5-20 هیومولایف 5 کیلوگرم,هیومیک-اسید,675840,135168.0,5.0,NaN,False
2742,ماکرو کامل20/20/20,کود کامل ( ماکرو )\n23,5550000.0,555000.0,NaN,NaN,NaN
2743,ماکرو کامل 15/8/15,کود کامل ( ماکرو )\n23,5530000.0,110600.0,NaN,NaN,NaN
2746,ماکرو کامل 10/52/10,کود کامل ( ماکرو )\n23,6240000.0,624000.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...
4673,کود NPK 10 52 10 کوالی مکس,کود NPK,32000000,32000000.0,1.0,NaN,True
4681,کود سه بیست (NPK 20 20 20) کوالی مکس,کود NPK,29000000,29000000.0,1.0,NaN,True
4693,کود 10 52 10 NPK زیگلر آلمان,کود NPK,3960000,3960000.0,1.0,NaN,True
4695,کود NPK 11 53 05 اینترمگ,کود NPK,52600000,52600000.0,1.0,NaN,True
4699,کود 36 12 12 NPK فرمولایف,کود NPK,28175000,28175000.0,1.0,NaN,True

In [239]:
rows = []

# NPK to Dataframe
for name in allRawNpkRealNamesList:
    filtered = filtered_df_npk[filtered_df_npk['name'].str.contains(name, na=False)]
    if filtered.empty:
        continue  # skip if no matches
    
    row = {
        "code": raw_source_df_npk_filtered.iloc[allRawNpkRealNamesList.index(name),2], 
        "name": name,
        "avg": filtered['price_per_kg'].mean(), 
        "min": filtered['price_per_kg'].min(),
        "max": filtered['price_per_kg'].max(),
        "std": filtered['price_per_kg'].std(),
        "listOfNames": filtered['name'].tolist(),
        "listOfPrices": filtered['price_per_kg'].tolist(),
    }
    rows.append(row)

# Convert list of dicts directly to a DataFrame
result_df = pd.DataFrame(rows)

print(result_df)

     code      name         avg        min         max           std  \
0  17-111  20 20 20  11310000.0   300000.0  29000000.0  1.547221e+07
1  17-113  10 52 10  17980000.0  3960000.0  32000000.0  1.982727e+07
2  17-129  18 18 18   4630000.0  4630000.0   4630000.0           NaN
3  17-139   19 6 20   4630000.0  4630000.0   4630000.0           NaN

                                         listOfNames  \
0  [کود سه 20 مایع تری پرو فارمونتی NPK 20 20 20+...
1  [کود NPK 10 52 10 کوالی مکس, کود 10 52 10 NPK ...
2                         [کود NPK 18 18 18 باواریا]
3                          [کود NPK 19 6 20 باواریا]

                        listOfPrices
0  [300000.0, 4630000.0, 29000000.0]
1            [32000000.0, 3960000.0]
2                        [4630000.0]
3                        [4630000.0]

In [240]:
result_df

,code,name,avg,min,max,std,listOfNames,listOfPrices
0,17-111,20 20 20,11310000.0,300000.0,29000000.0,1.547221e+07,[کود سه 20 مایع تری پرو فارمونتی NPK 20 20 20+...,"[300000.0, 4630000.0, 29000000.0]"
1,17-113,10 52 10,17980000.0,3960000.0,32000000.0,1.982727e+07,"[کود NPK 10 52 10 کوالی مکس, کود 10 52 10 NPK ...","[32000000.0, 3960000.0]"
2,17-129,18 18 18,4630000.0,4630000.0,4630000.0,NaN,[کود NPK 18 18 18 باواریا],[4630000.0]
3,17-139,19 6 20,4630000.0,4630000.0,4630000.0,NaN,[کود NPK 19 6 20 باواریا],[4630000.0]

In [241]:
npk_excluded_raw_source = raw_source_df[raw_source_df["input_code"] != 17]
npk_excluded_raw_source

,sub_input_code,input_code,Name_of_fertilizer,Group_of_fertilizer,Real_Name_of_fertilizer,Minimum_Price(Kg),Maximum_Price(Kg),Exact_Price(Kg),Sources,sources_unique,Group_of_fertilizer_unique
0,111,11,11-111,کود نیتروژن (ازته),اوره,25000,600000,42500.0,https://www.bbk-iran.com/,https://www.bbk-iran.com/,کود نیتروژن (ازته)
1,112,11,11-112,کود نیتروژن (ازته),آمونیاک,440000,440000,440000.0,https://shimistore.com/product/ammonia/,https://shimistore.com/product/ammonia/,کود فسفاته
2,113,11,11-113,کود نیتروژن (ازته),نیترات آمونیوم,640000,640000,640000.0,torob.com,torob.com,کود پتاسه
3,114,11,11-114,کود نیتروژن (ازته),اسید نیتریک,640000,640000,640000.0,torob.com,https://www.bbk-iran.com,کود کلسیم
4,115,11,11-115,کود نیتروژن (ازته),سولفات آمونیوم,210000,100000,155000.0,https://www.bbk-iran.com,https://digikoud.com/,کود منیزیم
...,...,...,...,...,...,...,...,...,...,...,...
190,113,99,99-113,سایر کود ها,ضد شوری,3120000,4100000,NaN,https://torob.com/,NaN,NaN
191,114,99,99-114,سایر کود ها,ضد تنش,3990000,3990000,NaN,https://sepahankesht.com/,NaN,NaN
192,115,99,99-115,سایر کود ها,اصلاح کننده خاک,420000,3200000,NaN,https://torob.com/,NaN,NaN
193,116,99,99-116,سایر کود ها,اصلاح کننده ph,1220000,1650000,NaN,https://torob.com/,NaN,NaN
194,117,99,99-117,سایر کود ها,ریشه زا ( تریکوران، پارس باسیل و ...),6890000,8450000,NaN,https://torob.com/,NaN,NaN

In [242]:
npk_excluded_raw_source.iloc[:,4].tolist()

['اوره',
 'آمونیاک',
 'نیترات آمونیوم',
 'اسید نیتریک',
 'سولفات آمونیوم',
 'اوره با پوشش گوگردی',
 'اوره سولفاتی',
 'اوره نیترات آمونیوم',
 ' فسفات آمونیوم',
 'نیترات کلسیم',
 'نیترات پتاسیم',
 'اوره فسفات',
 'مونو فسفات پتاسیم',
 'فسفات آمونیم',
 'فسفیت پتاسیم',
 'فسفات دی آمونیم ',
 'نیترات فسفات آمونیوم',
 'سنگ فسفات',
 'سوپر فسفات تریپل',
 'اسید فسفریک',
 'دی سوپر فسفات',
 ' سوپر فسفات ساده',
 'مونو آمونیوم فسفات',
 'فسفات آمونیاک',
 'فسفات گوگردی',
 'آمینو فسفات',
 'فسفات کلسیم',
 'کلات فسفر',
 'سولفات پتاسیم',
 'کلرور پتاسیم',
 'مونو پتاسیم فسفات',
 'پتاسیم نیترات',
 'پتاسیم منیزیم',
 'آمینو پتاس',
 'پتاسه گرانوله',
 'کلات پتاسیم',
 ' پتاسیم سیلیکات',
 'کلسیم نیترات',
 'کلات کلسیم',
 'کلسیم بورات',
 'آمینو کلسیم',
 'کلسیم فسفات',
 'کلسیم آمونیوم نیترات',
 'کلسیم منیزیم',
 'سولفات کلسیم',
 'کلرو کلسیم',
 'سولفات منیزیم',
 'نیترات منیزیم',
 'کلات منیزیم',
 'منیزیم فسفیت',
 ' پتاس منیزیم',
 'منیزیم روی',
 'امینو منیزیم',
 'گوگرد پودری',
 'گوگرد گرانوله',
 'اسید سولفوریک',
 'گوگرد مایع',
 'گوگرد بنتونیت دار',
 'فروت ست (ازت+بر+روی)',
 'دلفارد',
 'چالکود',
 ' اهن -روی- منگنز',
 'روی-بر-پتاسیم',
 'پتاسیم کلسیم نیترات',
 '12-12-36+TE',
 '15-5-30+TE',
 '10-52-10+TE',
 '20-20-20+TE',
 '9-7-7+TE',
 '17-0-6+Ca',
 'کلات منگز',
 'سولفات منگنز',
 'امینو منگنز',
 'آهن منگنز روی',
 'آهن سکوسترین',
 'سولفات آهن',
 'کلات آهن',
 'آمینو اهن',
 'نیترات آهن',
 ' کلات روی',
 'سولفات روی',
 'امینو روی',
 'نیترات روی',
 'فسفات روی',
 'اهن روی منگنز',
 'آمینو بور',
 'اسید بریک',
 'بورات کلسیم',
 'کلات بور',
 'سولفات بور',
 ' کلات مس',
 'سولفات مس',
 'امینو مس',
 'کلات مولیبدن',
 'مولیبدات پتاسیم',
 'مولیبدات آمونیوم',
 'آمینو مولیبدن',
 'سولفات کبالت',
 'آمینو کلات کبالت',
 'نیکل',
 'کلر',
 'میکروکامل',
 'میکرومیکس',
 'سیلیکون',
 'سیلیکات پتاسیم',
 'مگنز نیتروژن',
 'روی نیتروژن',
 'مس نیتروژن',
 'میکرو سولفاته',
 'مخلوط میکرو',
 'میکرو کلاته',
 'گاوی',
 'مرغی',
 'گوسفندی',
 'اسبی',
 'کفتری',
 'پلیت مرغی',
 'مرغی مایع',
 'ماهی',
 'مرغی گرانوله',
 'کمپوست',
 'ورمی کمپوست',
 'کود سبز',
 'اسید هیومیک',
 'اسید آمینه',
 'فولیک اسید',
 'گوگرد آلی',
 'هیومات پتاسیم',
 'اسیدهیومیک + ریزمغزی',
 'اسید آمینه + ریز مغذی',
 'جلبک دریایی',
 'بایوچار',
 'نیتروزیست',
 'فسفوزیست',
 'ازتو باکتر',
 'باکتری تیوباسیلوس',
 'باکتری ریزوبیوم',
 ' باکتری آزوسپریلیوم',
 'قارچ میکوریزا',
 'باکتریهای ریزوسفر محرک رشد',
 'تثبیت کننده های نیتروژن',
 ' حل کننده های فسفات',
 'فسفر + باکتریهای حل کننده فسفات',
 'فلاویت',
 'قارچ تریکودرما',
 'اسیدهای آمینه + باکتری محرک رشد',
 'باکتریهای تثبیت کننده ازت، حل\xad\u200cکننده فسفر و محرک رشد',
 'کود بذر مال',
 'فرتی فراست (ضد سرما)',
 'ضد شوری',
 'ضد تنش',
 'اصلاح کننده خاک',
 'اصلاح کننده  ph',
 ' ریشه زا ( تریکوران، پارس باسیل و ...)']

Other fertilizers

In [243]:


# # Others to Dataframe
# for counter in range(len(npk_excluded_raw_source.iloc[:,4].tolist())):
#     name = npk_excluded_raw_source.iloc[:,4].tolist()[counter]
#     filtered = df[df['name'].str.contains(re.escape(name), na=False, case=False)]
#     if filtered.empty:
#         continue  # skip if no matches
    
#     row = {
#         "code": npk_excluded_raw_source.iloc[counter,2], 
#         "name": name,
#         "avg": filtered['price_per_kg'].mean(), 
#         "min": filtered['price_per_kg'].min(),
#         "max": filtered['price_per_kg'].max(),
#         "std": filtered['price_per_kg'].std(),
#         "listOfNames": filtered['name'].tolist(),
#         "listOfPrices": filtered['price_per_kg'].tolist(),
#     }
#     rows.append(row)

# # Convert list of dicts directly to a DataFrame
# result_df = pd.DataFrame(rows)

# print(result_df)

In [244]:
import pandas as pd

def contains_all_words(text, words):
    """Check if all words are present in text (any order). Case insensitive."""
    text_lower = str(text).lower()
    return all(word in text_lower for word in words)

for counter, full_name in enumerate(npk_excluded_raw_source.iloc[:, 4].tolist()):
    words = full_name.split()
    
    # Filter rows where 'name' column contains all words (in any order)
    filtered = df[df['name'].apply(lambda x: contains_all_words(x, words))]
    
    if filtered.empty:
        continue  # skip if no matches
    
    row = {
        "code": npk_excluded_raw_source.iloc[counter, 2],
        "name": full_name,
        "avg": filtered['price_per_kg'].mean(),
        "min": filtered['price_per_kg'].min(),
        "max": filtered['price_per_kg'].max(),
        "std": filtered['price_per_kg'].std(),
        "listOfNames": filtered['name'].tolist(),
        "listOfPrices": filtered['price_per_kg'].tolist(),
    }
    rows.append(row)

result_df = pd.DataFrame(rows)
print(result_df)

      code                 name           avg           min          max  \
0   17-111             20 20 20  1.131000e+07  3.000000e+05  29000000.00
1   17-113             10 52 10  1.798000e+07  3.960000e+06  32000000.00
2   17-129             18 18 18  4.630000e+06  4.630000e+06   4630000.00
3   17-139              19 6 20  4.630000e+06  4.630000e+06   4630000.00
4   11-111                 اوره  1.267000e+06  3.400000e+04  13000000.00
5   11-115       سولفات آمونیوم  7.904583e+04  2.000000e+03    141999.94
6   11-116  اوره با پوشش گوگردی  2.490000e+05  1.160000e+05    392000.00
7   11-119        فسفات آمونیوم  2.980273e+05  1.116000e+05    700000.00
8   11-120         نیترات کلسیم  3.711364e+05  4.400000e+03   2730000.00
9   11-121        نیترات پتاسیم  1.018543e+06  2.000000e+05   3700000.00
10  12-111           اوره فسفات  3.212667e+06  1.750000e+05  13000000.00
11  12-112    مونو فسفات پتاسیم  1.033489e+06  5.400000e+03   4130000.00
12  12-114         فسفیت پتاسیم  1.000467e+06  7.800000e+05   1411000.00
13  12-121      سوپر فسفات ساده  1.221000e+05  6.840002e+04    152000.00
14  12-122   مونو آمونیوم فسفات  2.819000e+05  1.800000e+05    399500.00
15  12-124         فسفات گوگردی  1.176600e+05  1.700000e+04    170000.00
16  13-111        سولفات پتاسیم  1.314641e+06  1.500000e+03  17000000.00
17  13-113    مونو پتاسیم فسفات  1.033489e+06  5.400000e+03   4130000.00
18  13-114        پتاسیم نیترات  1.018543e+06  2.000000e+05   3700000.00
19  13-115        پتاسیم منیزیم  1.389800e+05  1.359600e+05    142000.00
20  13-117        پتاسه گرانوله  1.020000e+05  1.020000e+05    102000.00
21  13-119       پتاسیم سیلیکات  2.946000e+05  1.470000e+05    500000.00
22  14-111         کلسیم نیترات  3.711364e+05  4.400000e+03   2730000.00
23  14-112           کلات کلسیم  1.632500e+05  1.625000e+05    164000.00
24  14-117         کلسیم منیزیم  4.550000e+05  1.575000e+05   1050000.00
25  15-111        سولفات منیزیم  8.047333e+04  2.320000e+04    157500.00
26  15-112        نیترات منیزیم  2.125000e+06  2.125000e+06   2125000.00
27  15-115          پتاس منیزیم  1.389800e+05  1.359600e+05    142000.00
28  16-111          گوگرد پودری  1.170667e+05  2.200000e+03    273000.00
29  16-112        گوگرد گرانوله  6.450000e+04  3.800000e+04     91000.00
30  16-114           گوگرد مایع  1.776782e+05  1.025000e+04    550000.00
31  16-115    گوگرد بنتونیت دار  1.006667e+05  9.100000e+04    120000.00
32  18-113               چالکود  9.174667e+04  2.244000e+04    134000.00
33  19-112         سولفات منگنز  7.313600e+05  7.000000e+03   1837000.00
34  19-114        آهن منگنز روی  7.500000e+06  7.500000e+06   7500000.00
35  19-116           سولفات آهن  1.066333e+05  2.320000e+04    180000.00
36  19-117             کلات آهن  1.298500e+06  2.000000e+05   1956000.00
37  19-120             کلات روی  2.966250e+05  1.625000e+05    650000.00
38  19-121           سولفات روی  1.647464e+06  1.392000e+05  13750000.00
39  19-124            فسفات روی  1.116000e+05  1.116000e+05    111600.00
40  19-129             کلات بور  1.632500e+05  1.625000e+05    164000.00
41  19-132            سولفات مس  2.139667e+06  2.460000e+05   5926000.00
42  19-141                  کلر  6.875000e+05  5.400000e+05    990000.00
43  19-143            میکرومیکس  3.770000e+05  9.300000e+04    850000.00
44  19-145       سیلیکات پتاسیم  2.946000e+05  1.470000e+05    500000.00
45  20-112                 مرغی  5.961834e+04  6.800000e+03    158800.00
46  21-111            پلیت مرغی  5.900000e+04  9.100000e+03    158800.00
47  21-112            مرغی مایع  6.618500e+04  1.295000e+04    120000.00
48  21-113                 ماهی  6.550000e+04  5.250000e+04     80000.00
49  21-115               کمپوست  1.444865e+04  4.882353e+02     45000.00
50  21-116          ورمی کمپوست  1.700393e+04  5.000000e+03     45000.00
51  21-117              کود سبز  1.530000e+05  5.400000e+04    230000.00
52  21-118          اسید هیومیک  6.479957e+05  1.040000e+04  19320000.00
53  21-119           اسید آمینه  6.790000e+06  9.700000e+05  18400000.00
54  21-120           فولیک اسید  4.397900e+05  4.397900e+05    439790.00
55  21-121            گوگرد آلی  3.800000e+04  3.800000e+04     38000.00
56  22-111          جلبک دریایی  1.064860e+06  1.776000e+05   2150000.00
57  99-113              ضد شوری  2.665930e+05  6.240000e+04    610800.00
58  99-115      اصلاح کننده خاک  6.912500e+05  1.825000e+05   1200000.00

             std                                        listOfNames  \
0   1.547221e+07  [کود سه 20 مایع تری پرو فارمونتی NPK 20 20 20+...
1   1.982727e+07  [کود NPK 10 52 10 کوالی مکس, کود 10 52 10 NPK ...
2            NaN                         [کود NPK 18 18 18 باواریا]
3            NaN                          [کود NPK 19 6 20 باواریا]
4   3.150216e+06  [اوره سولفات, اوره با پوشش گوگردی, اوره با پوش...
5   4.307121e+04  [سولفات آمونیوم پودری, سولفات آمونیوم ازبک, سو...
6   1.537921e+05  [اوره با پوشش گوگردی, اوره با پوشش گوگردی, اور...
7   1.698862e+05  [فسفات آمونیوم, دی آمونیوم فسفات چینی, فسفات آ...
8   7.865832e+05  [نیترات کلسیم, نیترات کلسیم, کود نیترات کلسیم ...
9   1.264799e+06  [نیترات پتاسیم, نیترات پتاسیم, نیترات پتاسیم و...
10  4.968804e+06  [کود آلی اوره فسفات (NP) کیلیترین 1 لیتری - 20...
11  1.712340e+06  [مونو پتاسیم فسفات, مونو پتاسیم فسفات, کود تقو...
12  2.455559e+05  [کود فسفیت پتاسیم (فوس وید ) سوپر مکس 1 لیتر, ...
13  3.961867e+04  [سوپر فسفات ساده, سوپر فسفات ساده, سوپر فسفات ...
14  8.486784e+04  [کود مونو آمونیوم فسفات 0-61-12 فرمولایف 10 کی...
15  8.719729e+04         [فسفات گوگردی, فسفات گوگردی, فسفات گوگردی]
16  4.222760e+06  [سولفات پتاسیم منیزیم 10/4, سولفات پتاسیم منیز...
17  1.712340e+06  [مونو پتاسیم فسفات, مونو پتاسیم فسفات, کود تقو...
18  1.264799e+06  [نیترات پتاسیم, نیترات پتاسیم, نیترات پتاسیم و...
19  4.270925e+03  [سولفات پتاسیم منیزیم 10/4, سولفات پتاسیم منیز...
20  0.000000e+00               [پتاسه گرانوله30%, پتاسه گرانوله30%]
21  1.355168e+05  [کود سیلیکات پتاسیم 2/5 لیتری آگروفر, سیلیکات ...
22  7.865832e+05  [نیترات کلسیم, نیترات کلسیم, کود نیترات کلسیم ...
23  1.060660e+03  [کود کلاته کلسیم-بور-روی مایع کلبومکس فارمونتی...
24  5.152851e+05  [کلسیم منیزیم, کلسیم منیزیم, کود کشاورزی کلسیم...
25  5.370865e+04  [سولفات پتاسیم منیزیم 10/4, سولفات منیزیم, سول...
26           NaN                      [کود نیترات منیزیم کوالی مکس]
27  4.270925e+03  [سولفات پتاسیم منیزیم 10/4, سولفات پتاسیم منیز...
28  1.399929e+05  [نیترات پتاسیم و کربن فعال و گوگرد پودری فلات ...
29  3.059956e+04  [گوگرد آلی گرانوله, گوگرد گرانوله بنتونیت دار ...
30  1.678102e+05  [گوگرد مایع پتاسه, گوگرد مایع, گوگرد مایع پتاس...
31  1.674316e+04  [گوگرد بنتونیت دار, گوگرد گرانوله بنتونیت دار ...
32  6.050058e+04  [چالکود فرموکمپلکس همراه با گوگرد و عناصر ریزم...
33  7.344904e+05  [سولفات منگنز چینی, سولفات منگنز چینی, کود سول...
34           NaN  [کود اسپانیایی ریز مغذی سه گانه آهن روی منگنز ...
35  6.758253e+04  [سولفات آهن 17 درصد, سولفات آهن 20 درصد, سولفا...
36  8.219025e+05  [کلات آهن لایفر 6٪ اسپانیایی, کلات آهن, کود آه...
37  2.366127e+05  [کود کلاته کلسیم-بور-روی مایع کلبومکس فارمونتی...
38  4.018046e+06  [سولفات روی پودری 34%, سولفات روی پودری 22 درص...
39           NaN  [کود دی آمونیوم فسفات 4 لیتری (فسفر بالا رویش 2)]
40  1.060660e+03  [کود کلاته کلسیم-بور-روی مایع کلبومکس فارمونتی...
41  3.279061e+06  [کات کبود (سولفات مس)5 کیلو گرم, کات کبود (سول...
42  2.083867e+05  [سم قارچ کش کوپراکسی کلراید اکسی کلرور مس پودر...
43  3.520691e+05  [میکرومیکس بازرگان کالا بسته بندی 1 لیتری یک غ...
44  1.355168e+05  [کود سیلیکات پتاسیم 2/5 لیتری آگروفر, سیلیکات ...
45  3.795275e+04  [کود مرغی مایع نیو داتیس آل (NEW DATIS ALL) حج...
46  8.642934e+04  [کود پلیت مرغی 25 کیلوگرمی, گابری گلدن(پلیت کو...
47  3.241302e+04  [کود مرغی مایع نیو داتیس آل (NEW DATIS ALL) حج...
48  1.350926e+04  [عصاره کود مرغ و ماهی غنی شده با هیومیک و فولو...
49  1.194283e+04  [خاک ورمی کمپوست سایز متوسط 10 لیتری آقای خاک,...
50  1.398516e+04  [خاک ورمی کمپوست سایز متوسط 10 لیتری آقای خاک,...
51  9.003888e+04  [کود اسید انفوریک مایع مگافرتیل ان اس 10 لیتری...
52  2.515547e+06  [کود هیومیک اسید مایع هیومولایف 5 لیتر, کود هی...
53  1.005457e+07  [اسید آمینه کیلیترین 1 لیتری - 1, کود مایع اسی...
54           NaN  [گابری هیومیک مایع (اسید هیومیک + فولیک)(20لیت...
55  0.000000e+00             [گوگرد آلی گرانوله, گوگرد آلی گرانوله]
56  6.659804e+05  [کود جلبک دریایی سیفول, کود جلبک دریایی مایع ش...
57  2.383079e+05  [کود ضد شوری فورنوترینت (Anti Salt) 5 لیتر, کو...
58  7.194811e+05  [کود تقویتی اصلاح کننده خاک و ضد شوری پرک سویل...

                                         listOfPrices
0                   [300000.0, 4630000.0, 29000000.0]
1                             [32000000.0, 3960000.0]
2                                         [4630000.0]
3                                         [4630000.0]
4   [355000.0, 372000.16, 116000.0, 340000.0, 3400...
5   [141999.94, 98000.0, 106000.0, 111000.0, 11100...
6           [372000.16, 116000.0, 116000.0, 392000.0]
7   [181600.0, 470000.0, 181600.0, 700000.0, 11160...
8   [190000.0, 190000.0, 111800.0, 150000.0, 92500...
9   [1100000.16, 1300000.0, 273000.0, 258800.0, 29...
10  [13000000.0, 191000.0, 3250000.0, 280000.0, 17...
11  [100000.0, 100000.0, 412500.0, 300000.0, 83500...
12  [897000.0, 1411000.0, 780000.0, 782800.0, 1160...
13           [68400.02, 152000.0, 152000.0, 116000.0]
14  [222000.0, 399500.0, 308000.0, 300000.0, 18000...
15                      [165980.0, 17000.0, 170000.0]
16  [135960.0, 142000.0, 168000.0, 150000.0, 69200...
17  [100000.0, 100000.0, 412500.0, 300000.0, 83500...
18  [1100000.16, 1300000.0, 273000.0, 258800.0, 29...
19                               [135960.0, 142000.0]
20                               [102000.0, 102000.0]
21  [147000.0, 350000.0, 500000.0, 236000.0, 24000...
22  [190000.0, 190000.0, 111800.0, 150000.0, 92500...
23                               [162500.0, 164000.0]
24                    [157500.0, 157500.0, 1050000.0]
25  [135960.0, 63000.0, 157500.0, 142000.0, 30000....
26                                        [2125000.0]
27                               [135960.0, 142000.0]
28                        [273000.0, 76000.0, 2200.0]
29               [38000.0, 91000.0, 91000.0, 38000.0]
30  [550000.0, 350000.0, 550000.0, 350000.0, 13000...
31                       [120000.0, 91000.0, 91000.0]
32                      [118800.0, 22440.0, 134000.0]
33  [850000.0, 850000.0, 112800.0, 7000.0, 1837000.0]
34                                        [7500000.0]
35  [120000.0, 169000.0, 180000.0, 120000.0, 27600...
36        [200000.0, 1900000.0, 1138000.0, 1956000.0]
37           [162500.0, 164000.0, 210000.0, 650000.0]
38  [430000.0, 640000.0, 620000.04, 245200.0, 4300...
39                                         [111600.0]
40                               [162500.0, 164000.0]
41                    [247000.0, 246000.0, 5926000.0]
42           [990000.0, 540000.0, 560000.0, 660000.0]
43            [850000.0, 125000.0, 93000.0, 440000.0]
44  [147000.0, 350000.0, 500000.0, 236000.0, 24000...
45  [65280.0, 78672.0, 104280.0, 120000.0, 120000....
46                         [9100.0, 158800.0, 9100.0]
47  [65280.0, 104280.0, 120000.0, 120000.0, 84250....
48      [80000.0, 60000.0, 55000.0, 52500.0, 80000.0]
49  [19960.0, nan, nan, nan, 18000.0, 6480.0, 2500...
50  [19960.0, nan, nan, nan, 6480.0, 45000.0, 5000...
51                      [54000.0, 230000.0, 175000.0]
52  [231000.0, 88176.0, 75504.0, 228360.0, 82280.0...
53                  [1000000.0, 970000.0, 18400000.0]
54                                         [439790.0]
55                                 [38000.0, 38000.0]
56  [187000.0, 177600.0, 2150000.0, 1920000.0, 950...
57            [62400.0, 210672.0, 182500.0, 610800.0]
58                              [182500.0, 1200000.0]

In [245]:
result_df

,code,name,avg,min,max,std,listOfNames,listOfPrices
0,17-111,20 20 20,1.131000e+07,3.000000e+05,29000000.00,1.547221e+07,[کود سه 20 مایع تری پرو فارمونتی NPK 20 20 20+...,"[300000.0, 4630000.0, 29000000.0]"
1,17-113,10 52 10,1.798000e+07,3.960000e+06,32000000.00,1.982727e+07,"[کود NPK 10 52 10 کوالی مکس, کود 10 52 10 NPK ...","[32000000.0, 3960000.0]"
2,17-129,18 18 18,4.630000e+06,4.630000e+06,4630000.00,NaN,[کود NPK 18 18 18 باواریا],[4630000.0]
3,17-139,19 6 20,4.630000e+06,4.630000e+06,4630000.00,NaN,[کود NPK 19 6 20 باواریا],[4630000.0]
4,11-111,اوره,1.267000e+06,3.400000e+04,13000000.00,3.150216e+06,"[اوره سولفات, اوره با پوشش گوگردی, اوره با پوش...","[355000.0, 372000.16, 116000.0, 340000.0, 3400..."
5,11-115,سولفات آمونیوم,7.904583e+04,2.000000e+03,141999.94,4.307121e+04,"[سولفات آمونیوم پودری, سولفات آمونیوم ازبک, سو...","[141999.94, 98000.0, 106000.0, 111000.0, 11100..."
6,11-116,اوره با پوشش گوگردی,2.490000e+05,1.160000e+05,392000.00,1.537921e+05,"[اوره با پوشش گوگردی, اوره با پوشش گوگردی, اور...","[372000.16, 116000.0, 116000.0, 392000.0]"
7,11-119,فسفات آمونیوم,2.980273e+05,1.116000e+05,700000.00,1.698862e+05,"[فسفات آمونیوم, دی آمونیوم فسفات چینی, فسفات آ...","[181600.0, 470000.0, 181600.0, 700000.0, 11160..."
8,11-120,نیترات کلسیم,3.711364e+05,4.400000e+03,2730000.00,7.865832e+05,"[نیترات کلسیم, نیترات کلسیم, کود نیترات کلسیم ...","[190000.0, 190000.0, 111800.0, 150000.0, 92500..."
9,11-121,نیترات پتاسیم,1.018543e+06,2.000000e+05,3700000.00,1.264799e+06,"[نیترات پتاسیم, نیترات پتاسیم, نیترات پتاسیم و...","[1100000.16, 1300000.0, 273000.0, 258800.0, 29..."
10,12-111,اوره فسفات,3.212667e+06,1.750000e+05,13000000.00,4.968804e+06,[کود آلی اوره فسفات (NP) کیلیترین 1 لیتری - 20...,"[13000000.0, 191000.0, 3250000.0, 280000.0, 17..."
11,12-112,مونو فسفات پتاسیم,1.033489e+06,5.400000e+03,4130000.00,1.712340e+06,"[مونو پتاسیم فسفات, مونو پتاسیم فسفات, کود تقو...","[100000.0, 100000.0, 412500.0, 300000.0, 83500..."
12,12-114,فسفیت پتاسیم,1.000467e+06,7.800000e+05,1411000.00,2.455559e+05,"[کود فسفیت پتاسیم (فوس وید ) سوپر مکس 1 لیتر, ...","[897000.0, 1411000.0, 780000.0, 782800.0, 1160..."
13,12-121,سوپر فسفات ساده,1.221000e+05,6.840002e+04,152000.00,3.961867e+04,"[سوپر فسفات ساده, سوپر فسفات ساده, سوپر فسفات ...","[68400.02, 152000.0, 152000.0, 116000.0]"
14,12-122,مونو آمونیوم فسفات,2.819000e+05,1.800000e+05,399500.00,8.486784e+04,[کود مونو آمونیوم فسفات 0-61-12 فرمولایف 10 کی...,"[222000.0, 399500.0, 308000.0, 300000.0, 18000..."
15,12-124,فسفات گوگردی,1.176600e+05,1.700000e+04,170000.00,8.719729e+04,"[فسفات گوگردی, فسفات گوگردی, فسفات گوگردی]","[165980.0, 17000.0, 170000.0]"
16,13-111,سولفات پتاسیم,1.314641e+06,1.500000e+03,17000000.00,4.222760e+06,"[سولفات پتاسیم منیزیم 10/4, سولفات پتاسیم منیز...","[135960.0, 142000.0, 168000.0, 150000.0, 69200..."
17,13-113,مونو پتاسیم فسفات,1.033489e+06,5.400000e+03,4130000.00,1.712340e+06,"[مونو پتاسیم فسفات, مونو پتاسیم فسفات, کود تقو...","[100000.0, 100000.0, 412500.0, 300000.0, 83500..."
18,13-114,پتاسیم نیترات,1.018543e+06,2.000000e+05,3700000.00,1.264799e+06,"[نیترات پتاسیم, نیترات پتاسیم, نیترات پتاسیم و...","[1100000.16, 1300000.0, 273000.0, 258800.0, 29..."
19,13-115,پتاسیم منیزیم,1.389800e+05,1.359600e+05,142000.00,4.270925e+03,"[سولفات پتاسیم منیزیم 10/4, سولفات پتاسیم منیز...","[135960.0, 142000.0]"
20,13-117,پتاسه گرانوله,1.020000e+05,1.020000e+05,102000.00,0.000000e+00,"[پتاسه گرانوله30%, پتاسه گرانوله30%]","[102000.0, 102000.0]"
21,13-119,پتاسیم سیلیکات,2.946000e+05,1.470000e+05,500000.00,1.355168e+05,"[کود سیلیکات پتاسیم 2/5 لیتری آگروفر, سیلیکات ...","[147000.0, 350000.0, 500000.0, 236000.0, 24000..."
22,14-111,کلسیم نیترات,3.711364e+05,4.400000e+03,2730000.00,7.865832e+05,"[نیترات کلسیم, نیترات کلسیم, کود نیترات کلسیم ...","[190000.0, 190000.0, 111800.0, 150000.0, 92500..."
23,14-112,کلات کلسیم,1.632500e+05,1.625000e+05,164000.00,1.060660e+03,[کود کلاته کلسیم-بور-روی مایع کلبومکس فارمونتی...,"[162500.0, 164000.0]"
24,14-117,کلسیم منیزیم,4.550000e+05,1.575000e+05,1050000.00,5.152851e+05,"[کلسیم منیزیم, کلسیم منیزیم, کود کشاورزی کلسیم...","[157500.0, 157500.0, 1050000.0]"
25,15-111,سولفات منیزیم,8.047333e+04,2.320000e+04,157500.00,5.370865e+04,"[سولفات پتاسیم منیزیم 10/4, سولفات منیزیم, سول...","[135960.0, 63000.0, 157500.0, 142000.0, 30000...."
26,15-112,نیترات منیزیم,2.125000e+06,2.125000e+06,2125000.00,NaN,[کود نیترات منیزیم کوالی مکس],[2125000.0]
27,15-115,پتاس منیزیم,1.389800e+05,1.359600e+05,142000.00,4.270925e+03,"[سولفات پتاسیم منیزیم 10/4, سولفات پتاسیم منیز...","[135960.0, 142000.0]"
28,16-111,گوگرد پودری,1.170667e+05,2.200000e+03,273000.00,1.399929e+05,[نیترات پتاسیم و کربن فعال و گوگرد پودری فلات ...,"[273000.0, 76000.0, 2200.0]"
29,16-112,گوگرد گرانوله,6.450000e+04,3.800000e+04,91000.00,3.059956e+04,"[گوگرد آلی گرانوله, گوگرد گرانوله بنتونیت دار ...","[38000.0, 91000.0, 91000.0, 38000.0]"
30,16-114,گوگرد مایع,1.776782e+05,1.025000e+04,550000.00,1.678102e+05,"[گوگرد مایع پتاسه, گوگرد مایع, گوگرد مایع پتاس...","[550000.0, 350000.0, 550000.0, 350000.0, 13000..."
31,16-115,گوگرد بنتونیت دار,1.006667e+05,9.100000e+04,120000.00,1.674316e+04,"[گوگرد بنتونیت دار, گوگرد گرانوله بنتونیت دار ...","[120000.0, 91000.0, 91000.0]"
32,18-113,چالکود,9.174667e+04,2.244000e+04,134000.00,6.050058e+04,[چالکود فرموکمپلکس همراه با گوگرد و عناصر ریزم...,"[118800.0, 22440.0, 134000.0]"
33,19-112,سولفات منگنز,7.313600e+05,7.000000e+03,1837000.00,7.344904e+05,"[سولفات منگنز چینی, سولفات منگنز چینی, کود سول...","[850000.0, 850000.0, 112800.0, 7000.0, 1837000.0]"
34,19-114,آهن منگنز روی,7.500000e+06,7.500000e+06,7500000.00,NaN,[کود اسپانیایی ریز مغذی سه گانه آهن روی منگنز ...,[7500000.0]
35,19-116,سولفات آهن,1.066333e+05,2.320000e+04,180000.00,6.758253e+04,"[سولفات آهن 17 درصد, سولفات آهن 20 درصد, سولفا...","[120000.0, 169000.0, 180000.0, 120000.0, 27600..."
36,19-117,کلات آهن,1.298500e+06,2.000000e+05,1956000.00,8.219025e+05,"[کلات آهن لایفر 6٪ اسپانیایی, کلات آهن, کود آه...","[200000.0, 1900000.0, 1138000.0, 1956000.0]"
37,19-120,کلات روی,2.966250e+05,1.625000e+05,650000.00,2.366127e+05,[کود کلاته کلسیم-بور-روی مایع کلبومکس فارمونتی...,"[162500.0, 164000.0, 210000.0, 650000.0]"
38,19-121,سولفات روی,1.647464e+06,1.392000e+05,13750000.00,4.018046e+06,"[سولفات روی پودری 34%, سولفات روی پودری 22 درص...","[430000.0, 640000.0, 620000.04, 245200.0, 4300..."
39,19-124,فسفات روی,1.116000e+05,1.116000e+05,111600.00,NaN,[کود دی آمونیوم فسفات 4 لیتری (فسفر بالا رویش 2)],[111600.0]
40,19-129,کلات بور,1.632500e+05,1.625000e+05,164000.00,1.060660e+03,[کود کلاته کلسیم-بور-روی مایع کلبومکس فارمونتی...,"[162500.0, 164000.0]"
41,19-132,سولفات مس,2.139667e+06,2.460000e+05,5926000.00,3.279061e+06,"[کات کبود (سولفات مس)5 کیلو گرم, کات کبود (سول...","[247000.0, 246000.0, 5926000.0]"
42,19-141,کلر,6.875000e+05,5.400000e+05,990000.00,2.083867e+05,[سم قارچ کش کوپراکسی کلراید اکسی کلرور مس پودر...,"[990000.0, 540000.0, 560000.0, 660000.0]"
43,19-143,میکرومیکس,3.770000e+05,9.300000e+04,850000.00,3.520691e+05,[میکرومیکس بازرگان کالا بسته بندی 1 لیتری یک غ...,"[850000.0, 125000.0, 93000.0, 440000.0]"
44,19-145,سیلیکات پتاسیم,2.946000e+05,1.470000e+05,500000.00,1.355168e+05,"[کود سیلیکات پتاسیم 2/5 لیتری آگروفر, سیلیکات ...","[147000.0, 350000.0, 500000.0, 236000.0, 24000..."
45,20-112,مرغی,5.961834e+04,6.800000e+03,158800.00,3.795275e+04,[کود مرغی مایع نیو داتیس آل (NEW DATIS ALL) حج...,"[65280.0, 78672.0, 104280.0, 120000.0, 120000...."
46,21-111,پلیت مرغی,5.900000e+04,9.100000e+03,158800.00,8.642934e+04,"[کود پلیت مرغی 25 کیلوگرمی, گابری گلدن(پلیت کو...","[9100.0, 158800.0, 9100.0]"
47,21-112,مرغی مایع,6.618500e+04,1.295000e+04,120000.00,3.241302e+04,[کود مرغی مایع نیو داتیس آل (NEW DATIS ALL) حج...,"[65280.0, 104280.0, 120000.0, 120000.0, 84250...."
48,21-113,ماهی,6.550000e+04,5.250000e+04,80000.00,1.350926e+04,[عصاره کود مرغ و ماهی غنی شده با هیومیک و فولو...,"[80000.0, 60000.0, 55000.0, 52500.0, 80000.0]"
49,21-115,کمپوست,1.444865e+04,4.882353e+02,45000.00,1.194283e+04,"[خاک ورمی کمپوست سایز متوسط 10 لیتری آقای خاک,...","[19960.0, nan, nan, nan, 18000.0, 6480.0, 2500..."
50,21-116,ورمی کمپوست,1.700393e+04,5.000000e+03,45000.00,1.398516e+04,"[خاک ورمی کمپوست سایز متوسط 10 لیتری آقای خاک,...","[19960.0, nan, nan, nan, 6480.0, 45000.0, 5000..."
51,21-117,کود سبز,1.530000e+05,5.400000e+04,230000.00,9.003888e+04,[کود اسید انفوریک مایع مگافرتیل ان اس 10 لیتری...,"[54000.0, 230000.0, 175000.0]"
52,21-118,اسید هیومیک,6.479957e+05,1.040000e+04,19320000.00,2.515547e+06,"[کود هیومیک اسید مایع هیومولایف 5 لیتر, کود هی...","[231000.0, 88176.0, 75504.0, 228360.0, 82280.0..."
53,21-119,اسید آمینه,6.790000e+06,9.700000e+05,18400000.00,1.005457e+07,"[اسید آمینه کیلیترین 1 لیتری - 1, کود مایع اسی...","[1000000.0, 970000.0, 18400000.0]"
54,21-120,فولیک اسید,4.397900e+05,4.397900e+05,439790.00,NaN,[گابری هیومیک مایع (اسید هیومیک + فولیک)(20لیت...,[439790.0]
55,21-121,گوگرد آلی,3.800000e+04,3.800000e+04,38000.00,0.000000e+00,"[گوگرد آلی گرانوله, گوگرد آلی گرانوله]","[38000.0, 38000.0]"
56,22-111,جلبک دریایی,1.064860e+06,1.776000e+05,2150000.00,6.659804e+05,"[کود جلبک دریایی سیفول, کود جلبک دریایی مایع ش...","[187000.0, 177600.0, 2150000.0, 1920000.0, 950..."
57,99-113,ضد شوری,2.665930e+05,6.240000e+04,610800.00,2.383079e+05,"[کود ضد شوری فورنوترینت (Anti Salt) 5 لیتر, کو...","[62400.0, 210672.0, 182500.0, 610800.0]"
58,99-115,اصلاح کننده خاک,6.912500e+05,1.825000e+05,1200000.00,7.194811e+05,[کود تقویتی اصلاح کننده خاک و ضد شوری پرک سویل...,"[182500.0, 1200000.0]"

In [246]:

# # Others to Dataframe
# for counter in range(len(npk_excluded_raw_source.iloc[:,4].tolist())):
#     name = npk_excluded_raw_source.iloc[:,4].tolist()[counter]
#     filtered = df[df['name'].str.contains(re.escape(name), na=False, case=False)]
#     if filtered.empty:
#         continue  # skip if no matches
    
#     row = {
#         "code": npk_excluded_raw_source.iloc[counter,2], 
#         "name": name,
#         "avg": filtered['price_per_kg'].median(), 
#         "min": filtered['price_per_kg'].min(),
#         "max": filtered['price_per_kg'].max(),
#         "std": filtered['price_per_kg'].std(),
#         "listOfNames": filtered['name'].tolist(),
#         "listOfPrices": filtered['price_per_kg'].tolist(),
#     }
#     rows.append(row)

# # Convert list of dicts directly to a DataFrame
# #npkExcludedResultRows = pd.DataFrame(rows)
# result_df = pd.DataFrame(rows)

# print(result_df)

In [247]:
result_df

,code,name,avg,min,max,std,listOfNames,listOfPrices
0,17-111,20 20 20,1.131000e+07,3.000000e+05,29000000.00,1.547221e+07,[کود سه 20 مایع تری پرو فارمونتی NPK 20 20 20+...,"[300000.0, 4630000.0, 29000000.0]"
1,17-113,10 52 10,1.798000e+07,3.960000e+06,32000000.00,1.982727e+07,"[کود NPK 10 52 10 کوالی مکس, کود 10 52 10 NPK ...","[32000000.0, 3960000.0]"
2,17-129,18 18 18,4.630000e+06,4.630000e+06,4630000.00,NaN,[کود NPK 18 18 18 باواریا],[4630000.0]
3,17-139,19 6 20,4.630000e+06,4.630000e+06,4630000.00,NaN,[کود NPK 19 6 20 باواریا],[4630000.0]
4,11-111,اوره,1.267000e+06,3.400000e+04,13000000.00,3.150216e+06,"[اوره سولفات, اوره با پوشش گوگردی, اوره با پوش...","[355000.0, 372000.16, 116000.0, 340000.0, 3400..."
5,11-115,سولفات آمونیوم,7.904583e+04,2.000000e+03,141999.94,4.307121e+04,"[سولفات آمونیوم پودری, سولفات آمونیوم ازبک, سو...","[141999.94, 98000.0, 106000.0, 111000.0, 11100..."
6,11-116,اوره با پوشش گوگردی,2.490000e+05,1.160000e+05,392000.00,1.537921e+05,"[اوره با پوشش گوگردی, اوره با پوشش گوگردی, اور...","[372000.16, 116000.0, 116000.0, 392000.0]"
7,11-119,فسفات آمونیوم,2.980273e+05,1.116000e+05,700000.00,1.698862e+05,"[فسفات آمونیوم, دی آمونیوم فسفات چینی, فسفات آ...","[181600.0, 470000.0, 181600.0, 700000.0, 11160..."
8,11-120,نیترات کلسیم,3.711364e+05,4.400000e+03,2730000.00,7.865832e+05,"[نیترات کلسیم, نیترات کلسیم, کود نیترات کلسیم ...","[190000.0, 190000.0, 111800.0, 150000.0, 92500..."
9,11-121,نیترات پتاسیم,1.018543e+06,2.000000e+05,3700000.00,1.264799e+06,"[نیترات پتاسیم, نیترات پتاسیم, نیترات پتاسیم و...","[1100000.16, 1300000.0, 273000.0, 258800.0, 29..."
10,12-111,اوره فسفات,3.212667e+06,1.750000e+05,13000000.00,4.968804e+06,[کود آلی اوره فسفات (NP) کیلیترین 1 لیتری - 20...,"[13000000.0, 191000.0, 3250000.0, 280000.0, 17..."
11,12-112,مونو فسفات پتاسیم,1.033489e+06,5.400000e+03,4130000.00,1.712340e+06,"[مونو پتاسیم فسفات, مونو پتاسیم فسفات, کود تقو...","[100000.0, 100000.0, 412500.0, 300000.0, 83500..."
12,12-114,فسفیت پتاسیم,1.000467e+06,7.800000e+05,1411000.00,2.455559e+05,"[کود فسفیت پتاسیم (فوس وید ) سوپر مکس 1 لیتر, ...","[897000.0, 1411000.0, 780000.0, 782800.0, 1160..."
13,12-121,سوپر فسفات ساده,1.221000e+05,6.840002e+04,152000.00,3.961867e+04,"[سوپر فسفات ساده, سوپر فسفات ساده, سوپر فسفات ...","[68400.02, 152000.0, 152000.0, 116000.0]"
14,12-122,مونو آمونیوم فسفات,2.819000e+05,1.800000e+05,399500.00,8.486784e+04,[کود مونو آمونیوم فسفات 0-61-12 فرمولایف 10 کی...,"[222000.0, 399500.0, 308000.0, 300000.0, 18000..."
15,12-124,فسفات گوگردی,1.176600e+05,1.700000e+04,170000.00,8.719729e+04,"[فسفات گوگردی, فسفات گوگردی, فسفات گوگردی]","[165980.0, 17000.0, 170000.0]"
16,13-111,سولفات پتاسیم,1.314641e+06,1.500000e+03,17000000.00,4.222760e+06,"[سولفات پتاسیم منیزیم 10/4, سولفات پتاسیم منیز...","[135960.0, 142000.0, 168000.0, 150000.0, 69200..."
17,13-113,مونو پتاسیم فسفات,1.033489e+06,5.400000e+03,4130000.00,1.712340e+06,"[مونو پتاسیم فسفات, مونو پتاسیم فسفات, کود تقو...","[100000.0, 100000.0, 412500.0, 300000.0, 83500..."
18,13-114,پتاسیم نیترات,1.018543e+06,2.000000e+05,3700000.00,1.264799e+06,"[نیترات پتاسیم, نیترات پتاسیم, نیترات پتاسیم و...","[1100000.16, 1300000.0, 273000.0, 258800.0, 29..."
19,13-115,پتاسیم منیزیم,1.389800e+05,1.359600e+05,142000.00,4.270925e+03,"[سولفات پتاسیم منیزیم 10/4, سولفات پتاسیم منیز...","[135960.0, 142000.0]"
20,13-117,پتاسه گرانوله,1.020000e+05,1.020000e+05,102000.00,0.000000e+00,"[پتاسه گرانوله30%, پتاسه گرانوله30%]","[102000.0, 102000.0]"
21,13-119,پتاسیم سیلیکات,2.946000e+05,1.470000e+05,500000.00,1.355168e+05,"[کود سیلیکات پتاسیم 2/5 لیتری آگروفر, سیلیکات ...","[147000.0, 350000.0, 500000.0, 236000.0, 24000..."
22,14-111,کلسیم نیترات,3.711364e+05,4.400000e+03,2730000.00,7.865832e+05,"[نیترات کلسیم, نیترات کلسیم, کود نیترات کلسیم ...","[190000.0, 190000.0, 111800.0, 150000.0, 92500..."
23,14-112,کلات کلسیم,1.632500e+05,1.625000e+05,164000.00,1.060660e+03,[کود کلاته کلسیم-بور-روی مایع کلبومکس فارمونتی...,"[162500.0, 164000.0]"
24,14-117,کلسیم منیزیم,4.550000e+05,1.575000e+05,1050000.00,5.152851e+05,"[کلسیم منیزیم, کلسیم منیزیم, کود کشاورزی کلسیم...","[157500.0, 157500.0, 1050000.0]"
25,15-111,سولفات منیزیم,8.047333e+04,2.320000e+04,157500.00,5.370865e+04,"[سولفات پتاسیم منیزیم 10/4, سولفات منیزیم, سول...","[135960.0, 63000.0, 157500.0, 142000.0, 30000...."
26,15-112,نیترات منیزیم,2.125000e+06,2.125000e+06,2125000.00,NaN,[کود نیترات منیزیم کوالی مکس],[2125000.0]
27,15-115,پتاس منیزیم,1.389800e+05,1.359600e+05,142000.00,4.270925e+03,"[سولفات پتاسیم منیزیم 10/4, سولفات پتاسیم منیز...","[135960.0, 142000.0]"
28,16-111,گوگرد پودری,1.170667e+05,2.200000e+03,273000.00,1.399929e+05,[نیترات پتاسیم و کربن فعال و گوگرد پودری فلات ...,"[273000.0, 76000.0, 2200.0]"
29,16-112,گوگرد گرانوله,6.450000e+04,3.800000e+04,91000.00,3.059956e+04,"[گوگرد آلی گرانوله, گوگرد گرانوله بنتونیت دار ...","[38000.0, 91000.0, 91000.0, 38000.0]"
30,16-114,گوگرد مایع,1.776782e+05,1.025000e+04,550000.00,1.678102e+05,"[گوگرد مایع پتاسه, گوگرد مایع, گوگرد مایع پتاس...","[550000.0, 350000.0, 550000.0, 350000.0, 13000..."
31,16-115,گوگرد بنتونیت دار,1.006667e+05,9.100000e+04,120000.00,1.674316e+04,"[گوگرد بنتونیت دار, گوگرد گرانوله بنتونیت دار ...","[120000.0, 91000.0, 91000.0]"
32,18-113,چالکود,9.174667e+04,2.244000e+04,134000.00,6.050058e+04,[چالکود فرموکمپلکس همراه با گوگرد و عناصر ریزم...,"[118800.0, 22440.0, 134000.0]"
33,19-112,سولفات منگنز,7.313600e+05,7.000000e+03,1837000.00,7.344904e+05,"[سولفات منگنز چینی, سولفات منگنز چینی, کود سول...","[850000.0, 850000.0, 112800.0, 7000.0, 1837000.0]"
34,19-114,آهن منگنز روی,7.500000e+06,7.500000e+06,7500000.00,NaN,[کود اسپانیایی ریز مغذی سه گانه آهن روی منگنز ...,[7500000.0]
35,19-116,سولفات آهن,1.066333e+05,2.320000e+04,180000.00,6.758253e+04,"[سولفات آهن 17 درصد, سولفات آهن 20 درصد, سولفا...","[120000.0, 169000.0, 180000.0, 120000.0, 27600..."
36,19-117,کلات آهن,1.298500e+06,2.000000e+05,1956000.00,8.219025e+05,"[کلات آهن لایفر 6٪ اسپانیایی, کلات آهن, کود آه...","[200000.0, 1900000.0, 1138000.0, 1956000.0]"
37,19-120,کلات روی,2.966250e+05,1.625000e+05,650000.00,2.366127e+05,[کود کلاته کلسیم-بور-روی مایع کلبومکس فارمونتی...,"[162500.0, 164000.0, 210000.0, 650000.0]"
38,19-121,سولفات روی,1.647464e+06,1.392000e+05,13750000.00,4.018046e+06,"[سولفات روی پودری 34%, سولفات روی پودری 22 درص...","[430000.0, 640000.0, 620000.04, 245200.0, 4300..."
39,19-124,فسفات روی,1.116000e+05,1.116000e+05,111600.00,NaN,[کود دی آمونیوم فسفات 4 لیتری (فسفر بالا رویش 2)],[111600.0]
40,19-129,کلات بور,1.632500e+05,1.625000e+05,164000.00,1.060660e+03,[کود کلاته کلسیم-بور-روی مایع کلبومکس فارمونتی...,"[162500.0, 164000.0]"
41,19-132,سولفات مس,2.139667e+06,2.460000e+05,5926000.00,3.279061e+06,"[کات کبود (سولفات مس)5 کیلو گرم, کات کبود (سول...","[247000.0, 246000.0, 5926000.0]"
42,19-141,کلر,6.875000e+05,5.400000e+05,990000.00,2.083867e+05,[سم قارچ کش کوپراکسی کلراید اکسی کلرور مس پودر...,"[990000.0, 540000.0, 560000.0, 660000.0]"
43,19-143,میکرومیکس,3.770000e+05,9.300000e+04,850000.00,3.520691e+05,[میکرومیکس بازرگان کالا بسته بندی 1 لیتری یک غ...,"[850000.0, 125000.0, 93000.0, 440000.0]"
44,19-145,سیلیکات پتاسیم,2.946000e+05,1.470000e+05,500000.00,1.355168e+05,"[کود سیلیکات پتاسیم 2/5 لیتری آگروفر, سیلیکات ...","[147000.0, 350000.0, 500000.0, 236000.0, 24000..."
45,20-112,مرغی,5.961834e+04,6.800000e+03,158800.00,3.795275e+04,[کود مرغی مایع نیو داتیس آل (NEW DATIS ALL) حج...,"[65280.0, 78672.0, 104280.0, 120000.0, 120000...."
46,21-111,پلیت مرغی,5.900000e+04,9.100000e+03,158800.00,8.642934e+04,"[کود پلیت مرغی 25 کیلوگرمی, گابری گلدن(پلیت کو...","[9100.0, 158800.0, 9100.0]"
47,21-112,مرغی مایع,6.618500e+04,1.295000e+04,120000.00,3.241302e+04,[کود مرغی مایع نیو داتیس آل (NEW DATIS ALL) حج...,"[65280.0, 104280.0, 120000.0, 120000.0, 84250...."
48,21-113,ماهی,6.550000e+04,5.250000e+04,80000.00,1.350926e+04,[عصاره کود مرغ و ماهی غنی شده با هیومیک و فولو...,"[80000.0, 60000.0, 55000.0, 52500.0, 80000.0]"
49,21-115,کمپوست,1.444865e+04,4.882353e+02,45000.00,1.194283e+04,"[خاک ورمی کمپوست سایز متوسط 10 لیتری آقای خاک,...","[19960.0, nan, nan, nan, 18000.0, 6480.0, 2500..."
50,21-116,ورمی کمپوست,1.700393e+04,5.000000e+03,45000.00,1.398516e+04,"[خاک ورمی کمپوست سایز متوسط 10 لیتری آقای خاک,...","[19960.0, nan, nan, nan, 6480.0, 45000.0, 5000..."
51,21-117,کود سبز,1.530000e+05,5.400000e+04,230000.00,9.003888e+04,[کود اسید انفوریک مایع مگافرتیل ان اس 10 لیتری...,"[54000.0, 230000.0, 175000.0]"
52,21-118,اسید هیومیک,6.479957e+05,1.040000e+04,19320000.00,2.515547e+06,"[کود هیومیک اسید مایع هیومولایف 5 لیتر, کود هی...","[231000.0, 88176.0, 75504.0, 228360.0, 82280.0..."
53,21-119,اسید آمینه,6.790000e+06,9.700000e+05,18400000.00,1.005457e+07,"[اسید آمینه کیلیترین 1 لیتری - 1, کود مایع اسی...","[1000000.0, 970000.0, 18400000.0]"
54,21-120,فولیک اسید,4.397900e+05,4.397900e+05,439790.00,NaN,[گابری هیومیک مایع (اسید هیومیک + فولیک)(20لیت...,[439790.0]
55,21-121,گوگرد آلی,3.800000e+04,3.800000e+04,38000.00,0.000000e+00,"[گوگرد آلی گرانوله, گوگرد آلی گرانوله]","[38000.0, 38000.0]"
56,22-111,جلبک دریایی,1.064860e+06,1.776000e+05,2150000.00,6.659804e+05,"[کود جلبک دریایی سیفول, کود جلبک دریایی مایع ش...","[187000.0, 177600.0, 2150000.0, 1920000.0, 950..."
57,99-113,ضد شوری,2.665930e+05,6.240000e+04,610800.00,2.383079e+05,"[کود ضد شوری فورنوترینت (Anti Salt) 5 لیتر, کو...","[62400.0, 210672.0, 182500.0, 610800.0]"
58,99-115,اصلاح کننده خاک,6.912500e+05,1.825000e+05,1200000.00,7.194811e+05,[کود تقویتی اصلاح کننده خاک و ضد شوری پرک سویل...,"[182500.0, 1200000.0]"

**Correct EXCEPTIONS**

In [248]:
result_df

,code,name,avg,min,max,std,listOfNames,listOfPrices
0,17-111,20 20 20,1.131000e+07,3.000000e+05,29000000.00,1.547221e+07,[کود سه 20 مایع تری پرو فارمونتی NPK 20 20 20+...,"[300000.0, 4630000.0, 29000000.0]"
1,17-113,10 52 10,1.798000e+07,3.960000e+06,32000000.00,1.982727e+07,"[کود NPK 10 52 10 کوالی مکس, کود 10 52 10 NPK ...","[32000000.0, 3960000.0]"
2,17-129,18 18 18,4.630000e+06,4.630000e+06,4630000.00,NaN,[کود NPK 18 18 18 باواریا],[4630000.0]
3,17-139,19 6 20,4.630000e+06,4.630000e+06,4630000.00,NaN,[کود NPK 19 6 20 باواریا],[4630000.0]
4,11-111,اوره,1.267000e+06,3.400000e+04,13000000.00,3.150216e+06,"[اوره سولفات, اوره با پوشش گوگردی, اوره با پوش...","[355000.0, 372000.16, 116000.0, 340000.0, 3400..."
5,11-115,سولفات آمونیوم,7.904583e+04,2.000000e+03,141999.94,4.307121e+04,"[سولفات آمونیوم پودری, سولفات آمونیوم ازبک, سو...","[141999.94, 98000.0, 106000.0, 111000.0, 11100..."
6,11-116,اوره با پوشش گوگردی,2.490000e+05,1.160000e+05,392000.00,1.537921e+05,"[اوره با پوشش گوگردی, اوره با پوشش گوگردی, اور...","[372000.16, 116000.0, 116000.0, 392000.0]"
7,11-119,فسفات آمونیوم,2.980273e+05,1.116000e+05,700000.00,1.698862e+05,"[فسفات آمونیوم, دی آمونیوم فسفات چینی, فسفات آ...","[181600.0, 470000.0, 181600.0, 700000.0, 11160..."
8,11-120,نیترات کلسیم,3.711364e+05,4.400000e+03,2730000.00,7.865832e+05,"[نیترات کلسیم, نیترات کلسیم, کود نیترات کلسیم ...","[190000.0, 190000.0, 111800.0, 150000.0, 92500..."
9,11-121,نیترات پتاسیم,1.018543e+06,2.000000e+05,3700000.00,1.264799e+06,"[نیترات پتاسیم, نیترات پتاسیم, نیترات پتاسیم و...","[1100000.16, 1300000.0, 273000.0, 258800.0, 29..."
10,12-111,اوره فسفات,3.212667e+06,1.750000e+05,13000000.00,4.968804e+06,[کود آلی اوره فسفات (NP) کیلیترین 1 لیتری - 20...,"[13000000.0, 191000.0, 3250000.0, 280000.0, 17..."
11,12-112,مونو فسفات پتاسیم,1.033489e+06,5.400000e+03,4130000.00,1.712340e+06,"[مونو پتاسیم فسفات, مونو پتاسیم فسفات, کود تقو...","[100000.0, 100000.0, 412500.0, 300000.0, 83500..."
12,12-114,فسفیت پتاسیم,1.000467e+06,7.800000e+05,1411000.00,2.455559e+05,"[کود فسفیت پتاسیم (فوس وید ) سوپر مکس 1 لیتر, ...","[897000.0, 1411000.0, 780000.0, 782800.0, 1160..."
13,12-121,سوپر فسفات ساده,1.221000e+05,6.840002e+04,152000.00,3.961867e+04,"[سوپر فسفات ساده, سوپر فسفات ساده, سوپر فسفات ...","[68400.02, 152000.0, 152000.0, 116000.0]"
14,12-122,مونو آمونیوم فسفات,2.819000e+05,1.800000e+05,399500.00,8.486784e+04,[کود مونو آمونیوم فسفات 0-61-12 فرمولایف 10 کی...,"[222000.0, 399500.0, 308000.0, 300000.0, 18000..."
15,12-124,فسفات گوگردی,1.176600e+05,1.700000e+04,170000.00,8.719729e+04,"[فسفات گوگردی, فسفات گوگردی, فسفات گوگردی]","[165980.0, 17000.0, 170000.0]"
16,13-111,سولفات پتاسیم,1.314641e+06,1.500000e+03,17000000.00,4.222760e+06,"[سولفات پتاسیم منیزیم 10/4, سولفات پتاسیم منیز...","[135960.0, 142000.0, 168000.0, 150000.0, 69200..."
17,13-113,مونو پتاسیم فسفات,1.033489e+06,5.400000e+03,4130000.00,1.712340e+06,"[مونو پتاسیم فسفات, مونو پتاسیم فسفات, کود تقو...","[100000.0, 100000.0, 412500.0, 300000.0, 83500..."
18,13-114,پتاسیم نیترات,1.018543e+06,2.000000e+05,3700000.00,1.264799e+06,"[نیترات پتاسیم, نیترات پتاسیم, نیترات پتاسیم و...","[1100000.16, 1300000.0, 273000.0, 258800.0, 29..."
19,13-115,پتاسیم منیزیم,1.389800e+05,1.359600e+05,142000.00,4.270925e+03,"[سولفات پتاسیم منیزیم 10/4, سولفات پتاسیم منیز...","[135960.0, 142000.0]"
20,13-117,پتاسه گرانوله,1.020000e+05,1.020000e+05,102000.00,0.000000e+00,"[پتاسه گرانوله30%, پتاسه گرانوله30%]","[102000.0, 102000.0]"
21,13-119,پتاسیم سیلیکات,2.946000e+05,1.470000e+05,500000.00,1.355168e+05,"[کود سیلیکات پتاسیم 2/5 لیتری آگروفر, سیلیکات ...","[147000.0, 350000.0, 500000.0, 236000.0, 24000..."
22,14-111,کلسیم نیترات,3.711364e+05,4.400000e+03,2730000.00,7.865832e+05,"[نیترات کلسیم, نیترات کلسیم, کود نیترات کلسیم ...","[190000.0, 190000.0, 111800.0, 150000.0, 92500..."
23,14-112,کلات کلسیم,1.632500e+05,1.625000e+05,164000.00,1.060660e+03,[کود کلاته کلسیم-بور-روی مایع کلبومکس فارمونتی...,"[162500.0, 164000.0]"
24,14-117,کلسیم منیزیم,4.550000e+05,1.575000e+05,1050000.00,5.152851e+05,"[کلسیم منیزیم, کلسیم منیزیم, کود کشاورزی کلسیم...","[157500.0, 157500.0, 1050000.0]"
25,15-111,سولفات منیزیم,8.047333e+04,2.320000e+04,157500.00,5.370865e+04,"[سولفات پتاسیم منیزیم 10/4, سولفات منیزیم, سول...","[135960.0, 63000.0, 157500.0, 142000.0, 30000...."
26,15-112,نیترات منیزیم,2.125000e+06,2.125000e+06,2125000.00,NaN,[کود نیترات منیزیم کوالی مکس],[2125000.0]
27,15-115,پتاس منیزیم,1.389800e+05,1.359600e+05,142000.00,4.270925e+03,"[سولفات پتاسیم منیزیم 10/4, سولفات پتاسیم منیز...","[135960.0, 142000.0]"
28,16-111,گوگرد پودری,1.170667e+05,2.200000e+03,273000.00,1.399929e+05,[نیترات پتاسیم و کربن فعال و گوگرد پودری فلات ...,"[273000.0, 76000.0, 2200.0]"
29,16-112,گوگرد گرانوله,6.450000e+04,3.800000e+04,91000.00,3.059956e+04,"[گوگرد آلی گرانوله, گوگرد گرانوله بنتونیت دار ...","[38000.0, 91000.0, 91000.0, 38000.0]"
30,16-114,گوگرد مایع,1.776782e+05,1.025000e+04,550000.00,1.678102e+05,"[گوگرد مایع پتاسه, گوگرد مایع, گوگرد مایع پتاس...","[550000.0, 350000.0, 550000.0, 350000.0, 13000..."
31,16-115,گوگرد بنتونیت دار,1.006667e+05,9.100000e+04,120000.00,1.674316e+04,"[گوگرد بنتونیت دار, گوگرد گرانوله بنتونیت دار ...","[120000.0, 91000.0, 91000.0]"
32,18-113,چالکود,9.174667e+04,2.244000e+04,134000.00,6.050058e+04,[چالکود فرموکمپلکس همراه با گوگرد و عناصر ریزم...,"[118800.0, 22440.0, 134000.0]"
33,19-112,سولفات منگنز,7.313600e+05,7.000000e+03,1837000.00,7.344904e+05,"[سولفات منگنز چینی, سولفات منگنز چینی, کود سول...","[850000.0, 850000.0, 112800.0, 7000.0, 1837000.0]"
34,19-114,آهن منگنز روی,7.500000e+06,7.500000e+06,7500000.00,NaN,[کود اسپانیایی ریز مغذی سه گانه آهن روی منگنز ...,[7500000.0]
35,19-116,سولفات آهن,1.066333e+05,2.320000e+04,180000.00,6.758253e+04,"[سولفات آهن 17 درصد, سولفات آهن 20 درصد, سولفا...","[120000.0, 169000.0, 180000.0, 120000.0, 27600..."
36,19-117,کلات آهن,1.298500e+06,2.000000e+05,1956000.00,8.219025e+05,"[کلات آهن لایفر 6٪ اسپانیایی, کلات آهن, کود آه...","[200000.0, 1900000.0, 1138000.0, 1956000.0]"
37,19-120,کلات روی,2.966250e+05,1.625000e+05,650000.00,2.366127e+05,[کود کلاته کلسیم-بور-روی مایع کلبومکس فارمونتی...,"[162500.0, 164000.0, 210000.0, 650000.0]"
38,19-121,سولفات روی,1.647464e+06,1.392000e+05,13750000.00,4.018046e+06,"[سولفات روی پودری 34%, سولفات روی پودری 22 درص...","[430000.0, 640000.0, 620000.04, 245200.0, 4300..."
39,19-124,فسفات روی,1.116000e+05,1.116000e+05,111600.00,NaN,[کود دی آمونیوم فسفات 4 لیتری (فسفر بالا رویش 2)],[111600.0]
40,19-129,کلات بور,1.632500e+05,1.625000e+05,164000.00,1.060660e+03,[کود کلاته کلسیم-بور-روی مایع کلبومکس فارمونتی...,"[162500.0, 164000.0]"
41,19-132,سولفات مس,2.139667e+06,2.460000e+05,5926000.00,3.279061e+06,"[کات کبود (سولفات مس)5 کیلو گرم, کات کبود (سول...","[247000.0, 246000.0, 5926000.0]"
42,19-141,کلر,6.875000e+05,5.400000e+05,990000.00,2.083867e+05,[سم قارچ کش کوپراکسی کلراید اکسی کلرور مس پودر...,"[990000.0, 540000.0, 560000.0, 660000.0]"
43,19-143,میکرومیکس,3.770000e+05,9.300000e+04,850000.00,3.520691e+05,[میکرومیکس بازرگان کالا بسته بندی 1 لیتری یک غ...,"[850000.0, 125000.0, 93000.0, 440000.0]"
44,19-145,سیلیکات پتاسیم,2.946000e+05,1.470000e+05,500000.00,1.355168e+05,"[کود سیلیکات پتاسیم 2/5 لیتری آگروفر, سیلیکات ...","[147000.0, 350000.0, 500000.0, 236000.0, 24000..."
45,20-112,مرغی,5.961834e+04,6.800000e+03,158800.00,3.795275e+04,[کود مرغی مایع نیو داتیس آل (NEW DATIS ALL) حج...,"[65280.0, 78672.0, 104280.0, 120000.0, 120000...."
46,21-111,پلیت مرغی,5.900000e+04,9.100000e+03,158800.00,8.642934e+04,"[کود پلیت مرغی 25 کیلوگرمی, گابری گلدن(پلیت کو...","[9100.0, 158800.0, 9100.0]"
47,21-112,مرغی مایع,6.618500e+04,1.295000e+04,120000.00,3.241302e+04,[کود مرغی مایع نیو داتیس آل (NEW DATIS ALL) حج...,"[65280.0, 104280.0, 120000.0, 120000.0, 84250...."
48,21-113,ماهی,6.550000e+04,5.250000e+04,80000.00,1.350926e+04,[عصاره کود مرغ و ماهی غنی شده با هیومیک و فولو...,"[80000.0, 60000.0, 55000.0, 52500.0, 80000.0]"
49,21-115,کمپوست,1.444865e+04,4.882353e+02,45000.00,1.194283e+04,"[خاک ورمی کمپوست سایز متوسط 10 لیتری آقای خاک,...","[19960.0, nan, nan, nan, 18000.0, 6480.0, 2500..."
50,21-116,ورمی کمپوست,1.700393e+04,5.000000e+03,45000.00,1.398516e+04,"[خاک ورمی کمپوست سایز متوسط 10 لیتری آقای خاک,...","[19960.0, nan, nan, nan, 6480.0, 45000.0, 5000..."
51,21-117,کود سبز,1.530000e+05,5.400000e+04,230000.00,9.003888e+04,[کود اسید انفوریک مایع مگافرتیل ان اس 10 لیتری...,"[54000.0, 230000.0, 175000.0]"
52,21-118,اسید هیومیک,6.479957e+05,1.040000e+04,19320000.00,2.515547e+06,"[کود هیومیک اسید مایع هیومولایف 5 لیتر, کود هی...","[231000.0, 88176.0, 75504.0, 228360.0, 82280.0..."
53,21-119,اسید آمینه,6.790000e+06,9.700000e+05,18400000.00,1.005457e+07,"[اسید آمینه کیلیترین 1 لیتری - 1, کود مایع اسی...","[1000000.0, 970000.0, 18400000.0]"
54,21-120,فولیک اسید,4.397900e+05,4.397900e+05,439790.00,NaN,[گابری هیومیک مایع (اسید هیومیک + فولیک)(20لیت...,[439790.0]
55,21-121,گوگرد آلی,3.800000e+04,3.800000e+04,38000.00,0.000000e+00,"[گوگرد آلی گرانوله, گوگرد آلی گرانوله]","[38000.0, 38000.0]"
56,22-111,جلبک دریایی,1.064860e+06,1.776000e+05,2150000.00,6.659804e+05,"[کود جلبک دریایی سیفول, کود جلبک دریایی مایع ش...","[187000.0, 177600.0, 2150000.0, 1920000.0, 950..."
57,99-113,ضد شوری,2.665930e+05,6.240000e+04,610800.00,2.383079e+05,"[کود ضد شوری فورنوترینت (Anti Salt) 5 لیتر, کو...","[62400.0, 210672.0, 182500.0, 610800.0]"
58,99-115,اصلاح کننده خاک,6.912500e+05,1.825000e+05,1200000.00,7.194811e+05,[کود تقویتی اصلاح کننده خاک و ضد شوری پرک سویل...,"[182500.0, 1200000.0]"

In [249]:
result_df.iloc[0,7]

[300000.0, 4630000.0, 29000000.0]

In [250]:
# Get the lists from the first row
names = result_df.iloc[4, 6]  # assuming this is already a list
prices = result_df.iloc[4, 7]  # assuming this is already a list

# Make new filtered lists
correctedNamesList = []
correctedPriceList = []
irrevelent_keywords = ["سولفات", "گوگردی", "فسفات"]


for name, price in zip(names, prices):
    if not any(keyword in name for keyword in irrevelent_keywords):
        correctedNamesList.append(name)
        correctedPriceList.append(price)

# Save them back
result_df.at[4, "listOfNames"] = correctedNamesList
result_df.at[4, "listOfPrices"] = correctedPriceList

In [251]:
result_df

,code,name,avg,min,max,std,listOfNames,listOfPrices
0,17-111,20 20 20,1.131000e+07,3.000000e+05,29000000.00,1.547221e+07,[کود سه 20 مایع تری پرو فارمونتی NPK 20 20 20+...,"[300000.0, 4630000.0, 29000000.0]"
1,17-113,10 52 10,1.798000e+07,3.960000e+06,32000000.00,1.982727e+07,"[کود NPK 10 52 10 کوالی مکس, کود 10 52 10 NPK ...","[32000000.0, 3960000.0]"
2,17-129,18 18 18,4.630000e+06,4.630000e+06,4630000.00,NaN,[کود NPK 18 18 18 باواریا],[4630000.0]
3,17-139,19 6 20,4.630000e+06,4.630000e+06,4630000.00,NaN,[کود NPK 19 6 20 باواریا],[4630000.0]
4,11-111,اوره,1.267000e+06,3.400000e+04,13000000.00,3.150216e+06,"[قیمت کود شیمیایی یا اوره 2 کیلویی, کود ترن 46...","[70000.0, 68000.0, 45000.0]"
5,11-115,سولفات آمونیوم,7.904583e+04,2.000000e+03,141999.94,4.307121e+04,"[سولفات آمونیوم پودری, سولفات آمونیوم ازبک, سو...","[141999.94, 98000.0, 106000.0, 111000.0, 11100..."
6,11-116,اوره با پوشش گوگردی,2.490000e+05,1.160000e+05,392000.00,1.537921e+05,"[اوره با پوشش گوگردی, اوره با پوشش گوگردی, اور...","[372000.16, 116000.0, 116000.0, 392000.0]"
7,11-119,فسفات آمونیوم,2.980273e+05,1.116000e+05,700000.00,1.698862e+05,"[فسفات آمونیوم, دی آمونیوم فسفات چینی, فسفات آ...","[181600.0, 470000.0, 181600.0, 700000.0, 11160..."
8,11-120,نیترات کلسیم,3.711364e+05,4.400000e+03,2730000.00,7.865832e+05,"[نیترات کلسیم, نیترات کلسیم, کود نیترات کلسیم ...","[190000.0, 190000.0, 111800.0, 150000.0, 92500..."
9,11-121,نیترات پتاسیم,1.018543e+06,2.000000e+05,3700000.00,1.264799e+06,"[نیترات پتاسیم, نیترات پتاسیم, نیترات پتاسیم و...","[1100000.16, 1300000.0, 273000.0, 258800.0, 29..."
10,12-111,اوره فسفات,3.212667e+06,1.750000e+05,13000000.00,4.968804e+06,[کود آلی اوره فسفات (NP) کیلیترین 1 لیتری - 20...,"[13000000.0, 191000.0, 3250000.0, 280000.0, 17..."
11,12-112,مونو فسفات پتاسیم,1.033489e+06,5.400000e+03,4130000.00,1.712340e+06,"[مونو پتاسیم فسفات, مونو پتاسیم فسفات, کود تقو...","[100000.0, 100000.0, 412500.0, 300000.0, 83500..."
12,12-114,فسفیت پتاسیم,1.000467e+06,7.800000e+05,1411000.00,2.455559e+05,"[کود فسفیت پتاسیم (فوس وید ) سوپر مکس 1 لیتر, ...","[897000.0, 1411000.0, 780000.0, 782800.0, 1160..."
13,12-121,سوپر فسفات ساده,1.221000e+05,6.840002e+04,152000.00,3.961867e+04,"[سوپر فسفات ساده, سوپر فسفات ساده, سوپر فسفات ...","[68400.02, 152000.0, 152000.0, 116000.0]"
14,12-122,مونو آمونیوم فسفات,2.819000e+05,1.800000e+05,399500.00,8.486784e+04,[کود مونو آمونیوم فسفات 0-61-12 فرمولایف 10 کی...,"[222000.0, 399500.0, 308000.0, 300000.0, 18000..."
15,12-124,فسفات گوگردی,1.176600e+05,1.700000e+04,170000.00,8.719729e+04,"[فسفات گوگردی, فسفات گوگردی, فسفات گوگردی]","[165980.0, 17000.0, 170000.0]"
16,13-111,سولفات پتاسیم,1.314641e+06,1.500000e+03,17000000.00,4.222760e+06,"[سولفات پتاسیم منیزیم 10/4, سولفات پتاسیم منیز...","[135960.0, 142000.0, 168000.0, 150000.0, 69200..."
17,13-113,مونو پتاسیم فسفات,1.033489e+06,5.400000e+03,4130000.00,1.712340e+06,"[مونو پتاسیم فسفات, مونو پتاسیم فسفات, کود تقو...","[100000.0, 100000.0, 412500.0, 300000.0, 83500..."
18,13-114,پتاسیم نیترات,1.018543e+06,2.000000e+05,3700000.00,1.264799e+06,"[نیترات پتاسیم, نیترات پتاسیم, نیترات پتاسیم و...","[1100000.16, 1300000.0, 273000.0, 258800.0, 29..."
19,13-115,پتاسیم منیزیم,1.389800e+05,1.359600e+05,142000.00,4.270925e+03,"[سولفات پتاسیم منیزیم 10/4, سولفات پتاسیم منیز...","[135960.0, 142000.0]"
20,13-117,پتاسه گرانوله,1.020000e+05,1.020000e+05,102000.00,0.000000e+00,"[پتاسه گرانوله30%, پتاسه گرانوله30%]","[102000.0, 102000.0]"
21,13-119,پتاسیم سیلیکات,2.946000e+05,1.470000e+05,500000.00,1.355168e+05,"[کود سیلیکات پتاسیم 2/5 لیتری آگروفر, سیلیکات ...","[147000.0, 350000.0, 500000.0, 236000.0, 24000..."
22,14-111,کلسیم نیترات,3.711364e+05,4.400000e+03,2730000.00,7.865832e+05,"[نیترات کلسیم, نیترات کلسیم, کود نیترات کلسیم ...","[190000.0, 190000.0, 111800.0, 150000.0, 92500..."
23,14-112,کلات کلسیم,1.632500e+05,1.625000e+05,164000.00,1.060660e+03,[کود کلاته کلسیم-بور-روی مایع کلبومکس فارمونتی...,"[162500.0, 164000.0]"
24,14-117,کلسیم منیزیم,4.550000e+05,1.575000e+05,1050000.00,5.152851e+05,"[کلسیم منیزیم, کلسیم منیزیم, کود کشاورزی کلسیم...","[157500.0, 157500.0, 1050000.0]"
25,15-111,سولفات منیزیم,8.047333e+04,2.320000e+04,157500.00,5.370865e+04,"[سولفات پتاسیم منیزیم 10/4, سولفات منیزیم, سول...","[135960.0, 63000.0, 157500.0, 142000.0, 30000...."
26,15-112,نیترات منیزیم,2.125000e+06,2.125000e+06,2125000.00,NaN,[کود نیترات منیزیم کوالی مکس],[2125000.0]
27,15-115,پتاس منیزیم,1.389800e+05,1.359600e+05,142000.00,4.270925e+03,"[سولفات پتاسیم منیزیم 10/4, سولفات پتاسیم منیز...","[135960.0, 142000.0]"
28,16-111,گوگرد پودری,1.170667e+05,2.200000e+03,273000.00,1.399929e+05,[نیترات پتاسیم و کربن فعال و گوگرد پودری فلات ...,"[273000.0, 76000.0, 2200.0]"
29,16-112,گوگرد گرانوله,6.450000e+04,3.800000e+04,91000.00,3.059956e+04,"[گوگرد آلی گرانوله, گوگرد گرانوله بنتونیت دار ...","[38000.0, 91000.0, 91000.0, 38000.0]"
30,16-114,گوگرد مایع,1.776782e+05,1.025000e+04,550000.00,1.678102e+05,"[گوگرد مایع پتاسه, گوگرد مایع, گوگرد مایع پتاس...","[550000.0, 350000.0, 550000.0, 350000.0, 13000..."
31,16-115,گوگرد بنتونیت دار,1.006667e+05,9.100000e+04,120000.00,1.674316e+04,"[گوگرد بنتونیت دار, گوگرد گرانوله بنتونیت دار ...","[120000.0, 91000.0, 91000.0]"
32,18-113,چالکود,9.174667e+04,2.244000e+04,134000.00,6.050058e+04,[چالکود فرموکمپلکس همراه با گوگرد و عناصر ریزم...,"[118800.0, 22440.0, 134000.0]"
33,19-112,سولفات منگنز,7.313600e+05,7.000000e+03,1837000.00,7.344904e+05,"[سولفات منگنز چینی, سولفات منگنز چینی, کود سول...","[850000.0, 850000.0, 112800.0, 7000.0, 1837000.0]"
34,19-114,آهن منگنز روی,7.500000e+06,7.500000e+06,7500000.00,NaN,[کود اسپانیایی ریز مغذی سه گانه آهن روی منگنز ...,[7500000.0]
35,19-116,سولفات آهن,1.066333e+05,2.320000e+04,180000.00,6.758253e+04,"[سولفات آهن 17 درصد, سولفات آهن 20 درصد, سولفا...","[120000.0, 169000.0, 180000.0, 120000.0, 27600..."
36,19-117,کلات آهن,1.298500e+06,2.000000e+05,1956000.00,8.219025e+05,"[کلات آهن لایفر 6٪ اسپانیایی, کلات آهن, کود آه...","[200000.0, 1900000.0, 1138000.0, 1956000.0]"
37,19-120,کلات روی,2.966250e+05,1.625000e+05,650000.00,2.366127e+05,[کود کلاته کلسیم-بور-روی مایع کلبومکس فارمونتی...,"[162500.0, 164000.0, 210000.0, 650000.0]"
38,19-121,سولفات روی,1.647464e+06,1.392000e+05,13750000.00,4.018046e+06,"[سولفات روی پودری 34%, سولفات روی پودری 22 درص...","[430000.0, 640000.0, 620000.04, 245200.0, 4300..."
39,19-124,فسفات روی,1.116000e+05,1.116000e+05,111600.00,NaN,[کود دی آمونیوم فسفات 4 لیتری (فسفر بالا رویش 2)],[111600.0]
40,19-129,کلات بور,1.632500e+05,1.625000e+05,164000.00,1.060660e+03,[کود کلاته کلسیم-بور-روی مایع کلبومکس فارمونتی...,"[162500.0, 164000.0]"
41,19-132,سولفات مس,2.139667e+06,2.460000e+05,5926000.00,3.279061e+06,"[کات کبود (سولفات مس)5 کیلو گرم, کات کبود (سول...","[247000.0, 246000.0, 5926000.0]"
42,19-141,کلر,6.875000e+05,5.400000e+05,990000.00,2.083867e+05,[سم قارچ کش کوپراکسی کلراید اکسی کلرور مس پودر...,"[990000.0, 540000.0, 560000.0, 660000.0]"
43,19-143,میکرومیکس,3.770000e+05,9.300000e+04,850000.00,3.520691e+05,[میکرومیکس بازرگان کالا بسته بندی 1 لیتری یک غ...,"[850000.0, 125000.0, 93000.0, 440000.0]"
44,19-145,سیلیکات پتاسیم,2.946000e+05,1.470000e+05,500000.00,1.355168e+05,"[کود سیلیکات پتاسیم 2/5 لیتری آگروفر, سیلیکات ...","[147000.0, 350000.0, 500000.0, 236000.0, 24000..."
45,20-112,مرغی,5.961834e+04,6.800000e+03,158800.00,3.795275e+04,[کود مرغی مایع نیو داتیس آل (NEW DATIS ALL) حج...,"[65280.0, 78672.0, 104280.0, 120000.0, 120000...."
46,21-111,پلیت مرغی,5.900000e+04,9.100000e+03,158800.00,8.642934e+04,"[کود پلیت مرغی 25 کیلوگرمی, گابری گلدن(پلیت کو...","[9100.0, 158800.0, 9100.0]"
47,21-112,مرغی مایع,6.618500e+04,1.295000e+04,120000.00,3.241302e+04,[کود مرغی مایع نیو داتیس آل (NEW DATIS ALL) حج...,"[65280.0, 104280.0, 120000.0, 120000.0, 84250...."
48,21-113,ماهی,6.550000e+04,5.250000e+04,80000.00,1.350926e+04,[عصاره کود مرغ و ماهی غنی شده با هیومیک و فولو...,"[80000.0, 60000.0, 55000.0, 52500.0, 80000.0]"
49,21-115,کمپوست,1.444865e+04,4.882353e+02,45000.00,1.194283e+04,"[خاک ورمی کمپوست سایز متوسط 10 لیتری آقای خاک,...","[19960.0, nan, nan, nan, 18000.0, 6480.0, 2500..."
50,21-116,ورمی کمپوست,1.700393e+04,5.000000e+03,45000.00,1.398516e+04,"[خاک ورمی کمپوست سایز متوسط 10 لیتری آقای خاک,...","[19960.0, nan, nan, nan, 6480.0, 45000.0, 5000..."
51,21-117,کود سبز,1.530000e+05,5.400000e+04,230000.00,9.003888e+04,[کود اسید انفوریک مایع مگافرتیل ان اس 10 لیتری...,"[54000.0, 230000.0, 175000.0]"
52,21-118,اسید هیومیک,6.479957e+05,1.040000e+04,19320000.00,2.515547e+06,"[کود هیومیک اسید مایع هیومولایف 5 لیتر, کود هی...","[231000.0, 88176.0, 75504.0, 228360.0, 82280.0..."
53,21-119,اسید آمینه,6.790000e+06,9.700000e+05,18400000.00,1.005457e+07,"[اسید آمینه کیلیترین 1 لیتری - 1, کود مایع اسی...","[1000000.0, 970000.0, 18400000.0]"
54,21-120,فولیک اسید,4.397900e+05,4.397900e+05,439790.00,NaN,[گابری هیومیک مایع (اسید هیومیک + فولیک)(20لیت...,[439790.0]
55,21-121,گوگرد آلی,3.800000e+04,3.800000e+04,38000.00,0.000000e+00,"[گوگرد آلی گرانوله, گوگرد آلی گرانوله]","[38000.0, 38000.0]"
56,22-111,جلبک دریایی,1.064860e+06,1.776000e+05,2150000.00,6.659804e+05,"[کود جلبک دریایی سیفول, کود جلبک دریایی مایع ش...","[187000.0, 177600.0, 2150000.0, 1920000.0, 950..."
57,99-113,ضد شوری,2.665930e+05,6.240000e+04,610800.00,2.383079e+05,"[کود ضد شوری فورنوترینت (Anti Salt) 5 لیتر, کو...","[62400.0, 210672.0, 182500.0, 610800.0]"
58,99-115,اصلاح کننده خاک,6.912500e+05,1.825000e+05,1200000.00,7.194811e+05,[کود تقویتی اصلاح کننده خاک و ضد شوری پرک سویل...,"[182500.0, 1200000.0]"

***Remove Irrelevent Price Values***

In [252]:
def remove_outliers_iqr(prices, names, k=1.5):
    """
    Remove outlier prices and corresponding names using the IQR method.
    prices: list of floats
    names: list of strings (same length as prices)
    Returns filtered prices and names.
    """
    if not prices or len(prices) < 4:
        # Not enough data to filter, return original
        return prices, names

    arr = np.array(prices)
    q1 = np.percentile(arr, 25)
    q3 = np.percentile(arr, 75)
    iqr = q3 - q1
    lower_bound = q1 - k * iqr
    upper_bound = q3 + k * iqr

    filtered_prices = []
    filtered_names = []
    for price, name in zip(prices, names):
        if lower_bound <= price <= upper_bound:
            filtered_prices.append(price)
            filtered_names.append(name)

    return filtered_prices, filtered_names

cleaned_data = []

for idx, row in result_df.iterrows():
    prices = row['listOfPrices']
    names = row['listOfNames']

    filtered_prices, filtered_names = remove_outliers_iqr(prices, names)

    if filtered_prices:
        avg = np.mean(filtered_prices)
        minimum = np.min(filtered_prices)
        maximum = np.max(filtered_prices)
        std = np.std(filtered_prices, ddof=1) if len(filtered_prices) > 1 else 0.0
    else:
        avg = minimum = maximum = std = np.nan
        filtered_names = []

    cleaned_data.append({
        "code": row['code'],
        "name": row['name'],
        "avg": avg,
        "min": minimum,
        "max": maximum,
        "std": std,
        "listOfNames": filtered_names,
        "listOfPrices": filtered_prices,
    })

cleaned_df = pd.DataFrame(cleaned_data)
print(cleaned_df)

      code                 name           avg         min          max  \
0   17-111             20 20 20  1.131000e+07   300000.00  29000000.00
1   17-113             10 52 10  1.798000e+07  3960000.00  32000000.00
2   17-129             18 18 18  4.630000e+06  4630000.00   4630000.00
3   17-139              19 6 20  4.630000e+06  4630000.00   4630000.00
4   11-111                 اوره  6.100000e+04    45000.00     70000.00
5   11-115       سولفات آمونیوم  7.904583e+04     2000.00    141999.94
6   11-116  اوره با پوشش گوگردی  2.490000e+05   116000.00    392000.00
7   11-119        فسفات آمونیوم  2.578300e+05   111600.00    470000.00
8   11-120         نیترات کلسیم  1.352500e+05     4400.00    285000.00
9   11-121        نیترات پتاسیم  5.716334e+05   200000.00   1300000.00
10  12-111           اوره فسفات  1.255200e+06   175000.00   3250000.00
11  12-112    مونو فسفات پتاسیم  1.730571e+05     5400.00    412500.00
12  12-114         فسفیت پتاسیم  1.000467e+06   780000.00   1411000.00
13  12-121      سوپر فسفات ساده  1.221000e+05    68400.02    152000.00
14  12-122   مونو آمونیوم فسفات  2.819000e+05   180000.00    399500.00
15  12-124         فسفات گوگردی  1.176600e+05    17000.00    170000.00
16  13-111        سولفات پتاسیم  1.153043e+05     1500.00    290000.00
17  13-113    مونو پتاسیم فسفات  1.730571e+05     5400.00    412500.00
18  13-114        پتاسیم نیترات  5.716334e+05   200000.00   1300000.00
19  13-115        پتاسیم منیزیم  1.389800e+05   135960.00    142000.00
20  13-117        پتاسه گرانوله  1.020000e+05   102000.00    102000.00
21  13-119       پتاسیم سیلیکات  2.946000e+05   147000.00    500000.00
22  14-111         کلسیم نیترات  1.352500e+05     4400.00    285000.00
23  14-112           کلات کلسیم  1.632500e+05   162500.00    164000.00
24  14-117         کلسیم منیزیم  4.550000e+05   157500.00   1050000.00
25  15-111        سولفات منیزیم  8.047333e+04    23200.00    157500.00
26  15-112        نیترات منیزیم  2.125000e+06  2125000.00   2125000.00
27  15-115          پتاس منیزیم  1.389800e+05   135960.00    142000.00
28  16-111          گوگرد پودری  1.170667e+05     2200.00    273000.00
29  16-112        گوگرد گرانوله  6.450000e+04    38000.00     91000.00
30  16-114           گوگرد مایع  1.363091e+05    10250.00    350000.00
31  16-115    گوگرد بنتونیت دار  1.006667e+05    91000.00    120000.00
32  18-113               چالکود  9.174667e+04    22440.00    134000.00
33  19-112         سولفات منگنز  7.313600e+05     7000.00   1837000.00
34  19-114        آهن منگنز روی  7.500000e+06  7500000.00   7500000.00
35  19-116           سولفات آهن  1.066333e+05    23200.00    180000.00
36  19-117             کلات آهن  1.298500e+06   200000.00   1956000.00
37  19-120             کلات روی  1.788333e+05   162500.00    210000.00
38  19-121           سولفات روی  4.372100e+05   139200.00    640000.00
39  19-124            فسفات روی  1.116000e+05   111600.00    111600.00
40  19-129             کلات بور  1.632500e+05   162500.00    164000.00
41  19-132            سولفات مس  2.139667e+06   246000.00   5926000.00
42  19-141                  کلر  6.875000e+05   540000.00    990000.00
43  19-143            میکرومیکس  3.770000e+05    93000.00    850000.00
44  19-145       سیلیکات پتاسیم  2.946000e+05   147000.00    500000.00
45  20-112                 مرغی  5.607614e+04     6800.00    120000.00
46  21-111            پلیت مرغی  5.900000e+04     9100.00    158800.00
47  21-112            مرغی مایع  6.618500e+04    12950.00    120000.00
48  21-113                 ماهی  6.550000e+04    52500.00     80000.00
49  21-115               کمپوست           NaN         NaN          NaN
50  21-116          ورمی کمپوست           NaN         NaN          NaN
51  21-117              کود سبز  1.530000e+05    54000.00    230000.00
52  21-118          اسید هیومیک  2.482406e+05    10400.00    766000.00
53  21-119           اسید آمینه  6.790000e+06   970000.00  18400000.00
54  21-120           فولیک اسید  4.397900e+05   439790.00    439790.00
55  21-121            گوگرد آلی  3.800000e+04    38000.00     38000.00
56  22-111          جلبک دریایی  1.064860e+06   177600.00   2150000.00
57  99-113              ضد شوری  1.518573e+05    62400.00    210672.00
58  99-115      اصلاح کننده خاک  6.912500e+05   182500.00   1200000.00

             std                                        listOfNames  \
0   1.547221e+07  [کود سه 20 مایع تری پرو فارمونتی NPK 20 20 20+...
1   1.982727e+07  [کود NPK 10 52 10 کوالی مکس, کود 10 52 10 NPK ...
2   0.000000e+00                         [کود NPK 18 18 18 باواریا]
3   0.000000e+00                          [کود NPK 19 6 20 باواریا]
4   1.389244e+04  [قیمت کود شیمیایی یا اوره 2 کیلویی, کود ترن 46...
5   4.307121e+04  [سولفات آمونیوم پودری, سولفات آمونیوم ازبک, سو...
6   1.537921e+05  [اوره با پوشش گوگردی, اوره با پوشش گوگردی, اور...
7   1.109919e+05  [فسفات آمونیوم, دی آمونیوم فسفات چینی, فسفات آ...
8   8.593930e+04  [نیترات کلسیم, نیترات کلسیم, کود نیترات کلسیم ...
9   4.918786e+05  [نیترات پتاسیم, نیترات پتاسیم, نیترات پتاسیم و...
10  1.457290e+06  [کود اوره فسفات (NP 18-44) فلوریش 10 کیلو, کود...
11  1.423705e+05  [مونو پتاسیم فسفات, مونو پتاسیم فسفات, کود تقو...
12  2.455559e+05  [کود فسفیت پتاسیم (فوس وید ) سوپر مکس 1 لیتر, ...
13  3.961867e+04  [سوپر فسفات ساده, سوپر فسفات ساده, سوپر فسفات ...
14  8.486784e+04  [کود مونو آمونیوم فسفات 0-61-12 فرمولایف 10 کی...
15  8.719729e+04         [فسفات گوگردی, فسفات گوگردی, فسفات گوگردی]
16  8.110102e+04  [سولفات پتاسیم منیزیم 10/4, سولفات پتاسیم منیز...
17  1.423705e+05  [مونو پتاسیم فسفات, مونو پتاسیم فسفات, کود تقو...
18  4.918786e+05  [نیترات پتاسیم, نیترات پتاسیم, نیترات پتاسیم و...
19  4.270925e+03  [سولفات پتاسیم منیزیم 10/4, سولفات پتاسیم منیز...
20  0.000000e+00               [پتاسه گرانوله30%, پتاسه گرانوله30%]
21  1.355168e+05  [کود سیلیکات پتاسیم 2/5 لیتری آگروفر, سیلیکات ...
22  8.593930e+04  [نیترات کلسیم, نیترات کلسیم, کود نیترات کلسیم ...
23  1.060660e+03  [کود کلاته کلسیم-بور-روی مایع کلبومکس فارمونتی...
24  5.152851e+05  [کلسیم منیزیم, کلسیم منیزیم, کود کشاورزی کلسیم...
25  5.370865e+04  [سولفات پتاسیم منیزیم 10/4, سولفات منیزیم, سول...
26  0.000000e+00                      [کود نیترات منیزیم کوالی مکس]
27  4.270925e+03  [سولفات پتاسیم منیزیم 10/4, سولفات پتاسیم منیز...
28  1.399929e+05  [نیترات پتاسیم و کربن فعال و گوگرد پودری فلات ...
29  3.059956e+04  [گوگرد آلی گرانوله, گوگرد گرانوله بنتونیت دار ...
30  1.155532e+05  [گوگرد مایع, گوگرد مایع, کود گوگرد مایع شوک 20...
31  1.674316e+04  [گوگرد بنتونیت دار, گوگرد گرانوله بنتونیت دار ...
32  6.050058e+04  [چالکود فرموکمپلکس همراه با گوگرد و عناصر ریزم...
33  7.344904e+05  [سولفات منگنز چینی, سولفات منگنز چینی, کود سول...
34  0.000000e+00  [کود اسپانیایی ریز مغذی سه گانه آهن روی منگنز ...
35  6.758253e+04  [سولفات آهن 17 درصد, سولفات آهن 20 درصد, سولفا...
36  8.219025e+05  [کلات آهن لایفر 6٪ اسپانیایی, کلات آهن, کود آه...
37  2.700154e+04  [کود کلاته کلسیم-بور-روی مایع کلبومکس فارمونتی...
38  1.910216e+05  [سولفات روی پودری 34%, سولفات روی پودری 22 درص...
39  0.000000e+00  [کود دی آمونیوم فسفات 4 لیتری (فسفر بالا رویش 2)]
40  1.060660e+03  [کود کلاته کلسیم-بور-روی مایع کلبومکس فارمونتی...
41  3.279061e+06  [کات کبود (سولفات مس)5 کیلو گرم, کات کبود (سول...
42  2.083867e+05  [سم قارچ کش کوپراکسی کلراید اکسی کلرور مس پودر...
43  3.520691e+05  [میکرومیکس بازرگان کالا بسته بندی 1 لیتری یک غ...
44  1.355168e+05  [کود سیلیکات پتاسیم 2/5 لیتری آگروفر, سیلیکات ...
45  3.341279e+04  [کود مرغی مایع نیو داتیس آل (NEW DATIS ALL) حج...
46  8.642934e+04  [کود پلیت مرغی 25 کیلوگرمی, گابری گلدن(پلیت کو...
47  3.241302e+04  [کود مرغی مایع نیو داتیس آل (NEW DATIS ALL) حج...
48  1.350926e+04  [عصاره کود مرغ و ماهی غنی شده با هیومیک و فولو...
49           NaN                                                 []
50           NaN                                                 []
51  9.003888e+04  [کود اسید انفوریک مایع مگافرتیل ان اس 10 لیتری...
52  1.898396e+05  [کود هیومیک اسید مایع هیومولایف 5 لیتر, کود هی...
53  1.005457e+07  [اسید آمینه کیلیترین 1 لیتری - 1, کود مایع اسی...
54  0.000000e+00  [گابری هیومیک مایع (اسید هیومیک + فولیک)(20لیت...
55  0.000000e+00             [گوگرد آلی گرانوله, گوگرد آلی گرانوله]
56  6.659804e+05  [کود جلبک دریایی سیفول, کود جلبک دریایی مایع ش...
57  7.874247e+04  [کود ضد شوری فورنوترینت (Anti Salt) 5 لیتر, کو...
58  7.194811e+05  [کود تقویتی اصلاح کننده خاک و ضد شوری پرک سویل...

                                         listOfPrices
0                   [300000.0, 4630000.0, 29000000.0]
1                             [32000000.0, 3960000.0]
2                                         [4630000.0]
3                                         [4630000.0]
4                         [70000.0, 68000.0, 45000.0]
5   [141999.94, 98000.0, 106000.0, 111000.0, 11100...
6           [372000.16, 116000.0, 116000.0, 392000.0]
7   [181600.0, 470000.0, 181600.0, 111600.0, 22200...
8   [190000.0, 190000.0, 111800.0, 150000.0, 92500...
9   [1100000.16, 1300000.0, 273000.0, 258800.0, 29...
10  [191000.0, 3250000.0, 280000.0, 175000.0, 2380...
11  [100000.0, 100000.0, 412500.0, 300000.0, 83500...
12  [897000.0, 1411000.0, 780000.0, 782800.0, 1160...
13           [68400.02, 152000.0, 152000.0, 116000.0]
14  [222000.0, 399500.0, 308000.0, 300000.0, 18000...
15                      [165980.0, 17000.0, 170000.0]
16  [135960.0, 142000.0, 168000.0, 150000.0, 69200...
17  [100000.0, 100000.0, 412500.0, 300000.0, 83500...
18  [1100000.16, 1300000.0, 273000.0, 258800.0, 29...
19                               [135960.0, 142000.0]
20                               [102000.0, 102000.0]
21  [147000.0, 350000.0, 500000.0, 236000.0, 24000...
22  [190000.0, 190000.0, 111800.0, 150000.0, 92500...
23                               [162500.0, 164000.0]
24                    [157500.0, 157500.0, 1050000.0]
25  [135960.0, 63000.0, 157500.0, 142000.0, 30000....
26                                        [2125000.0]
27                               [135960.0, 142000.0]
28                        [273000.0, 76000.0, 2200.0]
29               [38000.0, 91000.0, 91000.0, 38000.0]
30  [350000.0, 350000.0, 13000.0, 120000.0, 280000...
31                       [120000.0, 91000.0, 91000.0]
32                      [118800.0, 22440.0, 134000.0]
33  [850000.0, 850000.0, 112800.0, 7000.0, 1837000.0]
34                                        [7500000.0]
35  [120000.0, 169000.0, 180000.0, 120000.0, 27600...
36        [200000.0, 1900000.0, 1138000.0, 1956000.0]
37                     [162500.0, 164000.0, 210000.0]
38  [430000.0, 640000.0, 620000.04, 245200.0, 4300...
39                                         [111600.0]
40                               [162500.0, 164000.0]
41                    [247000.0, 246000.0, 5926000.0]
42           [990000.0, 540000.0, 560000.0, 660000.0]
43            [850000.0, 125000.0, 93000.0, 440000.0]
44  [147000.0, 350000.0, 500000.0, 236000.0, 24000...
45  [65280.0, 78672.0, 104280.0, 120000.0, 120000....
46                         [9100.0, 158800.0, 9100.0]
47  [65280.0, 104280.0, 120000.0, 120000.0, 84250....
48      [80000.0, 60000.0, 55000.0, 52500.0, 80000.0]
49                                                 []
50                                                 []
51                      [54000.0, 230000.0, 175000.0]
52  [231000.0, 88176.0, 75504.0, 228360.0, 82280.0...
53                  [1000000.0, 970000.0, 18400000.0]
54                                         [439790.0]
55                                 [38000.0, 38000.0]
56  [187000.0, 177600.0, 2150000.0, 1920000.0, 950...
57                      [62400.0, 210672.0, 182500.0]
58                              [182500.0, 1200000.0]

In [253]:
def mad_based_filter(prices, names, thresh=3.5):
    """
    Remove outliers using Median Absolute Deviation (MAD).
    prices: list of floats
    names: list of strings (same length)
    thresh: threshold for modified z-score to consider outlier (usually 3-3.5)
    Returns filtered prices and names.
    """
    if not prices or len(prices) < 3:
        # Not enough data to filter robustly, return as is
        return prices, names

    arr = np.array(prices)
    median = np.median(arr)
    mad = np.median(np.abs(arr - median))

    if mad == 0:
        # MAD is zero means no variation, return original
        return prices, names

    modified_z_scores = 0.6745 * (arr - median) / mad

    filtered_prices = []
    filtered_names = []
    for price, name, z in zip(prices, names, modified_z_scores):
        if np.abs(z) <= thresh:
            filtered_prices.append(price)
            filtered_names.append(name)

    return filtered_prices, filtered_names

cleaned_data = []

for idx, row in result_df.iterrows():
    prices = row['listOfPrices']
    names = row['listOfNames']

    filtered_prices, filtered_names = mad_based_filter(prices, names)

    if filtered_prices:
        avg = np.mean(filtered_prices)
        minimum = np.min(filtered_prices)
        maximum = np.max(filtered_prices)
        std = np.std(filtered_prices, ddof=1) if len(filtered_prices) > 1 else 0.0
    else:
        avg = minimum = maximum = std = np.nan
        filtered_names = []

    cleaned_data.append({
        "code": row['code'],
        "name": row['name'],
        "avg": avg,
        "min": minimum,
        "max": maximum,
        "std": std,
        "listOfNames": filtered_names,
        "listOfPrices": filtered_prices,
    })

cleaned_df = pd.DataFrame(cleaned_data)
print(cleaned_df)

      code                 name           avg         min          max  \
0   17-111             20 20 20  2.465000e+06   300000.00   4630000.00
1   17-113             10 52 10  1.798000e+07  3960000.00  32000000.00
2   17-129             18 18 18  4.630000e+06  4630000.00   4630000.00
3   17-139              19 6 20  4.630000e+06  4630000.00   4630000.00
4   11-111                 اوره  6.900000e+04    68000.00     70000.00
5   11-115       سولفات آمونیوم  7.904583e+04     2000.00    141999.94
6   11-116  اوره با پوشش گوگردی  2.490000e+05   116000.00    392000.00
7   11-119        فسفات آمونیوم  2.578300e+05   111600.00    470000.00
8   11-120         نیترات کلسیم  1.352500e+05     4400.00    285000.00
9   11-121        نیترات پتاسیم  2.574500e+05   200000.00    298000.00
10  12-111           اوره فسفات  1.255200e+06   175000.00   3250000.00
11  12-112    مونو فسفات پتاسیم  1.730571e+05     5400.00    412500.00
12  12-114         فسفیت پتاسیم  1.000467e+06   780000.00   1411000.00
13  12-121      سوپر فسفات ساده  1.221000e+05    68400.02    152000.00
14  12-122   مونو آمونیوم فسفات  2.819000e+05   180000.00    399500.00
15  12-124         فسفات گوگردی  1.679900e+05   165980.00    170000.00
16  13-111        سولفات پتاسیم  1.153043e+05     1500.00    290000.00
17  13-113    مونو پتاسیم فسفات  1.730571e+05     5400.00    412500.00
18  13-114        پتاسیم نیترات  2.574500e+05   200000.00    298000.00
19  13-115        پتاسیم منیزیم  1.389800e+05   135960.00    142000.00
20  13-117        پتاسه گرانوله  1.020000e+05   102000.00    102000.00
21  13-119       پتاسیم سیلیکات  2.946000e+05   147000.00    500000.00
22  14-111         کلسیم نیترات  1.352500e+05     4400.00    285000.00
23  14-112           کلات کلسیم  1.632500e+05   162500.00    164000.00
24  14-117         کلسیم منیزیم  4.550000e+05   157500.00   1050000.00
25  15-111        سولفات منیزیم  8.047333e+04    23200.00    157500.00
26  15-112        نیترات منیزیم  2.125000e+06  2125000.00   2125000.00
27  15-115          پتاس منیزیم  1.389800e+05   135960.00    142000.00
28  16-111          گوگرد پودری  1.170667e+05     2200.00    273000.00
29  16-112        گوگرد گرانوله  6.450000e+04    38000.00     91000.00
30  16-114           گوگرد مایع  1.776782e+05    10250.00    550000.00
31  16-115    گوگرد بنتونیت دار  1.006667e+05    91000.00    120000.00
32  18-113               چالکود  1.264000e+05   118800.00    134000.00
33  19-112         سولفات منگنز  7.313600e+05     7000.00   1837000.00
34  19-114        آهن منگنز روی  7.500000e+06  7500000.00   7500000.00
35  19-116           سولفات آهن  1.066333e+05    23200.00    180000.00
36  19-117             کلات آهن  1.298500e+06   200000.00   1956000.00
37  19-120             کلات روی  1.788333e+05   162500.00    210000.00
38  19-121           سولفات روی  4.372100e+05   139200.00    640000.00
39  19-124            فسفات روی  1.116000e+05   111600.00    111600.00
40  19-129             کلات بور  1.632500e+05   162500.00    164000.00
41  19-132            سولفات مس  2.465000e+05   246000.00    247000.00
42  19-141                  کلر  5.866667e+05   540000.00    660000.00
43  19-143            میکرومیکس  3.770000e+05    93000.00    850000.00
44  19-145       سیلیکات پتاسیم  2.946000e+05   147000.00    500000.00
45  20-112                 مرغی  5.961834e+04     6800.00    158800.00
46  21-111            پلیت مرغی  5.900000e+04     9100.00    158800.00
47  21-112            مرغی مایع  6.618500e+04    12950.00    120000.00
48  21-113                 ماهی  6.550000e+04    52500.00     80000.00
49  21-115               کمپوست           NaN         NaN          NaN
50  21-116          ورمی کمپوست           NaN         NaN          NaN
51  21-117              کود سبز  1.530000e+05    54000.00    230000.00
52  21-118          اسید هیومیک  2.482406e+05    10400.00    766000.00
53  21-119           اسید آمینه  9.850000e+05   970000.00   1000000.00
54  21-120           فولیک اسید  4.397900e+05   439790.00    439790.00
55  21-121            گوگرد آلی  3.800000e+04    38000.00     38000.00
56  22-111          جلبک دریایی  1.064860e+06   177600.00   2150000.00
57  99-113              ضد شوری  1.518573e+05    62400.00    210672.00
58  99-115      اصلاح کننده خاک  6.912500e+05   182500.00   1200000.00

             std                                        listOfNames  \
0   3.061772e+06  [کود سه 20 مایع تری پرو فارمونتی NPK 20 20 20+...
1   1.982727e+07  [کود NPK 10 52 10 کوالی مکس, کود 10 52 10 NPK ...
2   0.000000e+00                         [کود NPK 18 18 18 باواریا]
3   0.000000e+00                          [کود NPK 19 6 20 باواریا]
4   1.414214e+03  [قیمت کود شیمیایی یا اوره 2 کیلویی, کود ترن 46...
5   4.307121e+04  [سولفات آمونیوم پودری, سولفات آمونیوم ازبک, سو...
6   1.537921e+05  [اوره با پوشش گوگردی, اوره با پوشش گوگردی, اور...
7   1.109919e+05  [فسفات آمونیوم, دی آمونیوم فسفات چینی, فسفات آ...
8   8.593930e+04  [نیترات کلسیم, نیترات کلسیم, کود نیترات کلسیم ...
9   4.158698e+04  [نیترات پتاسیم و کربن فعال و گوگرد پودری فلات ...
10  1.457290e+06  [کود اوره فسفات (NP 18-44) فلوریش 10 کیلو, کود...
11  1.423705e+05  [مونو پتاسیم فسفات, مونو پتاسیم فسفات, کود تقو...
12  2.455559e+05  [کود فسفیت پتاسیم (فوس وید ) سوپر مکس 1 لیتر, ...
13  3.961867e+04  [سوپر فسفات ساده, سوپر فسفات ساده, سوپر فسفات ...
14  8.486784e+04  [کود مونو آمونیوم فسفات 0-61-12 فرمولایف 10 کی...
15  2.842569e+03                       [فسفات گوگردی, فسفات گوگردی]
16  8.110102e+04  [سولفات پتاسیم منیزیم 10/4, سولفات پتاسیم منیز...
17  1.423705e+05  [مونو پتاسیم فسفات, مونو پتاسیم فسفات, کود تقو...
18  4.158698e+04  [نیترات پتاسیم و کربن فعال و گوگرد پودری فلات ...
19  4.270925e+03  [سولفات پتاسیم منیزیم 10/4, سولفات پتاسیم منیز...
20  0.000000e+00               [پتاسه گرانوله30%, پتاسه گرانوله30%]
21  1.355168e+05  [کود سیلیکات پتاسیم 2/5 لیتری آگروفر, سیلیکات ...
22  8.593930e+04  [نیترات کلسیم, نیترات کلسیم, کود نیترات کلسیم ...
23  1.060660e+03  [کود کلاته کلسیم-بور-روی مایع کلبومکس فارمونتی...
24  5.152851e+05  [کلسیم منیزیم, کلسیم منیزیم, کود کشاورزی کلسیم...
25  5.370865e+04  [سولفات پتاسیم منیزیم 10/4, سولفات منیزیم, سول...
26  0.000000e+00                      [کود نیترات منیزیم کوالی مکس]
27  4.270925e+03  [سولفات پتاسیم منیزیم 10/4, سولفات پتاسیم منیز...
28  1.399929e+05  [نیترات پتاسیم و کربن فعال و گوگرد پودری فلات ...
29  3.059956e+04  [گوگرد آلی گرانوله, گوگرد گرانوله بنتونیت دار ...
30  1.678102e+05  [گوگرد مایع پتاسه, گوگرد مایع, گوگرد مایع پتاس...
31  1.674316e+04  [گوگرد بنتونیت دار, گوگرد گرانوله بنتونیت دار ...
32  1.074802e+04  [چالکود فرموکمپلکس همراه با گوگرد و عناصر ریزم...
33  7.344904e+05  [سولفات منگنز چینی, سولفات منگنز چینی, کود سول...
34  0.000000e+00  [کود اسپانیایی ریز مغذی سه گانه آهن روی منگنز ...
35  6.758253e+04  [سولفات آهن 17 درصد, سولفات آهن 20 درصد, سولفا...
36  8.219025e+05  [کلات آهن لایفر 6٪ اسپانیایی, کلات آهن, کود آه...
37  2.700154e+04  [کود کلاته کلسیم-بور-روی مایع کلبومکس فارمونتی...
38  1.910216e+05  [سولفات روی پودری 34%, سولفات روی پودری 22 درص...
39  0.000000e+00  [کود دی آمونیوم فسفات 4 لیتری (فسفر بالا رویش 2)]
40  1.060660e+03  [کود کلاته کلسیم-بور-روی مایع کلبومکس فارمونتی...
41  7.071068e+02  [کات کبود (سولفات مس)5 کیلو گرم, کات کبود (سول...
42  6.429101e+04  [سم دیکلروس اسپیدارپردیس 1 لیتر, سم علف کش اخت...
43  3.520691e+05  [میکرومیکس بازرگان کالا بسته بندی 1 لیتری یک غ...
44  1.355168e+05  [کود سیلیکات پتاسیم 2/5 لیتری آگروفر, سیلیکات ...
45  3.795275e+04  [کود مرغی مایع نیو داتیس آل (NEW DATIS ALL) حج...
46  8.642934e+04  [کود پلیت مرغی 25 کیلوگرمی, گابری گلدن(پلیت کو...
47  3.241302e+04  [کود مرغی مایع نیو داتیس آل (NEW DATIS ALL) حج...
48  1.350926e+04  [عصاره کود مرغ و ماهی غنی شده با هیومیک و فولو...
49           NaN                                                 []
50           NaN                                                 []
51  9.003888e+04  [کود اسید انفوریک مایع مگافرتیل ان اس 10 لیتری...
52  1.898396e+05  [کود هیومیک اسید مایع هیومولایف 5 لیتر, کود هی...
53  2.121320e+04  [اسید آمینه کیلیترین 1 لیتری - 1, کود مایع اسی...
54  0.000000e+00  [گابری هیومیک مایع (اسید هیومیک + فولیک)(20لیت...
55  0.000000e+00             [گوگرد آلی گرانوله, گوگرد آلی گرانوله]
56  6.659804e+05  [کود جلبک دریایی سیفول, کود جلبک دریایی مایع ش...
57  7.874247e+04  [کود ضد شوری فورنوترینت (Anti Salt) 5 لیتر, کو...
58  7.194811e+05  [کود تقویتی اصلاح کننده خاک و ضد شوری پرک سویل...

                                         listOfPrices
0                               [300000.0, 4630000.0]
1                             [32000000.0, 3960000.0]
2                                         [4630000.0]
3                                         [4630000.0]
4                                  [70000.0, 68000.0]
5   [141999.94, 98000.0, 106000.0, 111000.0, 11100...
6           [372000.16, 116000.0, 116000.0, 392000.0]
7   [181600.0, 470000.0, 181600.0, 111600.0, 22200...
8   [190000.0, 190000.0, 111800.0, 150000.0, 92500...
9            [273000.0, 258800.0, 298000.0, 200000.0]
10  [191000.0, 3250000.0, 280000.0, 175000.0, 2380...
11  [100000.0, 100000.0, 412500.0, 300000.0, 83500...
12  [897000.0, 1411000.0, 780000.0, 782800.0, 1160...
13           [68400.02, 152000.0, 152000.0, 116000.0]
14  [222000.0, 399500.0, 308000.0, 300000.0, 18000...
15                               [165980.0, 170000.0]
16  [135960.0, 142000.0, 168000.0, 150000.0, 69200...
17  [100000.0, 100000.0, 412500.0, 300000.0, 83500...
18           [273000.0, 258800.0, 298000.0, 200000.0]
19                               [135960.0, 142000.0]
20                               [102000.0, 102000.0]
21  [147000.0, 350000.0, 500000.0, 236000.0, 24000...
22  [190000.0, 190000.0, 111800.0, 150000.0, 92500...
23                               [162500.0, 164000.0]
24                    [157500.0, 157500.0, 1050000.0]
25  [135960.0, 63000.0, 157500.0, 142000.0, 30000....
26                                        [2125000.0]
27                               [135960.0, 142000.0]
28                        [273000.0, 76000.0, 2200.0]
29               [38000.0, 91000.0, 91000.0, 38000.0]
30  [550000.0, 350000.0, 550000.0, 350000.0, 13000...
31                       [120000.0, 91000.0, 91000.0]
32                               [118800.0, 134000.0]
33  [850000.0, 850000.0, 112800.0, 7000.0, 1837000.0]
34                                        [7500000.0]
35  [120000.0, 169000.0, 180000.0, 120000.0, 27600...
36        [200000.0, 1900000.0, 1138000.0, 1956000.0]
37                     [162500.0, 164000.0, 210000.0]
38  [430000.0, 640000.0, 620000.04, 245200.0, 4300...
39                                         [111600.0]
40                               [162500.0, 164000.0]
41                               [247000.0, 246000.0]
42                     [540000.0, 560000.0, 660000.0]
43            [850000.0, 125000.0, 93000.0, 440000.0]
44  [147000.0, 350000.0, 500000.0, 236000.0, 24000...
45  [65280.0, 78672.0, 104280.0, 120000.0, 120000....
46                         [9100.0, 158800.0, 9100.0]
47  [65280.0, 104280.0, 120000.0, 120000.0, 84250....
48      [80000.0, 60000.0, 55000.0, 52500.0, 80000.0]
49                                                 []
50                                                 []
51                      [54000.0, 230000.0, 175000.0]
52  [231000.0, 88176.0, 75504.0, 228360.0, 82280.0...
53                              [1000000.0, 970000.0]
54                                         [439790.0]
55                                 [38000.0, 38000.0]
56  [187000.0, 177600.0, 2150000.0, 1920000.0, 950...
57                      [62400.0, 210672.0, 182500.0]
58                              [182500.0, 1200000.0]

save the result

In [254]:
import datetime
import os

os.makedirs("estimation_output", exist_ok=True)

now_str = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
filename = f"estimation_output/fertilizer_price_estimations_{now_str}.xlsx"

result_df.to_excel(filename, sheet_name="Fertilizer_Price_Estimations", index=False)